#!/bin/bash


need_pass=437
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.20/compiler/qualifiers/fn-out-array-allowed.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/fn-out-array-allowed.vert pass 1.20 --check-link"
run_test "spec/glsl-1.20/compiler/qualifiers/in-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/in-01.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/qualifiers/in-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/in-02.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/qualifiers/inout-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/inout-01.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/qualifiers/invariant-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/invariant-01.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/qualifiers/out-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/out-01.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/qualifiers/out-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/out-02.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/qualifiers/out-conversion-int-to-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/qualifiers/out-conversion-int-to-float.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/storage-qualfiers/static-write-attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/storage-qualfiers/static-write-attribute-01.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/storage-qualfiers/static-write-attribute-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/storage-qualfiers/static-write-attribute-02.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/storage-qualfiers/static-write-point-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/storage-qualfiers/static-write-point-coord.frag fail 1.20"
run_test "spec/glsl-1.20/compiler/storage-qualfiers/static-write-varying-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/storage-qualfiers/static-write-varying-01.frag fail 1.20"
run_test "spec/glsl-1.20/compiler/storage-qualfiers/static-write-varying-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/storage-qualfiers/static-write-varying-02.frag fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-add.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-add.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bool-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bool-float.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bool-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bool-int.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec2-ivec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec2-ivec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec2-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec2-vec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec3-ivec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec3-ivec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec3-vec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec3-vec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec4-ivec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec4-ivec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec4-vec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-bvec4-vec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-float-bool.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-float-bool.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-float-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-float-int.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-int-bool.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-int-bool.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-int-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-int-float.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec2-bvec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec2-bvec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec2-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec2-vec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec3-bvec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec3-bvec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec3-vec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec3-vec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec4-bvec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec4-bvec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec4-vec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-ivec4-vec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec2-bvec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec2-bvec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec2-ivec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec2-ivec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec3-bvec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec3-bvec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec3-ivec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec3-ivec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec4-bvec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec4-bvec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec4-ivec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-conversion-vec4-ivec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign-implicit-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-assign.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-assign.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-attribute.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-attribute.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-constant-index-implicit-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-constant-index-implicit-size.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-constant-index-negative.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-constant-index-negative.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-constant-index-too-large.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-constant-index-too-large.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bool-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bool-float.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bool-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bool-int.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec2-ivec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec2-ivec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec2-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec2-vec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec3-ivec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec3-ivec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec3-vec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec3-vec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec4-ivec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec4-ivec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec4-vec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-bvec4-vec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-float-bool.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-float-bool.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-float-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-float-int.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-int-bool.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-int-bool.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-int-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-int-float.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec2-bvec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec2-bvec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec2-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec2-vec2.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec3-bvec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec3-bvec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec3-vec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec3-vec3.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec4-bvec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec4-bvec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec4-vec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-ivec4-vec4.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec2-bvec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec2-bvec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec2-ivec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec2-ivec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec3-bvec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec3-bvec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec3-ivec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec3-ivec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec4-bvec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec4-bvec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec4-ivec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-implicit-conversion-vec4-ivec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-mismatched-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor-mismatched-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-ctor.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-divide.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-divide.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-implicit-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-implicit-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-matrix.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-matrix.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-mismatched-base-type.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-mismatched-base-type.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-mismatched-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-mismatched-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-vector.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-equal-vector.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-equal.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-equal.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-function-parameter-implicit-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-function-parameter-implicit-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-function-parameter-unsized.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-function-parameter-unsized.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-function-return-unsized.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-function-return-unsized.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-function-return.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-function-return.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-greater-equal.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-greater-equal.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-greater.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-greater.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-length-implicit-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-length-implicit-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-length-with-argument.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-length-with-argument.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-length.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-length.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-less-equal.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-less-equal.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-less.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-less.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-and.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-and.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-not.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-not.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-or.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-or.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-xor.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-logical-xor.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-multidimensional-new-syntax.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-multidimensional-new-syntax.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-multidimensional.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-multidimensional.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-multiply.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-multiply.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-negate.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-negate.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-implicit-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-implicit-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-matrix.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-matrix.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-mismatched-base-type.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-mismatched-base-type.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-mismatched-size.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-mismatched-size.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-vertor.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal-vertor.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-not-equal.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-any-type.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-any-type.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-declaration.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-declaration.frag fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-declaration.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-declaration.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-definition.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-definition.frag fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-definition.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-function-parameter-definition.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-structure-field.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-structure-field.frag fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-structure-field.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-array-structure-field.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-of-struct.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-of-struct.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-positive.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-positive.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-postdecrement.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-postdecrement.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-postincrement.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-postincrement.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-predecrement.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-predecrement.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-preincrement.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-preincrement.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-01.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-initializer.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-initializer.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-too-small.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-too-small.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-wrong-base-type.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-redeclaration-wrong-base-type.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-selection.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-selection.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-sequence.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-sequence.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-shadow-redeclaration.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-shadow-redeclaration.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bool.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bool.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bvec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bvec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bvec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bvec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bvec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-bvec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-constant-cast.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-constant-cast.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-constant-relational.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-constant-relational.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-float.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-int.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-ivec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-ivec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-ivec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-ivec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-ivec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-ivec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-length.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-length.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-negative.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-negative.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-non-builtin-function.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-non-builtin-function.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-not-constant.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-not-constant.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-selection.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-selection.vert pass 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-sequence.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-sequence.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-vec2.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-vec3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-vec3.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-vec4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-vec4.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-with-side-effect.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-with-side-effect.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-size-zero.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-size-zero.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-subtract.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-subtract.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-variable-index-implicit-size-global.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-variable-index-implicit-size-global.vert fail 1.20"
run_test "spec/glsl-1.20/compiler/structure-and-array-operations/array-variable-index-implicit-size-local.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.20/compiler/structure-and-array-operations/array-variable-index-implicit-size-local.vert fail 1.20"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-matrixCompMult-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-div-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x3-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat2x4-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x2-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat3x4-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x2-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-mat4x3-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-mult-vec4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec3-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec3-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec3-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec3-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec4-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec4-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec4-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec4-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x3-mat2x3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x4-mat2x4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x4-mat2x4.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 437 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

