#!/bin/bash


need_pass=283
failures=0
PIGLIT_PATH=/usr/local/piglit/lib64/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/piglit/lib64/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test [$name] of expected runtime $time sec: [$command]"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ pass :: $name"
  else
    let "failures++"
    echo "+ fail :: $name"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render-fog" 0.0 "bin/arb_color_buffer_float-render GL_RGBA8_SNORM fog -fbo -auto"
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render-sanity" 0.0 "bin/arb_color_buffer_float-render GL_RGBA8_SNORM sanity -fbo -auto"
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render-sanity-fog" 0.0 "bin/arb_color_buffer_float-render GL_RGBA8_SNORM sanity fog -fbo -auto"
run_test "spec/ARB_color_buffer_float/mixed-mrt" 0.0 "bin/arb_color_buffer_float-mrt mixed -fbo -auto"
run_test "spec/ARB_copy_buffer/copy_buffer_coherency" 0.0 "bin/copy_buffer_coherency -auto"
run_test "spec/ARB_copy_buffer/copybuffersubdata" 0.0 "bin/copybuffersubdata -auto"
run_test "spec/ARB_copy_buffer/dlist" 0.0 "bin/arb_copy_buffer-dlist -fbo -auto"
run_test "spec/ARB_copy_buffer/get" 0.0 "bin/arb_copy_buffer-get -fbo -auto"
run_test "spec/ARB_copy_buffer/negative-bound-zero" 0.0 "bin/arb_copy_buffer-negative-bound-zero -fbo -auto"
run_test "spec/ARB_copy_buffer/negative-bounds" 0.0 "bin/arb_copy_buffer-negative-bounds -fbo -auto"
run_test "spec/ARB_copy_buffer/negative-mapped" 0.0 "bin/arb_copy_buffer-negative-mapped -fbo -auto"
run_test "spec/ARB_copy_buffer/overlap" 0.0 "bin/arb_copy_buffer-overlap -fbo -auto"
run_test "spec/ARB_copy_buffer/targets" 0.0 "bin/arb_copy_buffer-targets -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-clear-formats" 0.0 "bin/fbo-clear-formats GL_ARB_depth_buffer_float -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-clear-formats stencil" 0.0 "bin/fbo-clear-formats GL_ARB_depth_buffer_float stencil -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-blit" 0.0 "bin/fbo-depth blit GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-copypixels" 0.0 "bin/fbo-depth copypixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-drawpixels" 0.0 "bin/fbo-depth drawpixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-readpixels" 0.0 "bin/fbo-depth readpixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-tex1d" 0.0 "bin/fbo-depth-tex1d GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-blit" 0.0 "bin/fbo-depth blit GL_DEPTH_COMPONENT32F -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-drawpixels" 0.0 "bin/fbo-depth drawpixels GL_DEPTH_COMPONENT32F -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-readpixels" 0.0 "bin/fbo-depth readpixels GL_DEPTH_COMPONENT32F -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-tex1d" 0.0 "bin/fbo-depth-tex1d GL_DEPTH_COMPONENT32F -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-blit" 0.0 "bin/fbo-depthstencil blit GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-copypixels" 0.0 "bin/fbo-depthstencil copypixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-drawpixels-24_8" 0.0 "bin/fbo-depthstencil drawpixels GL_DEPTH32F_STENCIL8 24_8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-drawpixels-32F_24_8_REV" 0.0 "bin/fbo-depthstencil drawpixels GL_DEPTH32F_STENCIL8 32F_24_8_REV -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-drawpixels-FLOAT-and-USHORT" 0.0 "bin/fbo-depthstencil drawpixels GL_DEPTH32F_STENCIL8 FLOAT-and-USHORT -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-readpixels-24_8" 0.0 "bin/fbo-depthstencil readpixels GL_DEPTH32F_STENCIL8 24_8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-readpixels-32F_24_8_REV" 0.0 "bin/fbo-depthstencil readpixels GL_DEPTH32F_STENCIL8 32F_24_8_REV -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-readpixels-FLOAT-and-USHORT" 0.0 "bin/fbo-depthstencil readpixels GL_DEPTH32F_STENCIL8 FLOAT-and-USHORT -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats GL_ARB_depth_buffer_float -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-blit" 0.0 "bin/fbo-stencil blit GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-clear" 0.0 "bin/fbo-stencil clear GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-copypixels" 0.0 "bin/fbo-stencil copypixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-drawpixels" 0.0 "bin/fbo-stencil drawpixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-readpixels" 0.0 "bin/fbo-stencil readpixels GL_DEPTH32F_STENCIL8 -fbo -auto"
run_test "spec/ARB_depth_buffer_float/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_ARB_depth_buffer_float -fbo -auto"
run_test "spec/ARB_depth_buffer_float/texwrap formats" 0.0 "bin/texwrap GL_ARB_depth_buffer_float -fbo -auto"
run_test "spec/ARB_depth_buffer_float/texwrap formats bordercolor" 0.0 "bin/texwrap GL_ARB_depth_buffer_float bordercolor -fbo -auto"
run_test "spec/ARB_depth_buffer_float/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap GL_ARB_depth_buffer_float bordercolor swizzled -fbo -auto"
run_test "spec/ARB_depth_clamp/depth_clamp" 0.0 "bin/depth_clamp -auto"
run_test "spec/ARB_depth_texture/depth-level-clamp" 0.0 "bin/depth-level-clamp -auto"
run_test "spec/ARB_depth_texture/depth-tex-modes" 0.0 "bin/depth-tex-modes -auto"
run_test "spec/ARB_depth_texture/fbo-clear-formats" 0.0 "bin/fbo-clear-formats GL_ARB_depth_texture -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-blit" 0.0 "bin/fbo-depth blit GL_DEPTH_COMPONENT16 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-copypixels" 0.0 "bin/fbo-depth copypixels GL_DEPTH_COMPONENT16 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-drawpixels" 0.0 "bin/fbo-depth drawpixels GL_DEPTH_COMPONENT16 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-readpixels" 0.0 "bin/fbo-depth readpixels GL_DEPTH_COMPONENT16 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-tex1d" 0.0 "bin/fbo-depth-tex1d GL_DEPTH_COMPONENT16 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-blit" 0.0 "bin/fbo-depth blit GL_DEPTH_COMPONENT24 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-copypixels" 0.0 "bin/fbo-depth copypixels GL_DEPTH_COMPONENT24 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-drawpixels" 0.0 "bin/fbo-depth drawpixels GL_DEPTH_COMPONENT24 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-readpixels" 0.0 "bin/fbo-depth readpixels GL_DEPTH_COMPONENT24 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-tex1d" 0.0 "bin/fbo-depth-tex1d GL_DEPTH_COMPONENT24 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-blit" 0.0 "bin/fbo-depth blit GL_DEPTH_COMPONENT32 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-copypixels" 0.0 "bin/fbo-depth copypixels GL_DEPTH_COMPONENT32 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-drawpixels" 0.0 "bin/fbo-depth drawpixels GL_DEPTH_COMPONENT32 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-readpixels" 0.0 "bin/fbo-depth readpixels GL_DEPTH_COMPONENT32 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-tex1d" 0.0 "bin/fbo-depth-tex1d GL_DEPTH_COMPONENT32 -fbo -auto"
run_test "spec/ARB_depth_texture/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats GL_ARB_depth_texture -fbo -auto"
run_test "spec/ARB_depth_texture/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_ARB_depth_texture -fbo -auto"
run_test "spec/ARB_depth_texture/texwrap formats" 0.0 "bin/texwrap GL_ARB_depth_texture -fbo -auto"
run_test "spec/ARB_depth_texture/texwrap formats bordercolor" 0.0 "bin/texwrap GL_ARB_depth_texture bordercolor -fbo -auto"
run_test "spec/ARB_depth_texture/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap GL_ARB_depth_texture bordercolor swizzled -fbo -auto"
run_test "spec/ARB_draw_buffers/arb_draw_buffers-state_change" 0.0 "bin/arb_draw_buffers-state_change -auto"
run_test "spec/ARB_draw_buffers/fbo-mrt-alphatest" 0.0 "bin/fbo-mrt-alphatest -auto"
run_test "spec/ARB_draw_buffers_blend/fbo-draw-buffers-blend" 0.0 "bin/fbo-draw-buffers-blend -auto"
run_test "spec/ARB_draw_elements_base_vertex/arb_draw_elements_base_vertex-bounds" 0.0 "bin/arb_draw_elements_base_vertex-bounds -auto"
run_test "spec/ARB_draw_elements_base_vertex/arb_draw_elements_base_vertex-drawelements" 0.0 "bin/arb_draw_elements_base_vertex-drawelements -auto"
run_test "spec/ARB_draw_elements_base_vertex/arb_draw_elements_base_vertex-drawelements-instanced" 0.0 "bin/arb_draw_elements_base_vertex-drawelements-instanced -auto"
run_test "spec/ARB_draw_elements_base_vertex/arb_draw_elements_base_vertex-drawelements-user_varrays" 0.0 "bin/arb_draw_elements_base_vertex-drawelements -auto user_varrays"
run_test "spec/ARB_draw_elements_base_vertex/arb_draw_elements_base_vertex-negative-index" 0.0 "bin/arb_draw_elements_base_vertex-negative-index -auto"
run_test "spec/ARB_draw_elements_base_vertex/arb_draw_elements_base_vertex-negative-index-user_varrays" 0.0 "bin/arb_draw_elements_base_vertex-negative-index -auto user_varrays"
run_test "spec/ARB_draw_elements_base_vertex/dlist" 0.0 "bin/arb_draw_elements_base_vertex-dlist -fbo -auto"
run_test "spec/ARB_draw_instanced/arb_draw_instanced-drawarrays" 0.0 "bin/arb_draw_instanced-drawarrays -auto"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-disabled.frag" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-disabled.frag fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-disabled.vert" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-disabled.vert fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-enabled.frag" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-enabled.frag fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-enabled.vert" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-enabled.vert pass 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/negative-instanceidarb-write.vert" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/compiler/negative-instanceidarb-write.vert fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/dlist" 0.0 "bin/arb_draw_instanced-dlist -fbo -auto"
run_test "spec/ARB_draw_instanced/draw-non-instanced" 0.0 "bin/shader_runner tests/spec/arb_draw_instanced/execution/draw-non-instanced.shader_test -auto"
run_test "spec/ARB_draw_instanced/elements" 0.0 "bin/arb_draw_instanced-elements -fbo -auto"
run_test "spec/ARB_draw_instanced/instance-array-dereference" 0.0 "bin/shader_runner tests/spec/arb_draw_instanced/execution/instance-array-dereference.shader_test -auto"
run_test "spec/ARB_draw_instanced/negative-arrays-first-negative" 0.0 "bin/arb_draw_instanced-negative-arrays-first-negative -fbo -auto"
run_test "spec/ARB_draw_instanced/negative-elements-type" 0.0 "bin/arb_draw_instanced-negative-elements-type -fbo -auto"
run_test "spec/ARB_draw_instanced/preprocessor/feature-macro-enabled.frag" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/preprocessor/feature-macro-enabled.frag pass 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/preprocessor/feature-macro-enabled.vert" 0.0 "bin/glslparsertest tests/spec/arb_draw_instanced/preprocessor/feature-macro-enabled.vert pass 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/attribute-01.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-01.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-01.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-02.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-02.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-03.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-03.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-04.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-04.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-01.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-01.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-02.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-02.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-03.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-03.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-03.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-03.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-04.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-04.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-04.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-04.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-05.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-05.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-05.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-05.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-06.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-06.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-06.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-06.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-07.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-07.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-07.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-07.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-08.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-08.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-08.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-08.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-09.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-09.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-09.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-09.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-10.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-10.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-10.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-10.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-11.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-11.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-11.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-11.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-12.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-12.frag fail 1.10 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-13.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-13.frag pass 1.10 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-14.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-14.frag fail 1.10 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-01.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-01.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-02.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-02.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-03.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-03.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-04.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-04.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/overlapping-attrib-locations-1.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/overlapping-attrib-locations-1.vert pass 1.10 --check-link"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/overlapping-attrib-locations-2.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/overlapping-attrib-locations-2.vert pass 1.10 --check-link"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/varying-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/varying-01.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/varying-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/varying-01.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/preprocessor/define.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/preprocessor/define.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/preprocessor/define.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/preprocessor/define.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/attribute-01.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-01.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-01.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-02.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-02.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-03.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-03.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-04.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-04.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-05.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-05.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/index-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/index-01.frag fail 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-01.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-01.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-02.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-02.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-03.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-03.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-03.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-03.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-04.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-04.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-04.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-04.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-05.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-05.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-05.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-05.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-06.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-06.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-06.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-06.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-07.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-07.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-07.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-07.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-08.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-08.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-08.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-08.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-09.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-09.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-09.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-09.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-10.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-10.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-10.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-10.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-11.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-11.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-11.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-11.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-12.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-12.frag fail 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-13.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-13.frag pass 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-14.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-14.frag fail 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-01.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-01.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-02.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-02.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-03.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-03.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-04.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-04.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-05.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-05.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/varying-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/varying-01.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/varying-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/varying-01.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/preprocessor/define.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/preprocessor/define.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/preprocessor/define.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/preprocessor/define.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.30/compiler/not-enabled-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.30/compiler/not-enabled-01.vert fail 1.30"
run_test "spec/ARB_explicit_attrib_location/1.30/compiler/not-enabled-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.30/compiler/not-enabled-02.vert fail 1.30 GL_ARB_shading_language_420pack"
run_test "spec/ARB_explicit_attrib_location/1.30/preprocessor/define-130.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.30/preprocessor/define-130.frag pass 1.30 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.30/preprocessor/define-130.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.30/preprocessor/define-130.vert pass 1.30 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-01" 0.0 "bin/glsl-explicit-location-01 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-02" 0.0 "bin/glsl-explicit-location-02 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-03" 0.0 "bin/glsl-explicit-location-03 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-04" 0.0 "bin/glsl-explicit-location-04 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-05" 0.0 "bin/glsl-explicit-location-05 -auto"
run_test "spec/ARB_fragment_coord_conventions/compiler/basic-qualifiers-both-origin-and-pixel.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/basic-qualifiers-both-origin-and-pixel.frag pass 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/basic-qualifiers-layout-illegal-01-PointCoord.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/basic-qualifiers-layout-illegal-01-PointCoord.frag fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/basic-qualifiers-layout-illegal-02-FrontFacing.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/basic-qualifiers-layout-illegal-02-FrontFacing.frag fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/basic-qualifiers-nothing.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/basic-qualifiers-nothing.frag pass 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/basic-qualifiers-origin.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/basic-qualifiers-origin.frag pass 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/basic-qualifiers-pixel-center.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/basic-qualifiers-pixel-center.frag pass 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/redeclaration-after-use.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/redeclaration-after-use.frag fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/redeclaration-outside-fs.vert" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/redeclaration-outside-fs.vert fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/redeclaration-qualifier-applied-to-uniform.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/redeclaration-qualifier-applied-to-uniform.frag fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/redeclaration-qualifier-applied-to-vertex-input.vert" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/redeclaration-qualifier-applied-to-vertex-input.vert fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/compiler/redeclaration-user-defined-varying.frag" 0.0 "bin/glslparsertest tests/spec/arb_fragment_coord_conventions/compiler/redeclaration-user-defined-varying.frag fail 1.10 GL_ARB_fragment_coord_conventions"
run_test "spec/ARB_fragment_coord_conventions/fp-arb-fragment-coord-conventions-integer" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-arb-fragment-coord-conventions-integer.vpfp -fbo -auto"
run_test "spec/ARB_fragment_coord_conventions/fp-arb-fragment-coord-conventions-none" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-arb-fragment-coord-conventions-none.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/dph" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/dph.shader_test -auto"
run_test "spec/ARB_fragment_program/fdo30337a" 0.0 "bin/vpfp-generic tests/shaders/generic/fdo30337a.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fdo30337b" 0.0 "bin/vpfp-generic tests/shaders/generic/fdo30337b.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fdo38145" 0.0 "bin/vpfp-generic tests/shaders/generic/fdo38145.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fp-abs-01" 0.0 "bin/fp-abs-01 -auto"
run_test "spec/ARB_fragment_program/fp-cmp" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-cmp.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fp-dst-aliasing-1" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-dst-aliasing-1.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fp-dst-aliasing-2" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-dst-aliasing-2.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fp-ex2-sat" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-ex2-sat.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/fp-fog" 0.0 "bin/fp-fog -auto"
run_test "spec/ARB_fragment_program/fp-formats" 0.0 "bin/fp-formats -auto"
run_test "spec/ARB_fragment_program/fp-fragment-position" 0.0 "bin/fp-fragment-position -auto"
run_test "spec/ARB_fragment_program/fp-incomplete-tex" 0.0 "bin/fp-incomplete-tex -auto"
run_test "spec/ARB_fragment_program/fp-indirections" 0.0 "bin/fp-indirections -auto"
run_test "spec/ARB_fragment_program/fp-indirections2" 0.0 "bin/fp-indirections2 -auto"
run_test "spec/ARB_fragment_program/fp-kil" 0.0 "bin/fp-kil -auto"
run_test "spec/ARB_fragment_program/fp-lit-mask" 0.0 "bin/fp-lit-mask -auto"
run_test "spec/ARB_fragment_program/fp-lit-src-equals-dst" 0.0 "bin/fp-lit-src-equals-dst -auto"
run_test "spec/ARB_fragment_program/fp-long-alu" 0.0 "bin/fp-long-alu -auto"
run_test "spec/ARB_fragment_program/fp-set-01" 0.0 "bin/fp-set-01 -auto"
run_test "spec/ARB_fragment_program/fp-two-constants" 0.0 "bin/vpfp-generic tests/shaders/generic/fp-two-constants.vpfp -fbo -auto"
run_test "spec/ARB_fragment_program/incomplete-texture-arb_fp" 0.0 "bin/incomplete-texture -auto arb_fp -fbo -auto"
run_test "spec/ARB_fragment_program/kil-swizzle" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/kil-swizzle.shader_test -auto"
run_test "spec/ARB_fragment_program/lrp_sat" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/lrp_sat.shader_test -auto"
run_test "spec/ARB_fragment_program/minmax" 0.0 "bin/arb_fragment_program-minmax -fbo -auto"
run_test "spec/ARB_fragment_program/sparse-samplers" 0.0 "bin/arb_fragment_program-sparse-samplers -fbo -auto"
run_test "spec/ARB_fragment_program/texturing/tex-2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/texturing/tex-2d.shader_test -auto"
run_test "spec/ARB_fragment_program/texturing/txb-2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/texturing/txb-2d.shader_test -auto"
run_test "spec/ARB_fragment_program/texturing/txp-2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/texturing/txp-2d.shader_test -auto"
run_test "spec/ARB_fragment_program/trinity-fp1" 0.0 "bin/trinity-fp1 -auto"
run_test "spec/ARB_fragment_program_shadow/masked" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/masked.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/tex-shadow1d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/tex-shadow1d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/tex-shadow2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/tex-shadow2d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/tex-shadow2drect" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/tex-shadow2drect.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/txp-shadow1d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/txp-shadow1d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/txp-shadow2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/txp-shadow2d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/txp-shadow2drect" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/txp-shadow2drect.shader_test -auto"
run_test "spec/ARB_framebuffer_object/FBO blit from missing attachment" 0.0 "bin/fbo-missing-attachment-blit from -fbo -auto"
run_test "spec/ARB_framebuffer_object/FBO blit to missing attachment" 0.0 "bin/fbo-missing-attachment-blit to -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-alpha" 0.0 "bin/fbo-alpha -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-deriv" 0.0 "bin/fbo-deriv -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none glBlendFunci" 0.0 "bin/fbo-drawbuffers-none glBlendFunci -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none glBlitFramebuffer" 0.0 "bin/fbo-drawbuffers-none glBlitFramebuffer -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none glClear" 0.0 "bin/fbo-drawbuffers-none glClear -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none glClearBuffer" 0.0 "bin/fbo-drawbuffers-none glClearBuffer -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none glColorMaskIndexed" 0.0 "bin/fbo-drawbuffers-none glColorMaskIndexed -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none glDrawPixels" 0.0 "bin/fbo-drawbuffers-none glDrawPixels -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none gl_FragColor" 0.0 "bin/fbo-drawbuffers-none gl_FragColor -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none gl_FragData" 0.0 "bin/fbo-drawbuffers-none gl_FragData -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-drawbuffers-none use_frag_out" 0.0 "bin/fbo-drawbuffers-none use_frag_out -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-generatemipmap-1d" 0.0 "bin/fbo-generatemipmap-1d -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-generatemipmap-1d RGB9_E5" 0.0 "bin/fbo-generatemipmap-1d RGB9_E5 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-generatemipmap-3d" 0.0 "bin/fbo-generatemipmap-3d -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-generatemipmap-3d RGB9_E5" 0.0 "bin/fbo-generatemipmap-3d RGB9_E5 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-generatemipmap-cubemap" 0.0 "bin/fbo-generatemipmap-cubemap -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-generatemipmap-cubemap RGB9_E5" 0.0 "bin/fbo-generatemipmap-cubemap RGB9_E5 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-getframebufferattachmentparameter-01" 0.0 "bin/fbo-getframebufferattachmentparameter-01 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-gl_pointcoord" 0.0 "bin/fbo-gl_pointcoord -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete" 0.0 "bin/fbo-incomplete -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-invalid-texture" 0.0 "bin/fbo-incomplete-invalid-texture -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-01" 0.0 "bin/fbo-incomplete-texture-01 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-02" 0.0 "bin/fbo-incomplete-texture-02 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-03" 0.0 "bin/fbo-incomplete-texture-03 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-04" 0.0 "bin/fbo-incomplete-texture-04 -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-mipmap-copypix" 0.0 "bin/fbo-mipmap-copypix -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-scissor-blit fbo" 0.0 "bin/fbo-scissor-blit fbo -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-scissor-blit window" 0.0 "bin/fbo-scissor-blit window -auto"
run_test "spec/ARB_framebuffer_object/fbo-tex-rgbx" 0.0 "bin/fbo-tex-rgbx -fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-viewport" 0.0 "bin/fbo-viewport -auto"
run_test "spec/ARB_framebuffer_object/fdo28551" 0.0 "bin/fdo28551 -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels draw depth" 0.0 "bin/framebuffer-blit-levels draw depth -fbo -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels draw rgba" 0.0 "bin/framebuffer-blit-levels draw rgba -fbo -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels draw stencil" 0.0 "bin/framebuffer-blit-levels draw stencil -fbo -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels read depth" 0.0 "bin/framebuffer-blit-levels read depth -fbo -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels read rgba" 0.0 "bin/framebuffer-blit-levels read rgba -fbo -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels read stencil" 0.0 "bin/framebuffer-blit-levels read stencil -fbo -auto"
run_test "spec/ARB_framebuffer_object/same-attachment-glFramebufferRenderbuffer-GL_DEPTH_STENCIL_ATTACHMENT" 0.0 "bin/same-attachment-glFramebufferRenderbuffer-GL_DEPTH_STENCIL_ATTACHMENT -fbo -auto"
run_test "spec/ARB_framebuffer_object/same-attachment-glFramebufferTexture2D-GL_DEPTH_STENCIL_ATTACHMENT" 0.0 "bin/same-attachment-glFramebufferTexture2D-GL_DEPTH_STENCIL_ATTACHMENT -fbo -auto"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear downsample disabled -fbo -auto"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear downsample enabled -fbo -auto"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear msaa disabled -fbo -auto"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear msaa enabled -fbo -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 283 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

