#!/bin/bash


need_pass=426
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec2-ivec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec2-ivec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec3-ivec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec3-ivec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec4-ivec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-ivec4-ivec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat2-mat2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat2-mat2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat3-mat3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat3-mat3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat4-mat4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-mat4-mat4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec2-vec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec2-vec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec3-vec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec3-vec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec4-vec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-ne-vec4-vec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-neg-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-neg-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-not-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-not-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-not-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-not-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-or-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-or-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-or-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-or-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-selection-bool-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-sub-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-uplus-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-xor-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-xor-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-op-xor-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-op-xor-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-pow-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-pow-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-pow-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-pow-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-pow-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-pow-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-pow-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-pow-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-radians-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-radians-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-radians-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-radians-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-radians-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-radians-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-radians-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-radians-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-reflect-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-reflect-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-reflect-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-reflect-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-reflect-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-reflect-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-reflect-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-reflect-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-refract-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-refract-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-refract-vec2-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-refract-vec2-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-refract-vec3-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-refract-vec3-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-refract-vec4-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-refract-vec4-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sign-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sign-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sign-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sign-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sign-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sign-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sign-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sign-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sin-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sin-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sin-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sin-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sin-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sin-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sin-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sin-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-float-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-vec2-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-vec2-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-vec3-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-vec3-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-vec4-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-smoothstep-vec4-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sqrt-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sqrt-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sqrt-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sqrt-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sqrt-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sqrt-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-sqrt-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-sqrt-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-step-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-step-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-tan-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-tan-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-tan-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-tan-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-tan-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-tan-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/vs-tan-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/vs-tan-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/clipping/clip-plane-transformation clipvert_pos" 0.0 "bin/clip-plane-transformation clipvert_pos -auto -fbo"
run_test "spec/glsl-1.10/execution/clipping/clip-plane-transformation fixed" 0.0 "bin/clip-plane-transformation fixed -auto -fbo"
run_test "spec/glsl-1.10/execution/clipping/clip-plane-transformation pos_clipvert" 0.0 "bin/clip-plane-transformation pos_clipvert -auto -fbo"
run_test "spec/glsl-1.10/execution/fs-bool-less-compare-false" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-bool-less-compare-false.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-bool-less-compare-true" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-bool-less-compare-true.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-inline-notequal" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-inline-notequal.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-loop-bounds-unrolled" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-loop-bounds-unrolled.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-saturate-exp2" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-saturate-exp2.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-saturate-pow" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-saturate-pow.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-saturate-sqrt" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-saturate-sqrt.shader_test -auto"
run_test "spec/glsl-1.10/execution/fs-vector-indexing-kills-all-channels" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/fs-vector-indexing-kills-all-channels.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-flat-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-flat-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-flat-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-smooth-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-smooth-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-smooth-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-flat-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-flat-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-flat-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-smooth-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-smooth-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-smooth-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-other-flat-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-other-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-other-flat-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-other-flat-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-other-flat-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-other-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-other-smooth-fixed" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-other-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-other-smooth-none" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-other-smooth-none.shader_test -auto"
run_test "spec/glsl-1.10/execution/interpolation/interpolation-none-other-smooth-vertex" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/interpolation/interpolation-none-other-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxClipPlanes" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxClipPlanes.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxCombinedTextureImageUnits" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxCombinedTextureImageUnits.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxDrawBuffers" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxDrawBuffers.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxFragmentUniformComponents" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxFragmentUniformComponents.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxLights" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxLights.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxTextureCoords" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxTextureCoords.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxTextureImageUnits" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxTextureImageUnits.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxTextureUnits" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxTextureUnits.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxVaryingFloats" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxVaryingFloats.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxVertexAttribs" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxVertexAttribs.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxVertexTextureImageUnits" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxVertexTextureImageUnits.shader_test -auto"
run_test "spec/glsl-1.10/execution/maximums/gl_MaxVertexUniformComponents" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/maximums/gl_MaxVertexUniformComponents.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-01" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-01.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-02" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-02.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-03" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-03.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-04" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-04.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-05" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-05.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-06" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-06.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-07" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-07.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-08" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-08.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-09" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-09.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-bias" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1D-bias.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1DProj" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1DProj.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow1DProj-bias" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow1DProj-bias.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-01" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-01.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-02" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-02.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-03" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-03.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-04" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-04.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-05" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-05.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-06" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-06.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-07" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-07.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-08" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-08.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-09" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-09.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-bias" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-bias.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-clamp-z" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2D-clamp-z.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2DProj" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2DProj.shader_test -auto"
run_test "spec/glsl-1.10/execution/samplers/glsl-fs-shadow2DProj-bias" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/samplers/glsl-fs-shadow2DProj-bias.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-index-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat2-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-index-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat3-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-index-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-array-mat4-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat2-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat3-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-temp-mat4-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-array-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-uniform-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-array-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/fs-varying-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-index-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat2-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-index-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat3-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-index-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-array-mat4-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat2-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-row-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-col-wr.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-row-rd" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-row-rd.shader_test -auto"
run_test "spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-row-wr" 0.0 "bin/shader_runner tests/spec/glsl-1.10/execution/variable-indexing/vs-temp-mat3-row-wr.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 426 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

