#!/bin/bash


need_pass=448
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitor-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-int-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec2-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec3-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-ivec4-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uint-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-bitxor-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-complement-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-large-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-large-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-large-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-large-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uint-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-div-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-eq-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ge-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ge-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ge-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ge-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-gt-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-gt-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-gt-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-gt-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-le-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-le-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-le-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-le-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-int-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-ivec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lshift-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lt-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lt-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-lt-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-lt-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-int-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec2-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec3-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-ivec4-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uint-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mod-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uint-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-mult-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-ne-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-neg-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-int-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-ivec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-rshift-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-selection-bool-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uint-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec2-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec3-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-sub-uvec4-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uint.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uint.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uint.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uint.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/op-uplus-uvec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-float.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-float.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-float.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-float.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-vec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-vec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-vec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-vec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-vec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-vec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-vec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-vec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-vec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-vec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/round-vec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/round-vec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-float.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-float.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-float.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-float.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-vec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-vec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-vec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-vec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-vec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-vec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-vec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-vec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-vec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-vec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/roundEven-vec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/roundEven-vec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-int.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-int.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-int.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-ivec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-ivec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-ivec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-ivec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-ivec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-ivec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-ivec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-ivec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-ivec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-ivec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sign-ivec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sign-ivec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-float.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-float.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-float.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-float.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-vec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-vec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-vec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-vec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-vec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-vec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-vec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-vec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-vec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-vec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/sinh-vec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/sinh-vec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-float.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-float.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-float.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-float.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-vec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-vec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-vec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-vec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-vec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-vec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-vec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-vec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-vec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-vec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/tanh-vec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/tanh-vec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-float.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-float.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-float.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-float.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-vec2.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-vec2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-vec2.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-vec2.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-vec3.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-vec3.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-vec3.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-vec3.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-vec4.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-vec4.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/built-in-functions/trunc-vec4.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.30/compiler/built-in-functions/trunc-vec4.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-3.frag fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-3.vert fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-max.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-max.frag fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-max.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-access-max.vert fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large-with-access.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large-with-access.frag fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large-with-access.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large-with-access.vert fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large.frag fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-explicit-too-large.vert fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-implicit-access-max.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-implicit-access-max.frag fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-implicit-access-max.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-implicit-access-max.vert fail 1.30 --check-link"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-implicit-length.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-implicit-length.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/clipping/clip-distance-implicit-nonconst-access.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/clipping/clip-distance-implicit-nonconst-access.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/constant-expressions/sampler-array-index-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/constant-expressions/sampler-array-index-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/constant-expressions/sampler-array-index-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/constant-expressions/sampler-array-index-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/constant-expressions/sampler-array-index-03.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/constant-expressions/sampler-array-index-03.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/constant-expressions/uint-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/constant-expressions/uint-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-function-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-function-output.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-not-user-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-not-user-output.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-user-output-dead.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-user-output-dead.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-user-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-and-user-output.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-dead-and-user-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragColor-dead-and-user-output.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-and-function-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-and-function-output.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-and-user-output-dead.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-and-user-output-dead.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-and-user-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-and-user-output.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-dead-and-user-output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/fragment-outputs/write-gl_FragData-dead-and-user-output.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/fs-color-interpolation-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/fs-color-interpolation-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/fs-secondarycolor-interpolation-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/fs-secondarycolor-interpolation-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/fs-smooth-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/fs-smooth-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/fs-smooth-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/fs-smooth-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/local-smooth-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/local-smooth-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/smooth-varying-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/smooth-varying-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/smooth-varying-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/smooth-varying-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-backcolor-interpolation-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-backcolor-interpolation-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-backsecondarycolor-interpolation-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-backsecondarycolor-interpolation-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-flat-int-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-flat-int-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-frontcolor-interpolation-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-frontcolor-interpolation-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-frontsecondarycolor-interpolation-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-frontsecondarycolor-interpolation-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-smooth-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-smooth-01.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/interpolation-qualifiers/vs-smooth-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/interpolation-qualifiers/vs-smooth-02.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/keywords/attribute.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/attribute.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/bool.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/bool.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/break.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/break.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/bvec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/bvec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/bvec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/bvec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/bvec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/bvec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/case.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/case.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/centroid.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/centroid.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/const.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/const.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/continue.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/continue.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/default.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/default.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/discard.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/discard.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/do.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/do.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/else.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/else.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/false.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/false.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/flat.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/flat.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/float.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/float.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/for.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/for.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/highp.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/highp.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/if.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/if.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/in.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/in.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/inout.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/inout.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/int.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/int.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/invariant.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/invariant.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/isampler1D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/isampler1D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/isampler1DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/isampler1DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/isampler2D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/isampler2D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/isampler2DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/isampler2DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/isampler3D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/isampler3D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/isamplerCube.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/isamplerCube.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/ivec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/ivec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/ivec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/ivec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/ivec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/ivec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/lowp.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/lowp.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat2.frag fail 1.30"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 448 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

