#!/bin/bash


need_pass=441
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.30/compiler/keywords/ivec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/ivec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/ivec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/ivec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/lowp.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/lowp.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat2x2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat2x2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat2x3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat2x3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat2x4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat2x4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat3x2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat3x2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat3x3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat3x3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat3x4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat3x4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat4x2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat4x2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat4x3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat4x3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mat4x4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mat4x4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/mediump.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/mediump.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/noperspective.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/noperspective.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/out.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/out.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/precision.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/precision.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/return.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/return.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler1D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler1D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler1DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler1DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler1DArrayShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler1DArrayShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler1DShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler1DShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler2D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler2D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler2DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler2DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler2DArrayShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler2DArrayShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler2DShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler2DShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/sampler3D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/sampler3D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/samplerCube.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/samplerCube.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/samplerCubeShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/samplerCubeShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/smooth.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/smooth.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/struct.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/switch.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/switch.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/true.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/true.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/uint.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/uint.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/uniform.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/uniform.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/usampler1D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/usampler1D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/usampler1DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/usampler1DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/usampler2D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/usampler2D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/usampler2DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/usampler2DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/usampler3D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/usampler3D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/usamplerCube.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/usamplerCube.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/uvec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/uvec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/uvec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/uvec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/uvec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/uvec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/varying.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/varying.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/vec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/vec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/vec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/vec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/vec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/vec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/void.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/void.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/keywords/while.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/keywords/while.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-02.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-03.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-03.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-04.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-04.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-05.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-05.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-06.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-06.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-07.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/order-of-qualification/order-of-qualification-07.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/default-precision-bool-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/default-precision-bool-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/default-precision-float-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/default-precision-float-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/default-precision-int-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/default-precision-int-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/default-precision-vec-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/default-precision-vec-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-bool-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-bool-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-bool-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-bool-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-float-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-float-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-float-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-float-02.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-float-03.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-float-03.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-float-04.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-float-04.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-function-param-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-function-param-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-global-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-global-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-int-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-int-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-int-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-int-02.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-int-03.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-int-03.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-literal-const-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-literal-const-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-literal-const-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-literal-const-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-local-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-local-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-struct-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-struct-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-struct-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-struct-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-uint-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-uint-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-uint-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-uint-02.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/precision-qualifiers/precision-uint-03.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/precision-qualifiers/precision-uint-03.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/centroid-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/centroid-01.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-02.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-bool-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-bool-prohibited.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-bvec2-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-bvec2-prohibited.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-bvec3-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-bvec3-prohibited.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-bvec4-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-bvec4-prohibited.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/in-struct-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/in-struct-prohibited.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/inout-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/inout-01.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/invariant-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/invariant-01.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-02.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-bool-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-bool-prohibited.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-bvec2-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-bvec2-prohibited.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-bvec3-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-bvec3-prohibited.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-bvec4-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-bvec4-prohibited.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-conversion-ambiguous.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-conversion-ambiguous.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/qualifiers/out-struct-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/qualifiers/out-struct-prohibited.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/active.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/active.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/asm.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/asm.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/cast.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/cast.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/class.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/class.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/common.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/common.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/double.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/double.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/dvec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/dvec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/dvec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/dvec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/dvec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/dvec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/enum.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/enum.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/extern.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/extern.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/external.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/external.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/filter.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/filter.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/fixed.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/fixed.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/fvec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/fvec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/fvec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/fvec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/fvec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/fvec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/goto.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/goto.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/half.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/half.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/hvec2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/hvec2.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/hvec3.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/hvec3.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/hvec4.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/hvec4.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimage1D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimage1D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimage1DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimage1DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimage2D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimage2D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimage2DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimage2DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimage3D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimage3D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimageBuffer.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimageBuffer.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/iimageCube.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/iimageCube.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image1D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image1D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image1DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image1DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image1DArrayShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image1DArrayShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image1DShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image1DShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image2D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image2D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image2DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image2DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image2DArrayShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image2DArrayShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image2DShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image2DShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/image3D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/image3D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/imageBuffer.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/imageBuffer.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/imageCube.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/imageCube.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/inline.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/inline.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/input.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/input.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/interface.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/interface.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/long.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/long.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/namespace.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/namespace.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/noinline.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/noinline.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/output.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/output.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/packed.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/packed.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/partition.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/partition.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/public.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/public.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/row_major.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/row_major.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/sampler2DRect.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/sampler2DRect.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/sampler2DRectShadow.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/sampler2DRectShadow.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/sampler3DRect.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/sampler3DRect.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/samplerBuffer.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/samplerBuffer.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/short.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/short.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/sizeof.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/sizeof.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/static.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/static.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/superp.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/superp.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/template.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/template.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/this.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/this.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/typedef.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/typedef.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimage1D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimage1D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimage1DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimage1DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimage2D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimage2D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimage2DArray.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimage2DArray.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimage3D.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimage3D.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimageBuffer.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimageBuffer.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/uimageCube.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/uimageCube.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/union.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/union.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/unsigned.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/unsigned.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/using.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/using.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/reserved/volatile.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/reserved/volatile.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/fs-centroid-in-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/fs-centroid-in-01.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/fs-inout-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/fs-inout-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/function-param-centroid-in-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/function-param-centroid-in-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/local-centroid-in-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/local-centroid-in-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/local-in-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/local-in-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/local-out-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/local-out-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-centroid-in-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-centroid-in-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-clip-distance.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-clip-distance.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-01.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-02.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-direct.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-direct.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-indirect.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-in-indirect.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/static-write-vertex-id.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/static-write-vertex-id.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/vs-centroid-in-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/vs-centroid-in-01.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/storage-qualifiers/vs-inout-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/storage-qualifiers/vs-inout-01.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/structure-and-array-operations/array-index-as-uint-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/structure-and-array-operations/array-index-as-uint-01.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-const-int-expression.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-const-int-expression.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-const-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-const-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-duplicated.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-duplicated.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-empty-end.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-empty-end.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-fallthrough.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-fallthrough.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-in-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-in-int.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-statement.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-statement.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-case-uniform-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-case-uniform-int.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-default-duplicated.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-default-duplicated.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-default.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-default.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-const-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-const-float.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-const-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-const-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-const-ivec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-const-ivec2.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-const-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-const-vec2.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-in-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-in-float.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-in-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-in-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-in-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-in-vec2.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-uniform-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-uniform-float.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-uniform-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-uniform-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-uniform-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-uniform-vec2.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-var-float.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-var-float.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-var-int.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-var-int.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-expression-var-vec2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-expression-var-vec2.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-nested-break.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-nested-break.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-nested-case.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-nested-case.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-nested-default.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-nested-default.vert fail 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-nested-loop.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-nested-loop.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/switch-statement/switch-nested-switch.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/switch-statement/switch-nested-switch.vert pass 1.30"
run_test "spec/glsl-1.30/compiler/texture/texelFetch.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/texture/texelFetch.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/texture/texelFetchOffset.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/texture/texelFetchOffset.frag fail 1.30"
run_test "spec/glsl-1.30/compiler/texture/texelFetchOffset2.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/texture/texelFetchOffset2.frag pass 1.30"
run_test "spec/glsl-1.30/compiler/texture/textureSize.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.30/compiler/texture/textureSize.frag pass 1.30"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-abs-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-abs-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-abs-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-abs-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-abs-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-abs-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-abs-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-abs-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-acosh-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-acosh-float.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-acosh-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-acosh-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-acosh-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-acosh-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-acosh-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-acosh-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-asinh-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-asinh-float.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-asinh-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-asinh-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-asinh-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-asinh-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-asinh-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-asinh-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-atanh-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-atanh-float.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-atanh-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-atanh-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-atanh-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-atanh-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-atanh-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-atanh-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-int-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-int-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec2-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec2-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec2-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec2-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec3-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec3-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec3-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec3-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec4-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec4-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec4-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-ivec4-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uint-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uint-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec2-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec2-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec2-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec2-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec3-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec3-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec3-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec3-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec4-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec4-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec4-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-clamp-uvec4-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-cosh-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-cosh-float.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-cosh-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-cosh-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-cosh-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-cosh-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-cosh-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-cosh-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-equal-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-equal-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-equal-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-equal-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-equal-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-equal-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-greaterThan-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-greaterThan-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-greaterThan-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-greaterThan-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-greaterThan-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-greaterThan-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-greaterThanEqual-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-greaterThanEqual-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-greaterThanEqual-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-greaterThanEqual-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-greaterThanEqual-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-greaterThanEqual-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-lessThan-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-lessThan-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-lessThan-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-lessThan-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-lessThan-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-lessThan-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-lessThanEqual-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-lessThanEqual-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-lessThanEqual-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-lessThanEqual-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-lessThanEqual-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-lessThanEqual-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-max-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-max-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-min-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-min-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-mix-float-float-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-mix-float-float-bool.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-mix-vec2-vec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-mix-vec2-vec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-mix-vec3-vec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-mix-vec3-vec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-mix-vec4-vec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-mix-vec4-vec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-notEqual-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-notEqual-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-notEqual-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-notEqual-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-notEqual-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-notEqual-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uint-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-add-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uint-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitand-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uint-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitor-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uint-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-bitxor-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-complement-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-large-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-large-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uint-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-div-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uint-uint-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uint-uint-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec2-uvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec2-uvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec3-uvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec3-uvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec4-uvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-eq-uvec4-uvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-ge-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-ge-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-ge-uint-uint-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-ge-uint-uint-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-gt-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-gt-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-gt-uint-uint-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-gt-uint-uint-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-le-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-le-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-le-uint-uint-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-le-uint-uint-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-int-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-int-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-ivec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uint-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uint-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-uvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec2-uvec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-uvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec3-uvec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-uvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lshift-uvec4-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lt-uint-uint" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lt-uint-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-lt-uint-uint-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-lt-uint-uint-using-if.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-mod-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-mod-int-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-mod-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-mod-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/fs-op-mod-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.30/execution/built-in-functions/fs-op-mod-int-ivec3.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 441 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

