#!/bin/bash


need_pass=335
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/ARB_texture_rg/fbo-rg-GL_RED" 0.0 "bin/fbo-rg -auto GL_RED"
run_test "spec/ARB_texture_rg/fbo-rg-GL_RG" 0.0 "bin/fbo-rg -auto GL_RG"
run_test "spec/ARB_texture_rg/fbo-rg-GL_RG16" 0.0 "bin/fbo-rg -auto GL_RG16"
run_test "spec/ARB_texture_rg/fbo-rg-GL_RG8" 0.0 "bin/fbo-rg -auto GL_RG8"
run_test "spec/ARB_texture_rg/fs-shadow2d-red-01" 0.0 "bin/shader_runner tests/spec/arb_texture_rg/execution/fs-shadow2d-red-01.shader_test -auto"
run_test "spec/ARB_texture_rg/fs-shadow2d-red-02" 0.0 "bin/shader_runner tests/spec/arb_texture_rg/execution/fs-shadow2d-red-02.shader_test -auto"
run_test "spec/ARB_texture_rg/fs-shadow2d-red-03" 0.0 "bin/shader_runner tests/spec/arb_texture_rg/execution/fs-shadow2d-red-03.shader_test -auto"
run_test "spec/ARB_texture_rg/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_ARB_texture_rg -auto -fbo"
run_test "spec/ARB_texture_rg/get-renderbuffer-internalformat-float" 0.0 "bin/get-renderbuffer-internalformat GL_ARB_texture_rg-float -auto -fbo"
run_test "spec/ARB_texture_rg/multisample-formats 2 GL_ARB_texture_rg" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_ARB_texture_rg"
run_test "spec/ARB_texture_rg/multisample-formats 2 GL_ARB_texture_rg-float" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_ARB_texture_rg-float"
run_test "spec/ARB_texture_rg/multisample-formats 2 GL_ARB_texture_rg-int" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_ARB_texture_rg-int"
run_test "spec/ARB_texture_rg/multisample-formats 4 GL_ARB_texture_rg-float" 0.0 "bin/ext_framebuffer_multisample-formats -auto 4 GL_ARB_texture_rg-float"
run_test "spec/ARB_texture_rg/multisample-formats 4 GL_ARB_texture_rg-int" 0.0 "bin/ext_framebuffer_multisample-formats -auto 4 GL_ARB_texture_rg-int"
run_test "spec/ARB_texture_rg/rg-draw-pixels" 0.0 "bin/rg-draw-pixels -auto"
run_test "spec/ARB_texture_rg/rg-teximage-01" 0.0 "bin/rg-teximage-01 -auto"
run_test "spec/ARB_texture_rg/rg-teximage-02" 0.0 "bin/rg-teximage-02 -auto"
run_test "spec/ARB_texture_rg/texture-rg" 0.0 "bin/texture-rg -auto"
run_test "spec/ARB_texture_rg/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg"
run_test "spec/ARB_texture_rg/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg bordercolor"
run_test "spec/ARB_texture_rg/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg bordercolor swizzled"
run_test "spec/ARB_texture_rg/texwrap formats-float" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg-float"
run_test "spec/ARB_texture_rg/texwrap formats-float bordercolor" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg-float bordercolor"
run_test "spec/ARB_texture_rg/texwrap formats-float bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg-float bordercolor swizzled"
run_test "spec/ARB_texture_rg/texwrap formats-int" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rg-int"
run_test "spec/ARB_texture_rgb10_a2ui/fbo-blending" 0.0 "bin/ext_texture_integer-fbo-blending GL_ARB_texture_rgb10_a2ui -auto -fbo"
run_test "spec/ARB_texture_rgb10_a2ui/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_rgb10_a2ui"
run_test "spec/ARB_texture_storage/texture-storage" 0.0 "bin/arb_texture_storage-texture-storage -auto"
run_test "spec/ARB_timer_query/query GL_TIMESTAMP" 0.0 "bin/ext_timer_query-time-elapsed timestamp -auto -fbo"
run_test "spec/ARB_timer_query/query-lifetime" 0.0 "bin/ext_timer_query-lifetime -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/bindbuffer-general-point" 0.0 "bin/arb_uniform_buffer_object-bindbuffer-general-point -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/buffer-targets" 0.0 "bin/arb_uniform_buffer_object-buffer-targets -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/compiler/block-name-clashes-with-function.vert" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/block-name-clashes-with-function.vert fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/block-name-clashes-with-struct.vert" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/block-name-clashes-with-struct.vert fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/block-name-clashes-with-variable.vert" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/block-name-clashes-with-variable.vert fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/extension-disabled-column-major.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/extension-disabled-column-major.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/extension-disabled-row-major.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/extension-disabled-row-major.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/extension-disabled-std140.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/extension-disabled-std140.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/extension-disabled-uniform-block.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/extension-disabled-uniform-block.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-column_major-non-uniform.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-column_major-non-uniform.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-packed-non-uniform.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-packed-non-uniform.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-packed-within-block.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-packed-within-block.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-row_major-non-uniform.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-row_major-non-uniform.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-row_major-struct.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-row_major-struct.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-shared-non-uniform.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-shared-non-uniform.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-shared-within-block.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-shared-within-block.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-std140-non-uniform.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-std140-non-uniform.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/layout-std140-within-block.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/layout-std140-within-block.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/uniform-block-initializer.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/uniform-block-initializer.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/uniform-block-nested.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/uniform-block-nested.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/compiler/uniform-block-sampler.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/compiler/uniform-block-sampler.frag fail 1.20 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/deletebuffers" 0.0 "bin/arb_uniform_buffer_object-deletebuffers -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getactiveuniformblockname" 0.0 "bin/arb_uniform_buffer_object-getactiveuniformblockname -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getactiveuniformname" 0.0 "bin/arb_uniform_buffer_object-getactiveuniformname -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getactiveuniformsiv-uniform-block-index" 0.0 "bin/arb_uniform_buffer_object-getactiveuniformsiv-uniform-block-index -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getprogramiv" 0.0 "bin/arb_uniform_buffer_object-getprogramiv -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getuniformblockindex" 0.0 "bin/arb_uniform_buffer_object-getuniformblockindex -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getuniformindices" 0.0 "bin/arb_uniform_buffer_object-getuniformindices -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/getuniformlocation" 0.0 "bin/arb_uniform_buffer_object-getuniformlocation -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/link-mismatch-blocks" 0.0 "bin/arb_uniform_buffer_object-link-mismatch-blocks -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/maxblocks" 0.0 "bin/arb_uniform_buffer_object-maxblocks -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/maxuniformblocksize/vs" 0.0 "bin/arb_uniform_buffer_object-maxuniformblocksize vs -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/maxuniformblocksize/vsexceed" 0.0 "bin/arb_uniform_buffer_object-maxuniformblocksize vsexceed -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/minmax" 0.0 "bin/arb_uniform_buffer_object-minmax -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/negative-bindbuffer-index" 0.0 "bin/arb_uniform_buffer_object-negative-bindbuffer-index -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/negative-bindbuffer-target" 0.0 "bin/arb_uniform_buffer_object-negative-bindbuffer-target -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/negative-getactiveuniformblockiv" 0.0 "bin/arb_uniform_buffer_object-negative-getactiveuniformblockiv -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/negative-getactiveuniformsiv" 0.0 "bin/arb_uniform_buffer_object-negative-getactiveuniformsiv -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/preprocessor/define.frag" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/preprocessor/define.frag pass 1.10 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/preprocessor/define.vert" 0.0 "bin/glslparsertest tests/spec/arb_uniform_buffer_object/preprocessor/define.vert pass 1.10 GL_ARB_uniform_buffer_object"
run_test "spec/ARB_uniform_buffer_object/referenced-by-shader" 0.0 "bin/arb_uniform_buffer_object-referenced-by-shader -auto -fbo"
run_test "spec/ARB_uniform_buffer_object/uniformblockbinding" 0.0 "bin/arb_uniform_buffer_object-uniformblockbinding -auto -fbo"
run_test "spec/ARB_vertex_array_object/isvertexarray" 0.0 "bin/arb_vertex_array-isvertexarray -auto -fbo"
run_test "spec/ARB_vertex_array_object/vao-element-array-buffer" 0.0 "bin/vao-element-array-buffer -auto -fbo"
run_test "spec/ARB_vertex_buffer_object/elements-negative-offset" 0.0 "bin/arb_vertex_buffer_object-elements-negative-offset -auto"
run_test "spec/ARB_vertex_buffer_object/fdo14575" 0.0 "bin/fdo14575 -auto"
run_test "spec/ARB_vertex_buffer_object/fdo22540" 0.0 "bin/fdo22540 -auto"
run_test "spec/ARB_vertex_buffer_object/fdo31934" 0.0 "bin/fdo31934 -auto"
run_test "spec/ARB_vertex_buffer_object/mixed-immediate-and-vbo" 0.0 "bin/arb_vertex_buffer_object-mixed-immediate-and-vbo -auto"
run_test "spec/ARB_vertex_buffer_object/pos-array" 0.0 "bin/pos-array -auto"
run_test "spec/ARB_vertex_buffer_object/vbo-bufferdata" 0.0 "bin/vbo-bufferdata -auto"
run_test "spec/ARB_vertex_buffer_object/vbo-map-remap" 0.0 "bin/vbo-map-remap -auto"
run_test "spec/ARB_vertex_buffer_object/vbo-map-unsync" 0.0 "bin/vbo-map-unsync -auto -fbo"
run_test "spec/ARB_vertex_buffer_object/vbo-subdata-sync" 0.0 "bin/vbo-subdata-sync -auto"
run_test "spec/ARB_vertex_buffer_object/vbo-subdata-zero" 0.0 "bin/vbo-subdata-zero -auto"
run_test "spec/ARB_vertex_program/arl" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/arl.vpfp"
run_test "spec/ARB_vertex_program/big-param" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/big-param.vpfp"
run_test "spec/ARB_vertex_program/clip-plane-transformation arb" 0.0 "bin/clip-plane-transformation arb -auto -fbo"
run_test "spec/ARB_vertex_program/dataflow-bug" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/dataflow-bug.vpfp"
run_test "spec/ARB_vertex_program/fdo24066" 0.0 "bin/fdo24066 -auto"
run_test "spec/ARB_vertex_program/fogcoord-dp3" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fogcoord-dp3.vpfp"
run_test "spec/ARB_vertex_program/fogcoord-dp4" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fogcoord-dp4.vpfp"
run_test "spec/ARB_vertex_program/fogcoord-dph" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fogcoord-dph.vpfp"
run_test "spec/ARB_vertex_program/getenv4d-with-error" 0.0 "bin/arb_vertex_program-getenv4d-with-error -auto"
run_test "spec/ARB_vertex_program/getlocal4d-with-error" 0.0 "bin/arb_vertex_program-getlocal4d-with-error -auto"
run_test "spec/ARB_vertex_program/minmax" 0.0 "bin/arb_vertex_program-minmax -auto -fbo"
run_test "spec/ARB_vertex_program/vp-address-01" 0.0 "bin/vp-address-01 -auto"
run_test "spec/ARB_vertex_program/vp-arl-constant-array" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-huge" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-huge.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-huge-offset" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-huge-offset.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-huge-offset-neg" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-huge-offset-neg.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-huge-overwritten" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-huge-overwritten.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-huge-relative-offset" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-huge-relative-offset.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-huge-varying" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-huge-varying.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-constant-array-varying" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-constant-array-varying.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-env-array" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-env-array.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-local-array" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-local-array.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-neg-array" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-neg-array.vpfp"
run_test "spec/ARB_vertex_program/vp-arl-neg-array-2" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-arl-neg-array-2.vpfp"
run_test "spec/ARB_vertex_program/vp-bad-program" 0.0 "bin/vp-bad-program -auto"
run_test "spec/ARB_vertex_program/vp-constant-array" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-constant-array.vpfp"
run_test "spec/ARB_vertex_program/vp-constant-array-huge" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-constant-array-huge.vpfp"
run_test "spec/ARB_vertex_program/vp-constant-negate" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-constant-negate.vpfp"
run_test "spec/ARB_vertex_program/vp-exp-alias" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-exp-alias.vpfp"
run_test "spec/ARB_vertex_program/vp-max" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-max.vpfp"
run_test "spec/ARB_vertex_program/vp-max-array" 0.0 "bin/vp-max-array -auto"
run_test "spec/ARB_vertex_program/vp-min" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-min.vpfp"
run_test "spec/ARB_vertex_program/vp-sge-alias" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-sge-alias.vpfp"
run_test "spec/ARB_vertex_program/vp-two-constants" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/vp-two-constants.vpfp"
run_test "spec/ARB_vertex_type_2_10_10_10_rev/attribs" 0.0 "bin/attribs GL_ARB_vertex_type_2_10_10_10_rev -auto -fbo"
run_test "spec/ATI_draw_buffers/arbfp-no-index" 0.0 "bin/ati_draw_buffers-arbfp-no-index -auto"
run_test "spec/ATI_draw_buffers/arbfp-no-option" 0.0 "bin/ati_draw_buffers-arbfp-no-option -auto"
run_test "spec/ATI_draw_buffers/ati_draw_buffers-arbfp" 0.0 "bin/ati_draw_buffers-arbfp -auto"
run_test "spec/ATI_envmap_bumpmap/ati_envmap_bumpmap-bump" 0.0 "bin/ati_envmap_bumpmap-bump -auto"
run_test "spec/ATI_texture_compression_3dc/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats 3dc"
run_test "spec/EXT_draw_buffers2/fbo-drawbuffers2-blend" 0.0 "bin/fbo-drawbuffers2-blend -auto"
run_test "spec/EXT_draw_buffers2/fbo-drawbuffers2-colormask" 0.0 "bin/fbo-drawbuffers2-colormask -auto"
run_test "spec/EXT_fog_coord/ext_fog_coord-modes" 0.0 "bin/ext_fog_coord-modes -auto"
run_test "spec/EXT_framebuffer_blit/fbo-blit" 0.0 "bin/fbo-blit -auto"
run_test "spec/EXT_framebuffer_blit/fbo-copypix" 0.0 "bin/fbo-copypix -auto"
run_test "spec/EXT_framebuffer_blit/fbo-readdrawpix" 0.0 "bin/fbo-readdrawpix -auto"
run_test "spec/EXT_framebuffer_blit/fbo-srgb-blit" 0.0 "bin/fbo-srgb-blit -auto"
run_test "spec/EXT_framebuffer_blit/fbo-sys-blit" 0.0 "bin/fbo-sys-blit -auto"
run_test "spec/EXT_framebuffer_blit/fbo-sys-sub-blit" 0.0 "bin/fbo-sys-sub-blit -auto"
run_test "spec/EXT_framebuffer_object/fbo-1d" 0.0 "bin/fbo-1d -auto"
run_test "spec/EXT_framebuffer_object/fbo-3d" 0.0 "bin/fbo-3d -auto"
run_test "spec/EXT_framebuffer_object/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto"
run_test "spec/EXT_framebuffer_object/fbo-alphatest-nocolor" 0.0 "bin/fbo-alphatest-nocolor -auto"
run_test "spec/EXT_framebuffer_object/fbo-alphatest-nocolor-ff" 0.0 "bin/fbo-alphatest-nocolor-ff -auto"
run_test "spec/EXT_framebuffer_object/fbo-bind-renderbuffer" 0.0 "bin/fbo-bind-renderbuffer -auto"
run_test "spec/EXT_framebuffer_object/fbo-blending-formats" 0.0 "bin/fbo-blending-formats -auto"
run_test "spec/EXT_framebuffer_object/fbo-clear-formats" 0.0 "bin/fbo-clear-formats -auto"
run_test "spec/EXT_framebuffer_object/fbo-clearmipmap" 0.0 "bin/fbo-clearmipmap -auto"
run_test "spec/EXT_framebuffer_object/fbo-copyteximage" 0.0 "bin/fbo-copyteximage -auto"
run_test "spec/EXT_framebuffer_object/fbo-copyteximage-simple" 0.0 "bin/fbo-copyteximage-simple -auto"
run_test "spec/EXT_framebuffer_object/fbo-cubemap" 0.0 "bin/fbo-cubemap -auto"
run_test "spec/EXT_framebuffer_object/fbo-depth-sample-compare" 0.0 "bin/fbo-depth-sample-compare -auto"
run_test "spec/EXT_framebuffer_object/fbo-depthtex" 0.0 "bin/fbo-depthtex -auto"
run_test "spec/EXT_framebuffer_object/fbo-drawbuffers" 0.0 "bin/fbo-drawbuffers -auto"
run_test "spec/EXT_framebuffer_object/fbo-drawbuffers-arbfp" 0.0 "bin/fbo-drawbuffers-arbfp -auto"
run_test "spec/EXT_framebuffer_object/fbo-drawbuffers-blend-add" 0.0 "bin/fbo-drawbuffers-blend-add -auto"
run_test "spec/EXT_framebuffer_object/fbo-drawbuffers-fragcolor" 0.0 "bin/fbo-drawbuffers-fragcolor -auto"
run_test "spec/EXT_framebuffer_object/fbo-drawbuffers-maxtargets" 0.0 "bin/fbo-drawbuffers-maxtargets -auto"
run_test "spec/EXT_framebuffer_object/fbo-finish-deleted" 0.0 "bin/fbo-finish-deleted -auto"
run_test "spec/EXT_framebuffer_object/fbo-flushing" 0.0 "bin/fbo-flushing -auto"
run_test "spec/EXT_framebuffer_object/fbo-flushing-2" 0.0 "bin/fbo-flushing-2 -auto"
run_test "spec/EXT_framebuffer_object/fbo-fragcoord" 0.0 "bin/fbo-fragcoord -auto"
run_test "spec/EXT_framebuffer_object/fbo-fragcoord2" 0.0 "bin/fbo-fragcoord2 -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap" 0.0 "bin/fbo-generatemipmap -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-filtering" 0.0 "bin/fbo-generatemipmap-filtering -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-noimage" 0.0 "bin/fbo-generatemipmap-noimage -auto -fbo"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-nonsquare" 0.0 "bin/fbo-generatemipmap-nonsquare -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-npot" 0.0 "bin/fbo-generatemipmap-npot -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-scissor" 0.0 "bin/fbo-generatemipmap-scissor -auto"
run_test "spec/EXT_framebuffer_object/fbo-generatemipmap-viewport" 0.0 "bin/fbo-generatemipmap-viewport -auto"
run_test "spec/EXT_framebuffer_object/fbo-maxsize" 0.0 "bin/fbo-maxsize -auto"
run_test "spec/EXT_framebuffer_object/fbo-nodepth-test" 0.0 "bin/fbo-nodepth-test -auto"
run_test "spec/EXT_framebuffer_object/fbo-nostencil-test" 0.0 "bin/fbo-nostencil-test -auto"
run_test "spec/EXT_framebuffer_object/fbo-readpixels" 0.0 "bin/fbo-readpixels -auto"
run_test "spec/EXT_framebuffer_object/fbo-readpixels-depth-formats" 0.0 "bin/fbo-readpixels-depth-formats -auto"
run_test "spec/EXT_framebuffer_object/fbo-scissor-bitmap" 0.0 "bin/fbo-scissor-bitmap -auto"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX1-blit" 0.0 "bin/fbo-stencil -auto blit GL_STENCIL_INDEX1"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX1-clear" 0.0 "bin/fbo-stencil -auto clear GL_STENCIL_INDEX1"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX1-copypixels" 0.0 "bin/fbo-stencil -auto copypixels GL_STENCIL_INDEX1"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX1-drawpixels" 0.0 "bin/fbo-stencil -auto drawpixels GL_STENCIL_INDEX1"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX1-readpixels" 0.0 "bin/fbo-stencil -auto readpixels GL_STENCIL_INDEX1"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX16-blit" 0.0 "bin/fbo-stencil -auto blit GL_STENCIL_INDEX16"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX16-clear" 0.0 "bin/fbo-stencil -auto clear GL_STENCIL_INDEX16"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX16-copypixels" 0.0 "bin/fbo-stencil -auto copypixels GL_STENCIL_INDEX16"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX16-drawpixels" 0.0 "bin/fbo-stencil -auto drawpixels GL_STENCIL_INDEX16"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX16-readpixels" 0.0 "bin/fbo-stencil -auto readpixels GL_STENCIL_INDEX16"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX4-blit" 0.0 "bin/fbo-stencil -auto blit GL_STENCIL_INDEX4"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX4-clear" 0.0 "bin/fbo-stencil -auto clear GL_STENCIL_INDEX4"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX4-copypixels" 0.0 "bin/fbo-stencil -auto copypixels GL_STENCIL_INDEX4"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX4-drawpixels" 0.0 "bin/fbo-stencil -auto drawpixels GL_STENCIL_INDEX4"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX4-readpixels" 0.0 "bin/fbo-stencil -auto readpixels GL_STENCIL_INDEX4"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX8-blit" 0.0 "bin/fbo-stencil -auto blit GL_STENCIL_INDEX8"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX8-clear" 0.0 "bin/fbo-stencil -auto clear GL_STENCIL_INDEX8"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX8-copypixels" 0.0 "bin/fbo-stencil -auto copypixels GL_STENCIL_INDEX8"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX8-drawpixels" 0.0 "bin/fbo-stencil -auto drawpixels GL_STENCIL_INDEX8"
run_test "spec/EXT_framebuffer_object/fbo-stencil-GL_STENCIL_INDEX8-readpixels" 0.0 "bin/fbo-stencil -auto readpixels GL_STENCIL_INDEX8"
run_test "spec/EXT_framebuffer_object/fbo-storage-completeness" 0.0 "bin/fbo-storage-completeness -auto"
run_test "spec/EXT_framebuffer_object/fbo-storage-formats" 0.0 "bin/fbo-storage-formats -auto"
run_test "spec/EXT_framebuffer_object/fdo20701" 0.0 "bin/fdo20701 -auto"
run_test "spec/EXT_packed_depth_stencil/depthstencil-render-miplevels 1024 s=z24_s8" 0.0 "bin/depthstencil-render-miplevels 1024 s=z24_s8 -auto"
run_test "spec/EXT_packed_depth_stencil/depthstencil-render-miplevels 146 s=z24_s8" 0.0 "bin/depthstencil-render-miplevels 146 s=z24_s8 -auto"
run_test "spec/EXT_packed_depth_stencil/depthstencil-render-miplevels 292 s=z24_s8" 0.0 "bin/depthstencil-render-miplevels 292 s=z24_s8 -auto"
run_test "spec/EXT_packed_depth_stencil/depthstencil-render-miplevels 585 s=z24_s8" 0.0 "bin/depthstencil-render-miplevels 585 s=z24_s8 -auto"
run_test "spec/EXT_packed_depth_stencil/fbo-blit-d24s8" 0.0 "bin/fbo-blit-d24s8 -auto"
run_test "spec/EXT_packed_depth_stencil/fbo-clear-formats" 0.0 "bin/fbo-clear-formats -auto GL_EXT_packed_depth_stencil"
run_test "spec/EXT_packed_depth_stencil/fbo-depth-GL_DEPTH24_STENCIL8-blit" 0.0 "bin/fbo-depth -auto blit GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depth-GL_DEPTH24_STENCIL8-copypixels" 0.0 "bin/fbo-depth -auto copypixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depth-GL_DEPTH24_STENCIL8-drawpixels" 0.0 "bin/fbo-depth -auto drawpixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depth-GL_DEPTH24_STENCIL8-readpixels" 0.0 "bin/fbo-depth -auto readpixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depth-GL_DEPTH24_STENCIL8-tex1d" 0.0 "bin/fbo-depth-tex1d -auto GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-blit" 0.0 "bin/fbo-depthstencil -auto blit GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-copypixels" 0.0 "bin/fbo-depthstencil -auto copypixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-drawpixels-24_8" 0.0 "bin/fbo-depthstencil -auto drawpixels GL_DEPTH24_STENCIL8 24_8"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-drawpixels-32F_24_8_REV" 0.0 "bin/fbo-depthstencil -auto drawpixels GL_DEPTH24_STENCIL8 32F_24_8_REV"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-drawpixels-FLOAT-and-USHORT" 0.0 "bin/fbo-depthstencil -auto drawpixels GL_DEPTH24_STENCIL8 FLOAT-and-USHORT"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-readpixels-24_8" 0.0 "bin/fbo-depthstencil -auto readpixels GL_DEPTH24_STENCIL8 24_8"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-readpixels-32F_24_8_REV" 0.0 "bin/fbo-depthstencil -auto readpixels GL_DEPTH24_STENCIL8 32F_24_8_REV"
run_test "spec/EXT_packed_depth_stencil/fbo-depthstencil-GL_DEPTH24_STENCIL8-readpixels-FLOAT-and-USHORT" 0.0 "bin/fbo-depthstencil -auto readpixels GL_DEPTH24_STENCIL8 FLOAT-and-USHORT"
run_test "spec/EXT_packed_depth_stencil/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_packed_depth_stencil"
run_test "spec/EXT_packed_depth_stencil/fbo-stencil-GL_DEPTH24_STENCIL8-blit" 0.0 "bin/fbo-stencil -auto blit GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-stencil-GL_DEPTH24_STENCIL8-clear" 0.0 "bin/fbo-stencil -auto clear GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-stencil-GL_DEPTH24_STENCIL8-copypixels" 0.0 "bin/fbo-stencil -auto copypixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-stencil-GL_DEPTH24_STENCIL8-drawpixels" 0.0 "bin/fbo-stencil -auto drawpixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/fbo-stencil-GL_DEPTH24_STENCIL8-readpixels" 0.0 "bin/fbo-stencil -auto readpixels GL_DEPTH24_STENCIL8"
run_test "spec/EXT_packed_depth_stencil/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_EXT_packed_depth_stencil -auto -fbo"
run_test "spec/EXT_packed_depth_stencil/readpixels-24_8" 0.0 "bin/ext_packed_depth_stencil-readpixels-24_8 -auto"
run_test "spec/EXT_packed_depth_stencil/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_packed_depth_stencil"
run_test "spec/EXT_packed_depth_stencil/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_packed_depth_stencil bordercolor"
run_test "spec/EXT_packed_depth_stencil/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_packed_depth_stencil bordercolor swizzled"
run_test "spec/EXT_packed_float/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto GL_EXT_packed_float"
run_test "spec/EXT_packed_float/fbo-blending-formats" 0.0 "bin/fbo-blending-formats -auto GL_EXT_packed_float"
run_test "spec/EXT_packed_float/fbo-clear-formats" 0.0 "bin/fbo-clear-formats -auto GL_EXT_packed_float"
run_test "spec/EXT_packed_float/fbo-colormask-formats" 0.0 "bin/fbo-colormask-formats -auto GL_EXT_packed_float"
run_test "spec/EXT_packed_float/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_packed_float"
run_test "spec/EXT_packed_float/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_EXT_packed_float -auto -fbo"
run_test "spec/EXT_packed_float/getteximage-invalid-format-for-packed-type" 0.0 "bin/getteximage-invalid-format-for-packed-type -auto -fbo"
run_test "spec/EXT_packed_float/multisample-formats 2 GL_EXT_packed_float" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_EXT_packed_float"
run_test "spec/EXT_packed_float/multisample-formats 4 GL_EXT_packed_float" 0.0 "bin/ext_framebuffer_multisample-formats -auto 4 GL_EXT_packed_float"
run_test "spec/EXT_packed_float/pack" 0.0 "bin/ext_packed_float-pack -auto -fbo"
run_test "spec/EXT_packed_float/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_packed_float"
run_test "spec/EXT_packed_float/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_packed_float bordercolor"
run_test "spec/EXT_packed_float/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_packed_float bordercolor swizzled"
run_test "spec/EXT_provoking_vertex/provoking-vertex" 0.0 "bin/provoking-vertex -auto"
run_test "spec/EXT_texture_array/array-texture" 0.0 "bin/array-texture -auto"
run_test "spec/EXT_texture_array/compressed texsubimage" 0.0 "bin/ext_texture_array-compressed texsubimage -auto -fbo"
run_test "spec/EXT_texture_array/fbo-array" 0.0 "bin/fbo-array -auto"
run_test "spec/EXT_texture_array/fbo-generatemipmap-array" 0.0 "bin/fbo-generatemipmap-array -auto"
run_test "spec/EXT_texture_array/getteximage-targets 1D_ARRAY" 0.0 "bin/getteximage-targets 1D_ARRAY -auto -fbo"
run_test "spec/EXT_texture_array/getteximage-targets 2D_ARRAY" 0.0 "bin/getteximage-targets 2D_ARRAY -auto -fbo"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-01" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-01.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-02" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-02.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-03" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-03.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-04" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-04.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-05" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-05.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-06" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-06.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-07" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-07.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-08" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-08.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-09" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-09.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow1DArray-bias" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow1DArray-bias.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-01" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-01.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-02" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-02.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-03" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-03.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-04" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-04.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-05" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-05.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-06" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-06.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-07" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-07.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-08" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-08.shader_test -auto"
run_test "spec/EXT_texture_array/glsl-fs-shadow2DArray-09" 0.0 "bin/shader_runner tests/spec/ext_texture_array/glsl-fs-shadow2DArray-09.shader_test -auto"
run_test "spec/EXT_texture_array/maxlayers" 0.0 "bin/ext_texture_array-maxlayers -auto -fbo"
run_test "spec/EXT_texture_compression_latc/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats latc"
run_test "spec/EXT_texture_compression_rgtc/compressedteximage GL_COMPRESSED_RED_GREEN_RGTC2_EXT" 0.0 "bin/compressedteximage GL_COMPRESSED_RED_GREEN_RGTC2_EXT -auto -fbo"
run_test "spec/EXT_texture_compression_rgtc/compressedteximage GL_COMPRESSED_RED_RGTC1_EXT" 0.0 "bin/compressedteximage GL_COMPRESSED_RED_RGTC1_EXT -auto -fbo"
run_test "spec/EXT_texture_compression_rgtc/compressedteximage GL_COMPRESSED_SIGNED_RED_GREEN_RGTC2_EXT" 0.0 "bin/compressedteximage GL_COMPRESSED_SIGNED_RED_GREEN_RGTC2_EXT -auto -fbo"
run_test "spec/EXT_texture_compression_rgtc/compressedteximage GL_COMPRESSED_SIGNED_RED_RGTC1_EXT" 0.0 "bin/compressedteximage GL_COMPRESSED_SIGNED_RED_RGTC1_EXT -auto -fbo"
run_test "spec/EXT_texture_compression_rgtc/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_texture_compression_rgtc"
run_test "spec/EXT_texture_compression_rgtc/fbo-generatemipmap-formats-signed" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_texture_compression_rgtc-signed"
run_test "spec/EXT_texture_compression_rgtc/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats rgtc"
run_test "spec/EXT_texture_compression_rgtc/rgtc-teximage-01" 0.0 "bin/rgtc-teximage-01 -auto"
run_test "spec/EXT_texture_compression_rgtc/rgtc-teximage-02" 0.0 "bin/rgtc-teximage-02 -auto"
run_test "spec/EXT_texture_compression_rgtc/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_compression_rgtc"
run_test "spec/EXT_texture_compression_rgtc/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_compression_rgtc bordercolor"
run_test "spec/EXT_texture_compression_rgtc/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_compression_rgtc bordercolor swizzled"
run_test "spec/EXT_texture_compression_s3tc/gen-compressed-teximage" 0.0 "bin/gen-compressed-teximage -auto"
run_test "spec/EXT_texture_compression_s3tc/getteximage-targets S3TC 2D" 0.0 "bin/getteximage-targets S3TC 2D -auto -fbo"
run_test "spec/EXT_texture_compression_s3tc/getteximage-targets S3TC CUBE" 0.0 "bin/getteximage-targets S3TC CUBE -auto -fbo"
run_test "spec/EXT_texture_compression_s3tc/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats s3tc"
run_test "spec/EXT_texture_compression_s3tc/s3tc-teximage" 0.0 "bin/s3tc-teximage -auto"
run_test "spec/EXT_texture_compression_s3tc/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_compression_s3tc"
run_test "spec/EXT_texture_compression_s3tc/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_compression_s3tc bordercolor"
run_test "spec/EXT_texture_compression_s3tc/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_compression_s3tc bordercolor swizzled"
run_test "spec/EXT_texture_integer/api-drawpixels" 0.0 "bin/ext_texture_integer-api-drawpixels -auto -fbo"
run_test "spec/EXT_texture_integer/api-readpixels" 0.0 "bin/ext_texture_integer-api-readpixels -auto -fbo"
run_test "spec/EXT_texture_integer/api-teximage" 0.0 "bin/ext_texture_integer-api-teximage -auto -fbo"
run_test "spec/EXT_texture_integer/fbo-blending" 0.0 "bin/ext_texture_integer-fbo-blending -auto -fbo"
run_test "spec/EXT_texture_integer/fbo-blending GL_ARB_texture_rg" 0.0 "bin/ext_texture_integer-fbo-blending GL_ARB_texture_rg -auto -fbo"
run_test "spec/EXT_texture_integer/fbo_integer_precision_clear" 0.0 "bin/ext_texture_integer-fbo_integer_precision_clear -auto"
run_test "spec/EXT_texture_integer/fbo_integer_readpixels_sint_uint" 0.0 "bin/ext_texture_integer-fbo_integer_readpixels_sint_uint -auto"
run_test "spec/EXT_texture_integer/getteximage-clamping" 0.0 "bin/ext_texture_integer-getteximage-clamping -auto -fbo"
run_test "spec/EXT_texture_integer/getteximage-clamping GL_ARB_texture_rg" 0.0 "bin/ext_texture_integer-getteximage-clamping GL_ARB_texture_rg -auto -fbo"
run_test "spec/EXT_texture_integer/multisample-formats 2 GL_EXT_texture_integer" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_EXT_texture_integer"
run_test "spec/EXT_texture_integer/multisample-formats 4 GL_EXT_texture_integer" 0.0 "bin/ext_framebuffer_multisample-formats -auto 4 GL_EXT_texture_integer"
run_test "spec/EXT_texture_integer/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_integer"
run_test "spec/EXT_texture_lod_bias/lodbias" 0.0 "bin/lodbias -auto"
run_test "spec/EXT_texture_sRGB/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto GL_EXT_texture_sRGB"
run_test "spec/EXT_texture_sRGB/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_texture_sRGB"
run_test "spec/EXT_texture_sRGB/fbo-srgb" 0.0 "bin/fbo-srgb -auto"
run_test "spec/EXT_texture_sRGB/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats srgb"
run_test "spec/EXT_texture_sRGB/multisample-formats 2 GL_EXT_texture_sRGB" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_EXT_texture_sRGB"
run_test "spec/EXT_texture_sRGB/multisample-formats 4 GL_EXT_texture_sRGB" 0.0 "bin/ext_framebuffer_multisample-formats -auto 4 GL_EXT_texture_sRGB"
run_test "spec/EXT_texture_sRGB/tex-srgb" 0.0 "bin/tex-srgb -auto"
run_test "spec/EXT_texture_sRGB/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_sRGB"
run_test "spec/EXT_texture_sRGB/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_sRGB bordercolor"
run_test "spec/EXT_texture_sRGB/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_sRGB bordercolor swizzled"
run_test "spec/EXT_texture_shared_exponent/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_texture_shared_exponent"
run_test "spec/EXT_texture_shared_exponent/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_EXT_texture_shared_exponent -auto -fbo"
run_test "spec/EXT_texture_shared_exponent/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_shared_exponent"
run_test "spec/EXT_texture_shared_exponent/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_shared_exponent bordercolor"
run_test "spec/EXT_texture_shared_exponent/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_shared_exponent bordercolor swizzled"
run_test "spec/EXT_texture_snorm/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto GL_EXT_texture_snorm"
run_test "spec/EXT_texture_snorm/fbo-colormask-formats" 0.0 "bin/fbo-colormask-formats -auto GL_EXT_texture_snorm"
run_test "spec/EXT_texture_snorm/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_EXT_texture_snorm"
run_test "spec/EXT_texture_snorm/multisample-formats 2 GL_EXT_texture_snorm" 0.0 "bin/ext_framebuffer_multisample-formats -auto 2 GL_EXT_texture_snorm"
run_test "spec/EXT_texture_snorm/multisample-formats 4 GL_EXT_texture_snorm" 0.0 "bin/ext_framebuffer_multisample-formats -auto 4 GL_EXT_texture_snorm"
run_test "spec/EXT_texture_snorm/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_snorm"
run_test "spec/EXT_texture_snorm/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_snorm bordercolor"
run_test "spec/EXT_texture_snorm/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_snorm bordercolor swizzled"
run_test "spec/EXT_texture_swizzle/depth_texture_mode_and_swizzle" 0.0 "bin/depth_texture_mode_and_swizzle -auto -fbo"
run_test "spec/EXT_texture_swizzle/tex-swizzle" 0.0 "bin/tex-swizzle -auto"
run_test "spec/EXT_timer_query/time-elapsed" 0.0 "bin/ext_timer_query-time-elapsed -auto -fbo"
run_test "spec/EXT_timer_query/timer_query" 0.0 "bin/timer_query -auto"
run_test "spec/EXT_transform_feedback/alignment 0" 0.0 "bin/ext_transform_feedback-alignment 0 -auto -fbo"
run_test "spec/EXT_transform_feedback/alignment 12" 0.0 "bin/ext_transform_feedback-alignment 12 -auto -fbo"
run_test "spec/EXT_transform_feedback/alignment 4" 0.0 "bin/ext_transform_feedback-alignment 4 -auto -fbo"
run_test "spec/EXT_transform_feedback/alignment 8" 0.0 "bin/ext_transform_feedback-alignment 8 -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors begin_active" 0.0 "bin/ext_transform_feedback-api-errors begin_active -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors bind_base_active" 0.0 "bin/ext_transform_feedback-api-errors bind_base_active -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors bind_base_max" 0.0 "bin/ext_transform_feedback-api-errors bind_base_max -auto -fbo"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 335 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

