#!/bin/bash


need_pass=418
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord1.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord1.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord2.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord3.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord4.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord5.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord5.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord6.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord6.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord7.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord7.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-normal.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-normal.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-tex-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-tex-coord.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-01.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-02.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-vertex.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-vertex.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name-nested.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name-nested.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/texcoord/implicit-access-max.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/texcoord/implicit-access-max.frag fail 1.10 --check-link"
run_test "spec/glsl-1.10/compiler/texcoord/implicit-access-max.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/texcoord/implicit-access-max.vert fail 1.10 --check-link"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-cos-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-cos-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-cos-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-cos-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-cos-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-cos-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-cos-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-cos-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-cross-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-cross-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-degrees-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-degrees-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-degrees-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-degrees-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-degrees-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-degrees-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-degrees-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-degrees-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-distance-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-distance-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-distance-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-distance-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-distance-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-distance-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-distance-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-distance-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-dot-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-dot-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-dot-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-dot-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-dot-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-dot-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-dot-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-dot-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec2-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec2-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec3-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec3-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec4-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec4-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-fract-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-fract-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-fract-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-fract-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-fract-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-fract-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-fract-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-fract-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-length-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-length-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-length-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-length-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-length-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-length-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-length-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-length-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThanEqual-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log2-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log2-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-log2-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-log2-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-matrixCompMult-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-matrixCompMult-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-matrixCompMult-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-matrixCompMult-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-matrixCompMult-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-matrixCompMult-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-max-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-max-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-min-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-min-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-vec2-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-vec2-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-vec2-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-vec2-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-vec3-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-vec3-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-vec3-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-vec3-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-vec4-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-vec4-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mix-vec4-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mix-vec4-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-mod-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-mod-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-normalize-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-normalize-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-normalize-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-normalize-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-normalize-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-normalize-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-normalize-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-normalize-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-not-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-not-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-not-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-not-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-not-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-not-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-notEqual-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-notEqual-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-add-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-and-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-and-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-and-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-and-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-div-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec2-bvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec2-bvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec3-bvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec3-bvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec4-bvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-bvec4-bvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-float-float-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-float-float-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec2-ivec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec2-ivec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec3-ivec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec3-ivec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec4-ivec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-ivec4-ivec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat2-mat2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat2-mat2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat3-mat3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat3-mat3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat4-mat4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-mat4-mat4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec2-vec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec2-vec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec3-vec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec3-vec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec4-vec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-eq-vec4-vec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ge-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ge-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ge-float-float-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ge-float-float-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ge-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ge-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ge-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ge-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-gt-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-gt-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-gt-float-float-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-gt-float-float-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-gt-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-gt-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-gt-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-gt-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-le-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-le-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-le-float-float-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-le-float-float-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-le-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-le-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-le-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-le-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-lt-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-lt-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-lt-float-float-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-lt-float-float-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-lt-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-lt-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-lt-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-lt-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-mat4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec4-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-mult-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec2-bvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec2-bvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec3-bvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec3-bvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec4-bvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-bvec4-bvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-float-float-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-float-float-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-int-int-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-int-int-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec2-ivec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec2-ivec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec3-ivec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec3-ivec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec4-ivec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-ivec4-ivec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat2-mat2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat2-mat2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat3-mat3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat3-mat3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat4-mat4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-mat4-mat4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec2-vec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec2-vec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec3-vec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec3-vec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec4-vec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-ne-vec4-vec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-neg-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-neg-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-not-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-not-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-not-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-not-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-or-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-or-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-or-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-or-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bool-bool" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bool-bool.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bool-bool-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bool-bool-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-mat4-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-mat4-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-selection-bool-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-mat4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-mat4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-float-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-int-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec2-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec2-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec3-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec3-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec4-int" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec4-int.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat2-mat2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat2-mat2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat3-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat3-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat3-mat3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat3-mat3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat4-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-op-sub-mat4-float.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 418 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

