#!/bin/bash


need_pass=383
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
  else
    let "failures++"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/!OpenGL 1.1/dlist-fdo3129-01" 0.0 "framework/../bin/dlist-fdo3129-01 -auto"
run_test "spec/!OpenGL 1.1/dlist-fdo3129-02" 0.0 "framework/../bin/dlist-fdo3129-02 -auto"
run_test "spec/!OpenGL 1.1/dlist-fdo31590" 0.0 "framework/../bin/dlist-fdo31590 -auto"
run_test "spec/!OpenGL 1.1/draw-arrays-colormaterial" 0.0 "framework/../bin/draw-arrays-colormaterial -auto"
run_test "spec/!OpenGL 1.1/draw-copypixels-sync" 0.0 "framework/../bin/draw-copypixels-sync -auto"
run_test "spec/!OpenGL 1.1/draw-pixels" 0.0 "framework/../bin/draw-pixels -auto"
run_test "spec/!OpenGL 1.1/drawbuffer-modes" 0.0 "framework/../bin/drawbuffer-modes -auto"
run_test "spec/!OpenGL 1.1/fdo10370" 0.0 "framework/../bin/fdo10370 -auto"
run_test "spec/!OpenGL 1.1/fdo23489" 0.0 "framework/../bin/fdo23489 -auto"
run_test "spec/!OpenGL 1.1/fdo23670-depth_test" 0.0 "framework/../bin/fdo23670-depth_test -auto"
run_test "spec/!OpenGL 1.1/fdo23670-drawpix_stencil" 0.0 "framework/../bin/fdo23670-drawpix_stencil -auto"
run_test "spec/!OpenGL 1.1/fog-modes" 0.0 "framework/../bin/fog-modes -auto"
run_test "spec/!OpenGL 1.1/fragment-center" 0.0 "framework/../bin/fragment-center -auto"
run_test "spec/!OpenGL 1.1/geterror-inside-begin" 0.0 "framework/../bin/geterror-inside-begin -auto"
run_test "spec/!OpenGL 1.1/geterror-invalid-enum" 0.0 "framework/../bin/geterror-invalid-enum -auto"
run_test "spec/!OpenGL 1.1/getteximage-luminance" 0.0 "framework/../bin/getteximage-luminance -auto"
run_test "spec/!OpenGL 1.1/getteximage-simple" 0.0 "framework/../bin/getteximage-simple -auto"
run_test "spec/!OpenGL 1.1/getteximage-targets 1D" 0.0 "framework/../bin/getteximage-targets 1D -auto -fbo"
run_test "spec/!OpenGL 1.1/getteximage-targets 2D" 0.0 "framework/../bin/getteximage-targets 2D -auto -fbo"
run_test "spec/!OpenGL 1.1/incomplete-texture-fixed" 0.0 "framework/../bin/incomplete-texture -auto fixed -auto -fbo"
run_test "spec/!OpenGL 1.1/infinite-spot-light" 0.0 "framework/../bin/infinite-spot-light -auto"
run_test "spec/!OpenGL 1.1/masked-clear" 0.0 "framework/../bin/masked-clear -auto -fbo"
run_test "spec/!OpenGL 1.1/max-texture-size-level" 0.0 "framework/../bin/max-texture-size-level -auto -fbo"
run_test "spec/!OpenGL 1.1/point-line-no-cull" 0.0 "framework/../bin/point-line-no-cull -auto"
run_test "spec/!OpenGL 1.1/polygon-mode" 0.0 "framework/../bin/polygon-mode -auto"
run_test "spec/!OpenGL 1.1/proxy-texture" 0.0 "framework/../bin/proxy-texture -auto -fbo"
run_test "spec/!OpenGL 1.1/push-pop-texture-state" 0.0 "framework/../bin/push-pop-texture-state -auto -fbo"
run_test "spec/!OpenGL 1.1/quad-invariance" 0.0 "framework/../bin/quad-invariance -auto -fbo"
run_test "spec/!OpenGL 1.1/r300-readcache" 0.0 "framework/../bin/r300-readcache -auto"
run_test "spec/!OpenGL 1.1/read-front" 0.0 "framework/../bin/read-front -auto"
run_test "spec/!OpenGL 1.1/roundmode-getintegerv" 0.0 "framework/../bin/roundmode-getintegerv -auto"
run_test "spec/!OpenGL 1.1/roundmode-pixelstore" 0.0 "framework/../bin/roundmode-pixelstore -auto"
run_test "spec/!OpenGL 1.1/scissor-bitmap" 0.0 "framework/../bin/scissor-bitmap -auto"
run_test "spec/!OpenGL 1.1/scissor-clear" 0.0 "framework/../bin/scissor-clear -auto"
run_test "spec/!OpenGL 1.1/scissor-copypixels" 0.0 "framework/../bin/scissor-copypixels -auto"
run_test "spec/!OpenGL 1.1/scissor-depth-clear" 0.0 "framework/../bin/scissor-depth-clear -auto"
run_test "spec/!OpenGL 1.1/scissor-many" 0.0 "framework/../bin/scissor-many -auto"
run_test "spec/!OpenGL 1.1/scissor-offscreen" 0.0 "framework/../bin/scissor-offscreen -auto"
run_test "spec/!OpenGL 1.1/scissor-stencil-clear" 0.0 "framework/../bin/scissor-stencil-clear -auto"
run_test "spec/!OpenGL 1.1/sized-texture-format-channels" 0.0 "framework/../bin/sized-texture-format-channels -auto -fbo"
run_test "spec/!OpenGL 1.1/stencil-drawpixels" 0.0 "framework/../bin/stencil-drawpixels -auto"
run_test "spec/!OpenGL 1.1/texgen" 0.0 "framework/../bin/texgen -auto"
run_test "spec/!OpenGL 1.1/texredefine" 0.0 "framework/../bin/texredefine -auto"
run_test "spec/!OpenGL 1.1/texsubimage" 0.0 "framework/../bin/texsubimage -auto"
run_test "spec/!OpenGL 1.1/texture-al" 0.0 "framework/../bin/texture-al -auto"
run_test "spec/!OpenGL 1.1/texwrap 1D" 0.0 "framework/../bin/texwrap -fbo -auto 1D GL_RGBA8"
run_test "spec/!OpenGL 1.1/texwrap 1D bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto 1D GL_RGBA8 bordercolor"
run_test "spec/!OpenGL 1.1/texwrap 1D proj" 0.0 "framework/../bin/texwrap -fbo -auto 1D GL_RGBA8 proj"
run_test "spec/!OpenGL 1.1/texwrap 1D proj bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto 1D GL_RGBA8 proj bordercolor"
run_test "spec/!OpenGL 1.1/texwrap 2D" 0.0 "framework/../bin/texwrap -fbo -auto 2D GL_RGBA8"
run_test "spec/!OpenGL 1.1/texwrap 2D bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto 2D GL_RGBA8 bordercolor"
run_test "spec/!OpenGL 1.1/texwrap 2D proj" 0.0 "framework/../bin/texwrap -fbo -auto 2D GL_RGBA8 proj"
run_test "spec/!OpenGL 1.1/texwrap 2D proj bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto 2D GL_RGBA8 proj bordercolor"
run_test "spec/!OpenGL 1.1/texwrap formats" 0.0 "framework/../bin/texwrap -fbo -auto"
run_test "spec/!OpenGL 1.1/texwrap formats bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto bordercolor"
run_test "spec/!OpenGL 1.1/texwrap formats bordercolor-swizzled" 0.0 "framework/../bin/texwrap -fbo -auto bordercolor swizzled"
run_test "spec/!OpenGL 1.1/tri-tex-crash" 0.0 "framework/../bin/tri-tex-crash -auto"
run_test "spec/!OpenGL 1.1/triangle-guardband-viewport" 0.0 "framework/../bin/triangle-guardband-viewport -auto -fbo"
run_test "spec/!OpenGL 1.1/two-sided-lighting" 0.0 "framework/../bin/two-sided-lighting -auto"
run_test "spec/!OpenGL 1.1/user-clip" 0.0 "framework/../bin/user-clip -auto"
run_test "spec/!OpenGL 1.1/varray-disabled" 0.0 "framework/../bin/varray-disabled -auto"
run_test "spec/!OpenGL 1.1/vbo-buffer-unmap" 0.0 "framework/../bin/vbo-buffer-unmap -auto"
run_test "spec/!OpenGL 1.1/windowoverlap" 0.0 "framework/../bin/windowoverlap -auto"
run_test "spec/!OpenGL 1.2/copyteximage 3D" 0.0 "framework/../bin/copyteximage -auto 3D"
run_test "spec/!OpenGL 1.2/crash-texparameter-before-teximage" 0.0 "framework/../bin/crash-texparameter-before-teximage -auto"
run_test "spec/!OpenGL 1.2/draw-elements-vs-inputs" 0.0 "framework/../bin/draw-elements-vs-inputs -auto"
run_test "spec/!OpenGL 1.2/getteximage-targets 3D" 0.0 "framework/../bin/getteximage-targets 3D -auto -fbo"
run_test "spec/!OpenGL 1.2/levelclamp" 0.0 "framework/../bin/levelclamp -auto"
run_test "spec/!OpenGL 1.2/lodclamp" 0.0 "framework/../bin/lodclamp -auto"
run_test "spec/!OpenGL 1.2/lodclamp-between" 0.0 "framework/../bin/lodclamp-between -auto"
run_test "spec/!OpenGL 1.2/lodclamp-between-max" 0.0 "framework/../bin/lodclamp-between-max -auto"
run_test "spec/!OpenGL 1.2/mipmap-setup" 0.0 "framework/../bin/mipmap-setup -auto"
run_test "spec/!OpenGL 1.2/tex-skipped-unit" 0.0 "framework/../bin/tex-skipped-unit -auto"
run_test "spec/!OpenGL 1.2/tex3d" 0.0 "framework/../bin/tex3d -auto"
run_test "spec/!OpenGL 1.2/teximage-errors" 0.0 "framework/../bin/teximage-errors -auto"
run_test "spec/!OpenGL 1.2/texture-packed-formats" 0.0 "framework/../bin/texture-packed-formats -auto"
run_test "spec/!OpenGL 1.2/texwrap 3D" 0.0 "framework/../bin/texwrap -fbo -auto 3D GL_RGBA8"
run_test "spec/!OpenGL 1.2/texwrap 3D bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto 3D GL_RGBA8 bordercolor"
run_test "spec/!OpenGL 1.2/texwrap 3D proj" 0.0 "framework/../bin/texwrap -fbo -auto 3D GL_RGBA8 proj"
run_test "spec/!OpenGL 1.2/texwrap 3D proj bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto 3D GL_RGBA8 proj bordercolor"
run_test "spec/!OpenGL 1.2/two-sided-lighting-separate-specular" 0.0 "framework/../bin/two-sided-lighting-separate-specular -auto"
run_test "spec/!OpenGL 1.3/tex-border-1" 0.0 "framework/../bin/tex-border-1 -auto"
run_test "spec/!OpenGL 1.3/tex3d-depth1" 0.0 "framework/../bin/tex3d-depth1 -auto -fbo"
run_test "spec/!OpenGL 1.3/texunits" 0.0 "framework/../bin/texunits -auto"
run_test "spec/!OpenGL 1.4/blendminmax" 0.0 "framework/../bin/blendminmax -auto"
run_test "spec/!OpenGL 1.4/blendsquare" 0.0 "framework/../bin/blendsquare -auto"
run_test "spec/!OpenGL 1.4/copy-pixels" 0.0 "framework/../bin/copy-pixels -auto"
run_test "spec/!OpenGL 1.4/draw-batch" 0.0 "framework/../bin/draw-batch -auto"
run_test "spec/!OpenGL 1.4/stencil-wrap" 0.0 "framework/../bin/stencil-wrap -auto"
run_test "spec/!OpenGL 1.4/tex-miplevel-selection" 0.0 "framework/../bin/tex-miplevel-selection -auto -nobias -nolod"
run_test "spec/!OpenGL 1.4/tex-miplevel-selection-lod" 0.0 "framework/../bin/tex-miplevel-selection -auto -nobias"
run_test "spec/!OpenGL 1.4/tex-miplevel-selection-lod-bias" 0.0 "framework/../bin/tex-miplevel-selection -auto"
run_test "spec/!OpenGL 1.4/tex1d-2dborder" 0.0 "framework/../bin/tex1d-2dborder -auto"
run_test "spec/!OpenGL 1.4/triangle-rasterization-overdraw" 0.0 "framework/../bin/triangle-rasterization-overdraw -auto"
run_test "spec/!OpenGL 1.5/draw-elements" 0.0 "framework/../bin/draw-elements -auto"
run_test "spec/!OpenGL 1.5/draw-elements-user" 0.0 "framework/../bin/draw-elements -auto user"
run_test "spec/!OpenGL 1.5/draw-vertices" 0.0 "framework/../bin/draw-vertices -auto"
run_test "spec/!OpenGL 1.5/draw-vertices-user" 0.0 "framework/../bin/draw-vertices -auto user"
run_test "spec/!OpenGL 1.5/isbufferobj" 0.0 "framework/../bin/isbufferobj -auto"
run_test "spec/!OpenGL 2.0/attribs" 0.0 "framework/../bin/attribs -auto -fbo"
run_test "spec/!OpenGL 2.0/clear-varray-2.0" 0.0 "framework/../bin/clear-varray-2.0 -auto"
run_test "spec/!OpenGL 2.0/clip-flag-behavior" 0.0 "framework/../bin/clip-flag-behavior -auto"
run_test "spec/!OpenGL 2.0/depth-tex-modes-glsl" 0.0 "framework/../bin/depth-tex-modes-glsl -auto"
run_test "spec/!OpenGL 2.0/fragment-and-vertex-texturing" 0.0 "framework/../bin/fragment-and-vertex-texturing -auto"
run_test "spec/!OpenGL 2.0/getattriblocation-conventional" 0.0 "framework/../bin/getattriblocation-conventional -auto"
run_test "spec/!OpenGL 2.0/gl-2.0-edgeflag" 0.0 "framework/../bin/gl-2.0-edgeflag -auto -fbo"
run_test "spec/!OpenGL 2.0/incomplete-texture-glsl" 0.0 "framework/../bin/incomplete-texture -auto glsl -auto -fbo"
run_test "spec/!OpenGL 2.0/occlusion-query-discard" 0.0 "framework/../bin/occlusion-query-discard -auto"
run_test "spec/!OpenGL 2.0/stencil-twoside" 0.0 "framework/../bin/stencil-twoside -auto"
run_test "spec/!OpenGL 2.0/tex3d-npot" 0.0 "framework/../bin/tex3d-npot -auto"
run_test "spec/!OpenGL 2.0/vertex-program-two-side" 0.0 "framework/../bin/vertex-program-two-side -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side back" 0.0 "framework/../bin/vertex-program-two-side back -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side back back2" 0.0 "framework/../bin/vertex-program-two-side back back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side back front2" 0.0 "framework/../bin/vertex-program-two-side back front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side back front2 back2" 0.0 "framework/../bin/vertex-program-two-side back front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side back2" 0.0 "framework/../bin/vertex-program-two-side back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled" 0.0 "framework/../bin/vertex-program-two-side enabled -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled back" 0.0 "framework/../bin/vertex-program-two-side enabled back -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled back back2" 0.0 "framework/../bin/vertex-program-two-side enabled back back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled back front2" 0.0 "framework/../bin/vertex-program-two-side enabled back front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled back front2 back2" 0.0 "framework/../bin/vertex-program-two-side enabled back front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled back2" 0.0 "framework/../bin/vertex-program-two-side enabled back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front" 0.0 "framework/../bin/vertex-program-two-side enabled front -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front back" 0.0 "framework/../bin/vertex-program-two-side enabled front back -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front back back2" 0.0 "framework/../bin/vertex-program-two-side enabled front back back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front back front2" 0.0 "framework/../bin/vertex-program-two-side enabled front back front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front back front2 back2" 0.0 "framework/../bin/vertex-program-two-side enabled front back front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front back2" 0.0 "framework/../bin/vertex-program-two-side enabled front back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front front2" 0.0 "framework/../bin/vertex-program-two-side enabled front front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front front2 back2" 0.0 "framework/../bin/vertex-program-two-side enabled front front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front2" 0.0 "framework/../bin/vertex-program-two-side enabled front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side enabled front2 back2" 0.0 "framework/../bin/vertex-program-two-side enabled front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front" 0.0 "framework/../bin/vertex-program-two-side front -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front back" 0.0 "framework/../bin/vertex-program-two-side front back -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front back back2" 0.0 "framework/../bin/vertex-program-two-side front back back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front back front2" 0.0 "framework/../bin/vertex-program-two-side front back front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front back front2 back2" 0.0 "framework/../bin/vertex-program-two-side front back front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front back2" 0.0 "framework/../bin/vertex-program-two-side front back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front front2" 0.0 "framework/../bin/vertex-program-two-side front front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front front2 back2" 0.0 "framework/../bin/vertex-program-two-side front front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front2" 0.0 "framework/../bin/vertex-program-two-side front2 -auto -fbo"
run_test "spec/!OpenGL 2.0/vertex-program-two-side front2 back2" 0.0 "framework/../bin/vertex-program-two-side front2 back2 -auto -fbo"
run_test "spec/!OpenGL 2.1/minmax" 0.0 "framework/../bin/gl-2.1-minmax -auto -fbo"
run_test "spec/!OpenGL 3.0/array-depth-roundtrip" 0.0 "framework/../bin/array-depth-roundtrip -auto"
run_test "spec/!OpenGL 3.0/attribs" 0.0 "framework/../bin/attribs GL3 -auto -fbo"
run_test "spec/!OpenGL 3.0/bindfragdata-invalid-parameters" 0.0 "framework/../bin/bindfragdata-invalid-parameters -auto -fbo"
run_test "spec/!OpenGL 3.0/bindfragdata-link-error" 0.0 "framework/../bin/bindfragdata-link-error -auto -fbo"
run_test "spec/!OpenGL 3.0/bindfragdata-nonexistent-variable" 0.0 "framework/../bin/bindfragdata-nonexistent-variable -auto -fbo"
run_test "spec/!OpenGL 3.0/clearbuffer-invalid-buffer" 0.0 "framework/../bin/clearbuffer-invalid-buffer -auto -fbo"
run_test "spec/!OpenGL 3.0/depth-cube-map" 0.0 "framework/../bin/depth-cube-map -auto"
run_test "spec/!OpenGL 3.0/genmipmap-errors" 0.0 "framework/../bin/genmipmap-errors -auto -fbo"
run_test "spec/!OpenGL 3.0/getfragdatalocation" 0.0 "framework/../bin/getfragdatalocation -auto -fbo"
run_test "spec/!OpenGL 3.0/gl-3.0-required-renderbuffer-attachment-formats" 0.0 "framework/../bin/gl-3.0-required-renderbuffer-attachment-formats -auto -fbo"
run_test "spec/!OpenGL 3.0/gl-3.0-required-sized-texture-formats" 0.0 "framework/../bin/gl-3.0-required-sized-texture-formats -auto -fbo"
run_test "spec/!OpenGL 3.0/gl-3.0-required-texture-attachment-formats" 0.0 "framework/../bin/gl-3.0-required-texture-attachment-formats -auto -fbo"
run_test "spec/!OpenGL 3.0/integer-errors" 0.0 "framework/../bin/integer-errors -auto -fbo"
run_test "spec/!OpenGL 3.0/minmax" 0.0 "framework/../bin/gl-3.0-minmax -auto -fbo"
run_test "spec/!OpenGL 3.0/sampler-cube-shadow" 0.0 "framework/../bin/sampler-cube-shadow -auto"
run_test "spec/3DFX_texture_compression_FXT1/compressedteximage GL_COMPRESSED_RGBA_FXT1_3DFX" 0.0 "framework/../bin/compressedteximage GL_COMPRESSED_RGBA_FXT1_3DFX -auto -fbo"
run_test "spec/3DFX_texture_compression_FXT1/compressedteximage GL_COMPRESSED_RGB_FXT1_3DFX" 0.0 "framework/../bin/compressedteximage GL_COMPRESSED_RGB_FXT1_3DFX -auto -fbo"
run_test "spec/3DFX_texture_compression_FXT1/fbo-generatemipmap-formats" 0.0 "framework/../bin/fbo-generatemipmap-formats -auto GL_3DFX_texture_compression_FXT1"
run_test "spec/3DFX_texture_compression_FXT1/fxt1-teximage" 0.0 "framework/../bin/fxt1-teximage -auto"
run_test "spec/3DFX_texture_compression_FXT1/invalid formats" 0.0 "framework/../bin/arb_texture_compression-invalid-formats fxt1"
run_test "spec/AMD_seamless_cubemap_per_texture/amd_seamless_cubemap_per_texture" 0.0 "framework/../bin/amd_seamless_cubemap_per_texture -auto"
run_test "spec/AMD_shader_stencil_export/arb-undefined.frag" 0.0 "framework/../bin/glslparsertest tests/spec/amd_shader_stencil_export/arb-undefined.frag fail 1.20"
run_test "spec/APPLE_object_purgeable/object_purgeable-api-pbo" 0.0 "framework/../bin/object_purgeable-api-pbo -auto"
run_test "spec/APPLE_object_purgeable/object_purgeable-api-texture" 0.0 "framework/../bin/object_purgeable-api-texture -auto"
run_test "spec/APPLE_object_purgeable/object_purgeable-api-vbo" 0.0 "framework/../bin/object_purgeable-api-vbo -auto"
run_test "spec/APPLE_vertex_array_object/isvertexarray" 0.0 "framework/../bin/arb_vertex_array-isvertexarray apple -auto -fbo"
run_test "spec/APPLE_vertex_array_object/vao-01" 0.0 "framework/../bin/vao-01 -auto"
run_test "spec/APPLE_vertex_array_object/vao-02" 0.0 "framework/../bin/vao-02 -auto"
run_test "spec/ARB_ES2_compatibility/FBO blit from missing attachment (ES2 completeness rules)" 0.0 "framework/../bin/fbo-missing-attachment-blit -auto es2 from"
run_test "spec/ARB_ES2_compatibility/FBO blit to missing attachment (ES2 completeness rules)" 0.0 "framework/../bin/fbo-missing-attachment-blit -auto es2 to"
run_test "spec/ARB_ES2_compatibility/arb_es2_compatibility-drawbuffers" 0.0 "framework/../bin/arb_es2_compatibility-drawbuffers -auto"
run_test "spec/ARB_ES2_compatibility/arb_es2_compatibility-fixed-type" 0.0 "framework/../bin/arb_es2_compatibility-fixed-type -auto"
run_test "spec/ARB_ES2_compatibility/arb_es2_compatibility-getshaderprecisionformat" 0.0 "framework/../bin/arb_es2_compatibility-getshaderprecisionformat -auto"
run_test "spec/ARB_ES2_compatibility/arb_es2_compatibility-maxvectors" 0.0 "framework/../bin/arb_es2_compatibility-maxvectors -auto"
run_test "spec/ARB_ES2_compatibility/arb_es2_compatibility-releaseshadercompiler" 0.0 "framework/../bin/arb_es2_compatibility-releaseshadercompiler -auto"
run_test "spec/ARB_ES2_compatibility/arb_es2_compatibility-shadercompiler" 0.0 "framework/../bin/arb_es2_compatibility-shadercompiler -auto"
run_test "spec/ARB_ES2_compatibility/fbo-alphatest-formats" 0.0 "framework/../bin/fbo-alphatest-formats -auto GL_ARB_ES2_compatibility"
run_test "spec/ARB_ES2_compatibility/fbo-blending-formats" 0.0 "framework/../bin/fbo-blending-formats -auto GL_ARB_ES2_compatibility"
run_test "spec/ARB_ES2_compatibility/fbo-clear-formats" 0.0 "framework/../bin/fbo-clear-formats -auto GL_ARB_ES2_compatibility"
run_test "spec/ARB_ES2_compatibility/fbo-colormask-formats" 0.0 "framework/../bin/fbo-colormask-formats -auto GL_ARB_ES2_compatibility"
run_test "spec/ARB_ES2_compatibility/fbo-generatemipmap-formats" 0.0 "framework/../bin/fbo-generatemipmap-formats -auto GL_ARB_ES2_compatibility"
run_test "spec/ARB_ES2_compatibility/get-renderbuffer-internalformat" 0.0 "framework/../bin/get-renderbuffer-internalformat GL_ARB_ES2_compatibility -auto -fbo"
run_test "spec/ARB_ES2_compatibility/texwrap formats" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_ES2_compatibility"
run_test "spec/ARB_ES2_compatibility/texwrap formats bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_ES2_compatibility bordercolor"
run_test "spec/ARB_ES2_compatibility/texwrap formats bordercolor-swizzled" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_ES2_compatibility bordercolor swizzled"
run_test "spec/ARB_blend_func_extended/arb_blend_func_extended-bindfragdataindexed-invalid-parameters" 0.0 "framework/../bin/arb_blend_func_extended-bindfragdataindexed-invalid-parameters -auto"
run_test "spec/ARB_blend_func_extended/arb_blend_func_extended-blend-api" 0.0 "framework/../bin/arb_blend_func_extended-blend-api -auto"
run_test "spec/ARB_blend_func_extended/arb_blend_func_extended-error-at-begin" 0.0 "framework/../bin/arb_blend_func_extended-error-at-begin -auto"
run_test "spec/ARB_blend_func_extended/arb_blend_func_extended-fbo-extended-blend" 0.0 "framework/../bin/arb_blend_func_extended-fbo-extended-blend -auto"
run_test "spec/ARB_blend_func_extended/arb_blend_func_extended-fbo-extended-blend-explicit" 0.0 "framework/../bin/arb_blend_func_extended-fbo-extended-blend-explicit -auto"
run_test "spec/ARB_blend_func_extended/arb_blend_func_extended-getfragdataindex" 0.0 "framework/../bin/arb_blend_func_extended-getfragdataindex -auto"
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-clear" 0.0 "framework/../bin/arb_color_buffer_float-clear GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-drawpixels" 0.0 "framework/../bin/arb_color_buffer_float-drawpixels GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-getteximage" 0.0 "framework/../bin/arb_color_buffer_float-getteximage GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-probepixel" 0.0 "framework/../bin/arb_color_buffer_float-probepixel GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-queries" 0.0 "framework/../bin/arb_color_buffer_float-queries GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-readpixels" 0.0 "framework/../bin/arb_color_buffer_float-readpixels GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-render" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA16F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-render-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA16F fog "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-render-sanity" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA16F sanity "
run_test "spec/ARB_color_buffer_float/GL_RGBA16F-render-sanity-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA16F sanity fog"
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-clear" 0.0 "framework/../bin/arb_color_buffer_float-clear GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-drawpixels" 0.0 "framework/../bin/arb_color_buffer_float-drawpixels GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-getteximage" 0.0 "framework/../bin/arb_color_buffer_float-getteximage GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-probepixel" 0.0 "framework/../bin/arb_color_buffer_float-probepixel GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-queries" 0.0 "framework/../bin/arb_color_buffer_float-queries GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-readpixels" 0.0 "framework/../bin/arb_color_buffer_float-readpixels GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-render" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA32F  "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-render-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA32F fog "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-render-sanity" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA32F sanity "
run_test "spec/ARB_color_buffer_float/GL_RGBA32F-render-sanity-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA32F sanity fog"
run_test "spec/ARB_color_buffer_float/GL_RGBA8-clear" 0.0 "framework/../bin/arb_color_buffer_float-clear GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-drawpixels" 0.0 "framework/../bin/arb_color_buffer_float-drawpixels GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-getteximage" 0.0 "framework/../bin/arb_color_buffer_float-getteximage GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-probepixel" 0.0 "framework/../bin/arb_color_buffer_float-probepixel GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-queries" 0.0 "framework/../bin/arb_color_buffer_float-queries GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-readpixels" 0.0 "framework/../bin/arb_color_buffer_float-readpixels GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-render" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-render-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8 fog "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-render-sanity" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8 sanity "
run_test "spec/ARB_color_buffer_float/GL_RGBA8-render-sanity-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8 sanity fog"
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-clear" 0.0 "framework/../bin/arb_color_buffer_float-clear GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-drawpixels" 0.0 "framework/../bin/arb_color_buffer_float-drawpixels GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-getteximage" 0.0 "framework/../bin/arb_color_buffer_float-getteximage GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-probepixel" 0.0 "framework/../bin/arb_color_buffer_float-probepixel GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-queries" 0.0 "framework/../bin/arb_color_buffer_float-queries GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-readpixels" 0.0 "framework/../bin/arb_color_buffer_float-readpixels GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8_SNORM  "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8_SNORM fog "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render-sanity" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8_SNORM sanity "
run_test "spec/ARB_color_buffer_float/GL_RGBA8_SNORM-render-sanity-fog" 0.0 "framework/../bin/arb_color_buffer_float-render GL_RGBA8_SNORM sanity fog"
run_test "spec/ARB_color_buffer_float/mixed-mrt" 0.0 "framework/../bin/arb_color_buffer_float-mrt mixed  "
run_test "spec/ARB_copy_buffer/copy_buffer_coherency" 0.0 "framework/../bin/copy_buffer_coherency -auto"
run_test "spec/ARB_copy_buffer/copybuffersubdata" 0.0 "framework/../bin/copybuffersubdata -auto"
run_test "spec/ARB_copy_buffer/dlist" 0.0 "framework/../bin/arb_copy_buffer-dlist -auto -fbo"
run_test "spec/ARB_copy_buffer/get" 0.0 "framework/../bin/arb_copy_buffer-get -auto -fbo"
run_test "spec/ARB_copy_buffer/negative-bound-zero" 0.0 "framework/../bin/arb_copy_buffer-negative-bound-zero -auto -fbo"
run_test "spec/ARB_copy_buffer/negative-bounds" 0.0 "framework/../bin/arb_copy_buffer-negative-bounds -auto -fbo"
run_test "spec/ARB_copy_buffer/negative-mapped" 0.0 "framework/../bin/arb_copy_buffer-negative-mapped -auto -fbo"
run_test "spec/ARB_copy_buffer/overlap" 0.0 "framework/../bin/arb_copy_buffer-overlap -auto -fbo"
run_test "spec/ARB_copy_buffer/targets" 0.0 "framework/../bin/arb_copy_buffer-targets -auto -fbo"
run_test "spec/ARB_depth_buffer_float/fbo-clear-formats" 0.0 "framework/../bin/fbo-clear-formats -auto GL_ARB_depth_buffer_float"
run_test "spec/ARB_depth_buffer_float/fbo-clear-formats stencil" 0.0 "framework/../bin/fbo-clear-formats GL_ARB_depth_buffer_float stencil -auto"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-blit" 0.0 "framework/../bin/fbo-depth -auto blit GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-copypixels" 0.0 "framework/../bin/fbo-depth -auto copypixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-drawpixels" 0.0 "framework/../bin/fbo-depth -auto drawpixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-readpixels" 0.0 "framework/../bin/fbo-depth -auto readpixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH32F_STENCIL8-tex1d" 0.0 "framework/../bin/fbo-depth-tex1d -auto GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-blit" 0.0 "framework/../bin/fbo-depth -auto blit GL_DEPTH_COMPONENT32F"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-drawpixels" 0.0 "framework/../bin/fbo-depth -auto drawpixels GL_DEPTH_COMPONENT32F"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-readpixels" 0.0 "framework/../bin/fbo-depth -auto readpixels GL_DEPTH_COMPONENT32F"
run_test "spec/ARB_depth_buffer_float/fbo-depth-GL_DEPTH_COMPONENT32F-tex1d" 0.0 "framework/../bin/fbo-depth-tex1d -auto GL_DEPTH_COMPONENT32F"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-blit" 0.0 "framework/../bin/fbo-depthstencil -auto blit GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-copypixels" 0.0 "framework/../bin/fbo-depthstencil -auto copypixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-drawpixels-24_8" 0.0 "framework/../bin/fbo-depthstencil -auto drawpixels GL_DEPTH32F_STENCIL8 24_8"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-drawpixels-32F_24_8_REV" 0.0 "framework/../bin/fbo-depthstencil -auto drawpixels GL_DEPTH32F_STENCIL8 32F_24_8_REV"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-drawpixels-FLOAT-and-USHORT" 0.0 "framework/../bin/fbo-depthstencil -auto drawpixels GL_DEPTH32F_STENCIL8 FLOAT-and-USHORT"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-readpixels-24_8" 0.0 "framework/../bin/fbo-depthstencil -auto readpixels GL_DEPTH32F_STENCIL8 24_8"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-readpixels-32F_24_8_REV" 0.0 "framework/../bin/fbo-depthstencil -auto readpixels GL_DEPTH32F_STENCIL8 32F_24_8_REV"
run_test "spec/ARB_depth_buffer_float/fbo-depthstencil-GL_DEPTH32F_STENCIL8-readpixels-FLOAT-and-USHORT" 0.0 "framework/../bin/fbo-depthstencil -auto readpixels GL_DEPTH32F_STENCIL8 FLOAT-and-USHORT"
run_test "spec/ARB_depth_buffer_float/fbo-generatemipmap-formats" 0.0 "framework/../bin/fbo-generatemipmap-formats -auto GL_ARB_depth_buffer_float"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-blit" 0.0 "framework/../bin/fbo-stencil -auto blit GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-clear" 0.0 "framework/../bin/fbo-stencil -auto clear GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-copypixels" 0.0 "framework/../bin/fbo-stencil -auto copypixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-drawpixels" 0.0 "framework/../bin/fbo-stencil -auto drawpixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/fbo-stencil-GL_DEPTH32F_STENCIL8-readpixels" 0.0 "framework/../bin/fbo-stencil -auto readpixels GL_DEPTH32F_STENCIL8"
run_test "spec/ARB_depth_buffer_float/get-renderbuffer-internalformat" 0.0 "framework/../bin/get-renderbuffer-internalformat GL_ARB_depth_buffer_float -auto -fbo"
run_test "spec/ARB_depth_buffer_float/texwrap formats" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_depth_buffer_float"
run_test "spec/ARB_depth_buffer_float/texwrap formats bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_depth_buffer_float bordercolor"
run_test "spec/ARB_depth_buffer_float/texwrap formats bordercolor-swizzled" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_depth_buffer_float bordercolor swizzled"
run_test "spec/ARB_depth_clamp/depth_clamp" 0.0 "framework/../bin/depth_clamp -auto"
run_test "spec/ARB_depth_texture/depth-level-clamp" 0.0 "framework/../bin/depth-level-clamp -auto"
run_test "spec/ARB_depth_texture/depth-tex-modes" 0.0 "framework/../bin/depth-tex-modes -auto"
run_test "spec/ARB_depth_texture/fbo-clear-formats" 0.0 "framework/../bin/fbo-clear-formats -auto GL_ARB_depth_texture"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-blit" 0.0 "framework/../bin/fbo-depth -auto blit GL_DEPTH_COMPONENT16"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-copypixels" 0.0 "framework/../bin/fbo-depth -auto copypixels GL_DEPTH_COMPONENT16"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-drawpixels" 0.0 "framework/../bin/fbo-depth -auto drawpixels GL_DEPTH_COMPONENT16"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-readpixels" 0.0 "framework/../bin/fbo-depth -auto readpixels GL_DEPTH_COMPONENT16"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT16-tex1d" 0.0 "framework/../bin/fbo-depth-tex1d -auto GL_DEPTH_COMPONENT16"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-blit" 0.0 "framework/../bin/fbo-depth -auto blit GL_DEPTH_COMPONENT24"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-copypixels" 0.0 "framework/../bin/fbo-depth -auto copypixels GL_DEPTH_COMPONENT24"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-drawpixels" 0.0 "framework/../bin/fbo-depth -auto drawpixels GL_DEPTH_COMPONENT24"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-readpixels" 0.0 "framework/../bin/fbo-depth -auto readpixels GL_DEPTH_COMPONENT24"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT24-tex1d" 0.0 "framework/../bin/fbo-depth-tex1d -auto GL_DEPTH_COMPONENT24"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-blit" 0.0 "framework/../bin/fbo-depth -auto blit GL_DEPTH_COMPONENT32"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-copypixels" 0.0 "framework/../bin/fbo-depth -auto copypixels GL_DEPTH_COMPONENT32"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-drawpixels" 0.0 "framework/../bin/fbo-depth -auto drawpixels GL_DEPTH_COMPONENT32"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-readpixels" 0.0 "framework/../bin/fbo-depth -auto readpixels GL_DEPTH_COMPONENT32"
run_test "spec/ARB_depth_texture/fbo-depth-GL_DEPTH_COMPONENT32-tex1d" 0.0 "framework/../bin/fbo-depth-tex1d -auto GL_DEPTH_COMPONENT32"
run_test "spec/ARB_depth_texture/fbo-generatemipmap-formats" 0.0 "framework/../bin/fbo-generatemipmap-formats -auto GL_ARB_depth_texture"
run_test "spec/ARB_depth_texture/get-renderbuffer-internalformat" 0.0 "framework/../bin/get-renderbuffer-internalformat GL_ARB_depth_texture -auto -fbo"
run_test "spec/ARB_depth_texture/texwrap formats" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_depth_texture"
run_test "spec/ARB_depth_texture/texwrap formats bordercolor" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_depth_texture bordercolor"
run_test "spec/ARB_depth_texture/texwrap formats bordercolor-swizzled" 0.0 "framework/../bin/texwrap -fbo -auto GL_ARB_depth_texture bordercolor swizzled"
run_test "spec/ARB_draw_buffers/arb_draw_buffers-state_change" 0.0 "framework/../bin/arb_draw_buffers-state_change -auto"
run_test "spec/ARB_draw_buffers_blend/fbo-draw-buffers-blend" 0.0 "framework/../bin/fbo-draw-buffers-blend -auto"
run_test "spec/ARB_draw_elements_base_vertex/dlist-arb_draw_instanced" 0.0 "framework/../bin/arb_draw_elements_base_vertex-dlist-arb_draw_instanced -auto -fbo"
run_test "spec/ARB_draw_elements_base_vertex/draw-elements-base-vertex" 0.0 "framework/../bin/draw-elements-base-vertex -auto"
run_test "spec/ARB_draw_elements_base_vertex/draw-elements-base-vertex-bounds" 0.0 "framework/../bin/draw-elements-base-vertex-bounds -auto"
run_test "spec/ARB_draw_elements_base_vertex/draw-elements-base-vertex-neg" 0.0 "framework/../bin/draw-elements-base-vertex-neg -auto"
run_test "spec/ARB_draw_elements_base_vertex/draw-elements-base-vertex-user_varrays" 0.0 "framework/../bin/draw-elements-base-vertex -auto user_varrays"
run_test "spec/ARB_draw_elements_base_vertex/draw-elements-instanced-base-vertex" 0.0 "framework/../bin/draw-elements-instanced-base-vertex -auto"
run_test "spec/ARB_draw_elements_base_vertex/draw-elements-instanced-base-vertex-user_varrays" 0.0 "framework/../bin/draw-elements-instanced-base-vertex -auto user_varrays"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-disabled.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-disabled.frag fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-disabled.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-disabled.vert fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-enabled.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-enabled.frag fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/instanceidarb-enabled.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/compiler/instanceidarb-enabled.vert pass 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/compiler/negative-instanceidarb-write.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/compiler/negative-instanceidarb-write.vert fail 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/dlist" 0.0 "framework/../bin/arb_draw_instanced-dlist -auto -fbo"
run_test "spec/ARB_draw_instanced/draw-instanced" 0.0 "framework/../bin/draw-instanced -auto"
run_test "spec/ARB_draw_instanced/draw-instanced-divisor" 0.0 "framework/../bin/draw-instanced-divisor -auto"
run_test "spec/ARB_draw_instanced/draw-non-instanced" 0.0 "framework/../bin/shader_runner tests/spec/arb_draw_instanced/execution/draw-non-instanced.shader_test -auto"
run_test "spec/ARB_draw_instanced/elements" 0.0 "framework/../bin/arb_draw_instanced-elements -auto -fbo"
run_test "spec/ARB_draw_instanced/instance-array-dereference" 0.0 "framework/../bin/shader_runner tests/spec/arb_draw_instanced/execution/instance-array-dereference.shader_test -auto"
run_test "spec/ARB_draw_instanced/negative-arrays-first-negative" 0.0 "framework/../bin/arb_draw_instanced-negative-arrays-first-negative -auto -fbo"
run_test "spec/ARB_draw_instanced/negative-elements-type" 0.0 "framework/../bin/arb_draw_instanced-negative-elements-type -auto -fbo"
run_test "spec/ARB_draw_instanced/preprocessor/feature-macro-enabled.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/preprocessor/feature-macro-enabled.frag pass 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_draw_instanced/preprocessor/feature-macro-enabled.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_draw_instanced/preprocessor/feature-macro-enabled.vert pass 1.10 GL_ARB_draw_instanced"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/attribute-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/attribute-01.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-01.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-01.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-02.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-02.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-02.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-03.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-03.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/in-04.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/in-04.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-01.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-01.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-02.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-02.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-02.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-03.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-03.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-03.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-03.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-04.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-04.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-04.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-04.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-05.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-05.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-05.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-05.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-06.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-06.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-06.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-06.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-07.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-07.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-07.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-07.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-08.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-08.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-08.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-08.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-09.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-09.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-09.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-09.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-10.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-10.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-10.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-10.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-11.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-11.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/layout-11.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/layout-11.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-01.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-01.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-02.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-02.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-02.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-03.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-03.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/out-04.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/out-04.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/varying-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/varying-01.frag fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/compiler/varying-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/compiler/varying-01.vert fail 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/preprocessor/define.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/preprocessor/define.frag pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.10/preprocessor/define.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.10/preprocessor/define.vert pass 1.10 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/attribute-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/attribute-01.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-01.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-01.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-02.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-02.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-02.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-03.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-03.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-04.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-04.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/in-05.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/in-05.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/index-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/index-01.frag fail 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-01.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-01.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-02.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-02.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-02.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-03.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-03.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-03.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-03.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-04.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-04.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-04.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-04.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-05.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-05.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-05.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-05.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-06.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-06.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-06.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-06.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-07.frag" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-07.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-07.vert" 0.0 "framework/../bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-07.vert pass 1.20 GL_ARB_explicit_attrib_location"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 383 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

