#!/bin/bash


need_pass=357
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-04.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-04.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-05.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-05.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-05.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-05.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-06.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-06.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-06.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-06.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-07.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-07.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-07.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-07.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-08.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-08.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-08.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-08.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-09.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-09.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-09.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-09.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-10.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-10.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-10.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-10.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-11.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-11.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-11.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-11.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-12.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-12.frag fail 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-13.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-13.frag pass 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/layout-14.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/layout-14.frag fail 1.20 GL_ARB_explicit_attrib_location GL_ARB_blend_func_extended"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-01.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-01.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-02.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-02.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-03.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-03.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-04.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-04.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/out-05.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/out-05.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/varying-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/varying-01.frag fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/compiler/varying-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/compiler/varying-01.vert fail 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/preprocessor/define.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/preprocessor/define.frag pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.20/preprocessor/define.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.20/preprocessor/define.vert pass 1.20 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.30/preprocessor/define-130.frag" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.30/preprocessor/define-130.frag pass 1.30 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/1.30/preprocessor/define-130.vert" 0.0 "bin/glslparsertest tests/spec/arb_explicit_attrib_location/1.30/preprocessor/define-130.vert pass 1.30 GL_ARB_explicit_attrib_location"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-01" 0.0 "bin/glsl-explicit-location-01 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-02" 0.0 "bin/glsl-explicit-location-02 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-03" 0.0 "bin/glsl-explicit-location-03 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-04" 0.0 "bin/glsl-explicit-location-04 -auto"
run_test "spec/ARB_explicit_attrib_location/glsl-explicit-location-05" 0.0 "bin/glsl-explicit-location-05 -auto"
run_test "spec/ARB_fragment_coord_conventions/fp-arb-fragment-coord-conventions-integer" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-arb-fragment-coord-conventions-integer.vpfp"
run_test "spec/ARB_fragment_coord_conventions/fp-arb-fragment-coord-conventions-none" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-arb-fragment-coord-conventions-none.vpfp"
run_test "spec/ARB_fragment_program/dph" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/dph.shader_test -auto"
run_test "spec/ARB_fragment_program/fdo30337a" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fdo30337a.vpfp"
run_test "spec/ARB_fragment_program/fdo30337b" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fdo30337b.vpfp"
run_test "spec/ARB_fragment_program/fdo38145" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fdo38145.vpfp"
run_test "spec/ARB_fragment_program/fp-abs-01" 0.0 "bin/fp-abs-01 -auto"
run_test "spec/ARB_fragment_program/fp-cmp" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-cmp.vpfp"
run_test "spec/ARB_fragment_program/fp-dst-aliasing-1" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-dst-aliasing-1.vpfp"
run_test "spec/ARB_fragment_program/fp-dst-aliasing-2" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-dst-aliasing-2.vpfp"
run_test "spec/ARB_fragment_program/fp-ex2-sat" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-ex2-sat.vpfp"
run_test "spec/ARB_fragment_program/fp-fog" 0.0 "bin/fp-fog -auto"
run_test "spec/ARB_fragment_program/fp-formats" 0.0 "bin/fp-formats -auto"
run_test "spec/ARB_fragment_program/fp-fragment-position" 0.0 "bin/fp-fragment-position -auto"
run_test "spec/ARB_fragment_program/fp-incomplete-tex" 0.0 "bin/fp-incomplete-tex -auto"
run_test "spec/ARB_fragment_program/fp-indirections" 0.0 "bin/fp-indirections -auto"
run_test "spec/ARB_fragment_program/fp-indirections2" 0.0 "bin/fp-indirections2 -auto"
run_test "spec/ARB_fragment_program/fp-kil" 0.0 "bin/fp-kil -auto"
run_test "spec/ARB_fragment_program/fp-lit-mask" 0.0 "bin/fp-lit-mask -auto"
run_test "spec/ARB_fragment_program/fp-lit-src-equals-dst" 0.0 "bin/fp-lit-src-equals-dst -auto"
run_test "spec/ARB_fragment_program/fp-set-01" 0.0 "bin/fp-set-01 -auto"
run_test "spec/ARB_fragment_program/fp-two-constants" 0.0 "bin/vpfp-generic -auto tests/shaders/generic/fp-two-constants.vpfp"
run_test "spec/ARB_fragment_program/incomplete-texture-arb_fp" 0.0 "bin/incomplete-texture -auto arb_fp -auto -fbo"
run_test "spec/ARB_fragment_program/kil-swizzle" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/kil-swizzle.shader_test -auto"
run_test "spec/ARB_fragment_program/lrp_sat" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/lrp_sat.shader_test -auto"
run_test "spec/ARB_fragment_program/minmax" 0.0 "bin/arb_fragment_program-minmax -auto -fbo"
run_test "spec/ARB_fragment_program/texturing/tex-2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/texturing/tex-2d.shader_test -auto"
run_test "spec/ARB_fragment_program/texturing/txb-2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/texturing/txb-2d.shader_test -auto"
run_test "spec/ARB_fragment_program/texturing/txp-2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program/texturing/txp-2d.shader_test -auto"
run_test "spec/ARB_fragment_program/trinity-fp1" 0.0 "bin/trinity-fp1 -auto"
run_test "spec/ARB_fragment_program_shadow/masked" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/masked.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/tex-shadow1d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/tex-shadow1d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/tex-shadow2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/tex-shadow2d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/tex-shadow2drect" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/tex-shadow2drect.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/txp-shadow1d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/txp-shadow1d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/txp-shadow2d" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/txp-shadow2d.shader_test -auto"
run_test "spec/ARB_fragment_program_shadow/txp-shadow2drect" 0.0 "bin/shader_runner tests/spec/arb_fragment_program_shadow/txp-shadow2drect.shader_test -auto"
run_test "spec/ARB_framebuffer_object/FBO blit from missing attachment" 0.0 "bin/fbo-missing-attachment-blit -auto from"
run_test "spec/ARB_framebuffer_object/FBO blit to missing attachment" 0.0 "bin/fbo-missing-attachment-blit -auto to"
run_test "spec/ARB_framebuffer_object/fbo-alpha" 0.0 "bin/fbo-alpha -auto"
run_test "spec/ARB_framebuffer_object/fbo-deriv" 0.0 "bin/fbo-deriv -auto"
run_test "spec/ARB_framebuffer_object/fbo-getframebufferattachmentparameter-01" 0.0 "bin/fbo-getframebufferattachmentparameter-01 -auto"
run_test "spec/ARB_framebuffer_object/fbo-gl_pointcoord" 0.0 "bin/fbo-gl_pointcoord -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-01" 0.0 "bin/fbo-incomplete-texture-01 -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-02" 0.0 "bin/fbo-incomplete-texture-02 -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-03" 0.0 "bin/fbo-incomplete-texture-03 -auto"
run_test "spec/ARB_framebuffer_object/fbo-incomplete-texture-04" 0.0 "bin/fbo-incomplete-texture-04 -auto"
run_test "spec/ARB_framebuffer_object/fbo-mipmap-copypix" 0.0 "bin/fbo-mipmap-copypix -auto -fbo"
run_test "spec/ARB_framebuffer_object/fbo-scissor-blit fbo" 0.0 "bin/fbo-scissor-blit fbo -auto"
run_test "spec/ARB_framebuffer_object/fbo-scissor-blit window" 0.0 "bin/fbo-scissor-blit window -auto"
run_test "spec/ARB_framebuffer_object/fbo-viewport" 0.0 "bin/fbo-viewport -auto"
run_test "spec/ARB_framebuffer_object/fdo28551" 0.0 "bin/fdo28551 -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels draw depth" 0.0 "bin/framebuffer-blit-levels draw depth -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels draw rgba" 0.0 "bin/framebuffer-blit-levels draw rgba -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels draw stencil" 0.0 "bin/framebuffer-blit-levels draw stencil -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels read depth" 0.0 "bin/framebuffer-blit-levels read depth -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels read rgba" 0.0 "bin/framebuffer-blit-levels read rgba -auto"
run_test "spec/ARB_framebuffer_object/framebuffer-blit-levels read stencil" 0.0 "bin/framebuffer-blit-levels read stencil -auto"
run_test "spec/ARB_framebuffer_object/same-attachment-glFramebufferRenderbuffer-GL_DEPTH_STENCIL_ATTACHMENT" 0.0 "bin/same-attachment-glFramebufferRenderbuffer-GL_DEPTH_STENCIL_ATTACHMENT -auto -fbo"
run_test "spec/ARB_framebuffer_object/same-attachment-glFramebufferTexture2D-GL_DEPTH_STENCIL_ATTACHMENT" 0.0 "bin/same-attachment-glFramebufferTexture2D-GL_DEPTH_STENCIL_ATTACHMENT -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer linear_to_srgb upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer linear_to_srgb upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit renderbuffer srgb_to_linear upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit renderbuffer srgb_to_linear upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture linear_to_srgb upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture linear_to_srgb upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear downsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear downsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear downsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear downsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear msaa disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear msaa disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear msaa enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear msaa enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear scaled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear scaled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear scaled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear scaled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear single_sampled disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear single_sampled disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear single_sampled enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear single_sampled enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear upsample disabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear upsample disabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/blit texture srgb_to_linear upsample enabled" 0.0 "bin/arb_framebuffer_srgb-blit texture srgb_to_linear upsample enabled -auto -fbo"
run_test "spec/ARB_framebuffer_sRGB/framebuffer-srgb" 0.0 "bin/framebuffer-srgb -auto"
run_test "spec/ARB_half_float_vertex/draw-vertices-half-float" 0.0 "bin/draw-vertices-half-float -auto"
run_test "spec/ARB_half_float_vertex/draw-vertices-half-float-user" 0.0 "bin/draw-vertices-half-float -auto user"
run_test "spec/ARB_instanced_arrays/instanced_arrays" 0.0 "bin/instanced_arrays -auto"
run_test "spec/ARB_instanced_arrays/instanced_arrays-vbo" 0.0 "bin/instanced_arrays vbo -auto"
run_test "spec/ARB_internalformat_query/buffer over-run checks" 0.0 "bin/arb_internalformat_query-overrun -auto -fbo"
run_test "spec/ARB_internalformat_query/minmax" 0.0 "bin/arb_internalformat_query-minmax -auto -fbo"
run_test "spec/ARB_map_buffer_range/MAP_INVALIDATE_BUFFER_BIT decrement-offset" 0.0 "bin/map_buffer_range-invalidate MAP_INVALIDATE_BUFFER_BIT decrement-offset -auto -fbo"
run_test "spec/ARB_map_buffer_range/MAP_INVALIDATE_BUFFER_BIT increment-offset" 0.0 "bin/map_buffer_range-invalidate MAP_INVALIDATE_BUFFER_BIT increment-offset -auto -fbo"
run_test "spec/ARB_map_buffer_range/MAP_INVALIDATE_BUFFER_BIT offset=0" 0.0 "bin/map_buffer_range-invalidate MAP_INVALIDATE_BUFFER_BIT offset=0 -auto -fbo"
run_test "spec/ARB_map_buffer_range/MAP_INVALIDATE_RANGE_BIT decrement-offset" 0.0 "bin/map_buffer_range-invalidate MAP_INVALIDATE_RANGE_BIT decrement-offset -auto -fbo"
run_test "spec/ARB_map_buffer_range/MAP_INVALIDATE_RANGE_BIT increment-offset" 0.0 "bin/map_buffer_range-invalidate MAP_INVALIDATE_RANGE_BIT increment-offset -auto -fbo"
run_test "spec/ARB_map_buffer_range/MAP_INVALIDATE_RANGE_BIT offset=0" 0.0 "bin/map_buffer_range-invalidate MAP_INVALIDATE_RANGE_BIT offset=0 -auto -fbo"
run_test "spec/ARB_map_buffer_range/map_buffer_range_error_check" 0.0 "bin/map_buffer_range_error_check -auto"
run_test "spec/ARB_map_buffer_range/map_buffer_range_test" 0.0 "bin/map_buffer_range_test -auto"
run_test "spec/ARB_multisample/beginend" 0.0 "bin/arb_multisample-beginend -auto -fbo"
run_test "spec/ARB_multisample/pushpop" 0.0 "bin/arb_multisample-pushpop -auto -fbo"
run_test "spec/ARB_occlusion_query/occlusion_query_lifetime" 0.0 "bin/occlusion_query_lifetime -auto -fbo"
run_test "spec/ARB_occlusion_query/occlusion_query_meta_no_fragments" 0.0 "bin/occlusion_query_meta_no_fragments -auto -fbo"
run_test "spec/ARB_occlusion_query/occlusion_query_order" 0.0 "bin/occlusion_query_order -auto -fbo"
run_test "spec/ARB_occlusion_query2/api" 0.0 "bin/arb_occlusion_query2-api -auto -fbo"
run_test "spec/ARB_pixel_buffer_object/fbo-pbo-readpixels-small" 0.0 "bin/fbo-pbo-readpixels-small -auto"
run_test "spec/ARB_pixel_buffer_object/pbo-drawpixels" 0.0 "bin/pbo-drawpixels -auto"
run_test "spec/ARB_pixel_buffer_object/pbo-read-argb8888" 0.0 "bin/pbo-read-argb8888 -auto"
run_test "spec/ARB_pixel_buffer_object/pbo-readpixels-small" 0.0 "bin/pbo-readpixels-small -auto"
run_test "spec/ARB_pixel_buffer_object/pbo-teximage" 0.0 "bin/pbo-teximage -auto"
run_test "spec/ARB_pixel_buffer_object/pbo-teximage-tiling" 0.0 "bin/pbo-teximage-tiling -auto"
run_test "spec/ARB_pixel_buffer_object/pbo-teximage-tiling-2" 0.0 "bin/pbo-teximage-tiling-2 -auto"
run_test "spec/ARB_point_sprite/point-sprite" 0.0 "bin/point-sprite -auto"
run_test "spec/ARB_robustness/arb_robustness_client-mem-bounds" 0.0 "bin/arb_robustness_client-mem-bounds -auto"
run_test "spec/ARB_sampler_objects/GL_EXT_texture_sRGB_decode" 0.0 "bin/arb_sampler_objects-srgb-decode -auto -fbo"
run_test "spec/ARB_sampler_objects/framebufferblit" 0.0 "bin/arb_sampler_objects-framebufferblit -auto"
run_test "spec/ARB_sampler_objects/sampler-incomplete" 0.0 "bin/arb_sampler_objects-sampler-incomplete -auto -fbo"
run_test "spec/ARB_sampler_objects/sampler-objects" 0.0 "bin/arb_sampler_objects-sampler-objects -auto -fbo"
run_test "spec/ARB_seamless_cube_map/arb_seamless_cubemap" 0.0 "bin/arb_seamless_cubemap -auto"
run_test "spec/ARB_shader_objects/bindattriblocation-scratch-name" 0.0 "bin/arb_shader_objects-bindattriblocation-scratch-name -auto -fbo"
run_test "spec/ARB_shader_objects/clear-with-deleted" 0.0 "bin/arb_shader_objects-clear-with-deleted -auto -fbo"
run_test "spec/ARB_shader_objects/delete-repeat" 0.0 "bin/arb_shader_objects-delete-repeat -auto -fbo"
run_test "spec/ARB_shader_objects/getactiveuniform-beginend" 0.0 "bin/arb_shader_objects-getactiveuniform-beginend -auto -fbo"
run_test "spec/ARB_shader_objects/getuniform" 0.0 "bin/arb_shader_objects-getuniform -auto"
run_test "spec/ARB_shader_objects/getuniformlocation-array-of-struct-of-array" 0.0 "bin/arb_shader_objects-getuniformlocation-array-of-struct-of-array -auto -fbo"
run_test "spec/ARB_shader_stencil_export/amd-undefined.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_stencil_export/amd-undefined.frag fail 1.20"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-01.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-02.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-03.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-03.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-04.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-04.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-05.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-05.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-06.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-06.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-07.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-07.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-08.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-08.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-09.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-09.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-10.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-10.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-11.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-11.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-12.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-12.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-13.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-13.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-14.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-14.frag pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-15.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-15.frag pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-16.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-16.frag pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-17.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-17.frag pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-18.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-18.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-19.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-19.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-20.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-20.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-21.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-21.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-22.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-22.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-23.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-23.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-24.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-24.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-25.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-25.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-26.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-26.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-27.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-27.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-28.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-28.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-29.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-29.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-30.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-30.vert pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-31.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-31.vert pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-32.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-32.vert pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-33.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-33.vert pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_grad-34.vert" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_grad-34.vert pass 1.10 GL_ARB_shader_texture_lod GL_ARB_texture_rectangle"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-01.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-02.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-03.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-03.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-04.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-04.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-05.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-05.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-06.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-06.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-07.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-07.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-08.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-08.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-09.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-09.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-10.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-10.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-11.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-11.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-12.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-12.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/compiler/tex_lod-13.frag" 0.0 "bin/glslparsertest tests/spec/arb_shader_texture_lod/compiler/tex_lod-13.frag pass 1.10 GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/execution/arb_shader_texture_lod-texgrad" 0.0 "bin/arb_shader_texture_lod-texgrad -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-01" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-01.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-02" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-02.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-03" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-03.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-04" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-04.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-05" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-05.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-06" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-06.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-07" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-07.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-08" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-08.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-09" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-09.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-cumulative" 0.0 "bin/shader_runner tests/spec/arb_shader_texture_lod/execution/glsl-fs-shadow2DGradARB-cumulative.shader_test -auto"
run_test "spec/ARB_shader_texture_lod/execution/tex-miplevel-selection-texture2DLod" 0.0 "bin/tex-miplevel-selection -auto -nobias -nolod -GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/execution/tex-miplevel-selection-texture2DLod-lod" 0.0 "bin/tex-miplevel-selection -auto -nobias -GL_ARB_shader_texture_lod"
run_test "spec/ARB_shader_texture_lod/execution/tex-miplevel-selection-texture2DLod-lod-bias" 0.0 "bin/tex-miplevel-selection -auto -GL_ARB_shader_texture_lod"
run_test "spec/ARB_sync/sync_api" 0.0 "bin/sync_api -auto"
run_test "spec/ARB_sync/timeout-zero" 0.0 "bin/arb_sync-timeout-zero -auto -fbo"
run_test "spec/ARB_texture_compression/GL_TEXTURE_INTERNAL_FORMAT query" 0.0 "bin/arb_texture_compression-internal-format-query -auto"
run_test "spec/ARB_texture_compression/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_ARB_texture_compression"
run_test "spec/ARB_texture_compression/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_compression"
run_test "spec/ARB_texture_compression/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_compression bordercolor"
run_test "spec/ARB_texture_compression/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_compression bordercolor swizzled"
run_test "spec/ARB_texture_compression/unknown formats" 0.0 "bin/arb_texture_compression-invalid-formats unknown"
run_test "spec/ARB_texture_compression_bptc/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats bptc"
run_test "spec/ARB_texture_cube_map/crash-cubemap-order" 0.0 "bin/crash-cubemap-order -auto"
run_test "spec/ARB_texture_cube_map/cubemap" 0.0 "bin/cubemap -auto"
run_test "spec/ARB_texture_cube_map/cubemap npot" 0.0 "bin/cubemap -auto npot"
run_test "spec/ARB_texture_cube_map/cubemap-shader" 0.0 "bin/cubemap-shader -auto"
run_test "spec/ARB_texture_cube_map/cubemap-shader bias" 0.0 "bin/cubemap-shader -auto bias"
run_test "spec/ARB_texture_cube_map/cubemap-shader lod" 0.0 "bin/cubemap-shader -auto lod"
run_test "spec/ARB_texture_cube_map/getteximage-targets CUBE" 0.0 "bin/getteximage-targets CUBE -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/arb_texture_cube_map_array-cubemap" 0.0 "bin/arb_texture_cube_map_array-cubemap -auto"
run_test "spec/ARB_texture_cube_map_array/arb_texture_cube_map_array-cubemap-lod" 0.0 "bin/arb_texture_cube_map_array-cubemap-lod -auto"
run_test "spec/ARB_texture_cube_map_array/arb_texture_cube_map_array-fbo-cubemap-array" 0.0 "bin/arb_texture_cube_map_array-fbo-cubemap-array -auto"
run_test "spec/ARB_texture_cube_map_array/arb_texture_cube_map_array-get" 0.0 "bin/arb_texture_cube_map_array-get -auto"
run_test "spec/ARB_texture_cube_map_array/arb_texture_cube_map_array-sampler-cube-array-shadow" 0.0 "bin/arb_texture_cube_map_array-sampler-cube-array-shadow -auto"
run_test "spec/ARB_texture_cube_map_array/arb_texture_cube_map_array-teximage3d-invalid-values" 0.0 "bin/arb_texture_cube_map_array-teximage3d-invalid-values -auto"
run_test "spec/ARB_texture_cube_map_array/compiler/tex-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex-01.frag pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex-01.vert pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex-02.frag" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex-02.frag pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex-02.vert" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex-02.vert pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex_bias-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex_bias-01.frag pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex_grad-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex_grad-01.frag pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex_grad-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex_grad-01.vert pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex_lod-01.frag" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex_lod-01.frag pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/compiler/tex_lod-01.vert" 0.0 "bin/glslparsertest tests/spec/arb_texture_cube_map_array/compiler/tex_lod-01.vert pass 1.30 GL_ARB_texture_cube_map_array"
run_test "spec/ARB_texture_cube_map_array/getteximage-targets CUBE_ARRAY" 0.0 "bin/getteximage-targets CUBE_ARRAY -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/fs-textureSize-isamplerCubeArray" 0.0 "bin/textureSize fs isamplerCubeArray -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/fs-textureSize-samplerCubeArray" 0.0 "bin/textureSize fs samplerCubeArray -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/fs-textureSize-samplerCubeArrayShadow" 0.0 "bin/textureSize fs samplerCubeArrayShadow -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/fs-textureSize-usamplerCubeArray" 0.0 "bin/textureSize fs usamplerCubeArray -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/vs-textureSize-isamplerCubeArray" 0.0 "bin/textureSize vs isamplerCubeArray -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/vs-textureSize-samplerCubeArray" 0.0 "bin/textureSize vs samplerCubeArray -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/vs-textureSize-samplerCubeArrayShadow" 0.0 "bin/textureSize vs samplerCubeArrayShadow -auto -fbo"
run_test "spec/ARB_texture_cube_map_array/textureSize/vs-textureSize-usamplerCubeArray" 0.0 "bin/textureSize vs usamplerCubeArray -auto -fbo"
run_test "spec/ARB_texture_env_crossbar/crossbar" 0.0 "bin/crossbar -auto"
run_test "spec/ARB_texture_float/arb_texture_float-texture-float-formats" 0.0 "bin/arb_texture_float-texture-float-formats -auto"
run_test "spec/ARB_texture_float/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto GL_ARB_texture_float"
run_test "spec/ARB_texture_float/fbo-blending-formats" 0.0 "bin/fbo-blending-formats -auto GL_ARB_texture_float"
run_test "spec/ARB_texture_float/fbo-clear-formats" 0.0 "bin/fbo-clear-formats -auto GL_ARB_texture_float"
run_test "spec/ARB_texture_float/fbo-colormask-formats" 0.0 "bin/fbo-colormask-formats -auto GL_ARB_texture_float"
run_test "spec/ARB_texture_float/fbo-generatemipmap-formats" 0.0 "bin/fbo-generatemipmap-formats -auto GL_ARB_texture_float"
run_test "spec/ARB_texture_float/get-renderbuffer-internalformat" 0.0 "bin/get-renderbuffer-internalformat GL_ARB_texture_float -auto -fbo"
run_test "spec/ARB_texture_float/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_float"
run_test "spec/ARB_texture_float/texwrap formats bordercolor" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_float bordercolor"
run_test "spec/ARB_texture_float/texwrap formats bordercolor-swizzled" 0.0 "bin/texwrap -fbo -auto GL_ARB_texture_float bordercolor swizzled"
run_test "spec/ARB_texture_rectangle/1-1-linear-texture" 0.0 "bin/1-1-linear-texture -auto -fbo"
run_test "spec/ARB_texture_rectangle/getteximage-targets RECT" 0.0 "bin/getteximage-targets RECT -auto -fbo"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-01" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-01.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-02" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-02.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-03" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-03.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-04" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-04.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-05" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-05.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-06" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-06.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-07" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-07.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-08" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-08.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRect-09" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRect-09.shader_test -auto"
run_test "spec/ARB_texture_rectangle/glsl-fs-shadow2DRectProj" 0.0 "bin/shader_runner tests/spec/arb_texture_rectangle/glsl-fs-shadow2DRectProj.shader_test -auto"
run_test "spec/ARB_texture_rectangle/texrect-many" 0.0 "bin/texrect-many -auto"
run_test "spec/ARB_texture_rectangle/texwrap RECT" 0.0 "bin/texwrap -fbo -auto RECT GL_RGBA8"
run_test "spec/ARB_texture_rectangle/texwrap RECT bordercolor" 0.0 "bin/texwrap -fbo -auto RECT GL_RGBA8 bordercolor"
run_test "spec/ARB_texture_rectangle/texwrap RECT proj" 0.0 "bin/texwrap -fbo -auto RECT GL_RGBA8 proj"
run_test "spec/ARB_texture_rectangle/texwrap RECT proj bordercolor" 0.0 "bin/texwrap -fbo -auto RECT GL_RGBA8 proj bordercolor"
run_test "spec/ARB_texture_rg/depth-tex-modes-rg" 0.0 "bin/depth-tex-modes-rg -auto"
run_test "spec/ARB_texture_rg/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto GL_ARB_texture_rg"
run_test "spec/ARB_texture_rg/fbo-alphatest-formats-float" 0.0 "bin/fbo-alphatest-formats -auto GL_ARB_texture_rg-float"
run_test "spec/ARB_texture_rg/fbo-blending-formats" 0.0 "bin/fbo-blending-formats -auto GL_ARB_texture_rg"
run_test "spec/ARB_texture_rg/fbo-blending-formats-float" 0.0 "bin/fbo-blending-formats -auto GL_ARB_texture_rg-float"
run_test "spec/ARB_texture_rg/fbo-clear-formats" 0.0 "bin/fbo-clear-formats -auto GL_ARB_texture_rg"
run_test "spec/ARB_texture_rg/fbo-clear-formats-float" 0.0 "bin/fbo-clear-formats -auto GL_ARB_texture_rg-float"
run_test "spec/ARB_texture_rg/fbo-colormask-formats" 0.0 "bin/fbo-colormask-formats -auto GL_ARB_texture_rg"
run_test "spec/ARB_texture_rg/fbo-colormask-formats-float" 0.0 "bin/fbo-colormask-formats -auto GL_ARB_texture_rg-float"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 357 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

