#!/bin/bash


need_pass=404
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
  else
    let "failures++"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.30/execution/built-in-functions/vs-tanh-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-tanh-float.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-tanh-vec2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-tanh-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-tanh-vec3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-tanh-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-tanh-vec4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-tanh-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-trunc-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-trunc-float.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-trunc-vec2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-trunc-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-trunc-vec3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-trunc-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/built-in-functions/vs-trunc-vec4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/built-in-functions/vs-trunc-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/clip-plane-transformation pos" 0.0 "framework/../bin/clip-plane-transformation pos -auto -fbo"
run_test "spec/glsl-1.30/execution/clipping/fs-clip-distance-explicitly-sized" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/fs-clip-distance-explicitly-sized.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/fs-clip-distance-interpolated" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/fs-clip-distance-interpolated.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/fs-clip-distance-sizeable-to-max" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/fs-clip-distance-sizeable-to-max.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/max-clip-distances" 0.0 "framework/../bin/max-clip-distances -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-based-on-position" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-based-on-position.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-based-on-position-homogeneity" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-based-on-position-homogeneity.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-all-planes-enabled" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-all-planes-enabled.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-bulk-assign" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-bulk-assign.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-const-accept" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-const-accept.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-const-reject" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-const-reject.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-enables" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-enables.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-explicitly-sized" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-explicitly-sized.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-implicitly-sized" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-implicitly-sized.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-in-param" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-in-param.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-inout-param" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-inout-param.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-out-param" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-out-param.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-retval" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-retval.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-sizeable-to-max" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-sizeable-to-max.shader_test -auto"
run_test "spec/glsl-1.30/execution/clipping/vs-clip-distance-uint-index" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/clipping/vs-clip-distance-uint-index.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-decrement-int" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-decrement-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-decrement-uint" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-decrement-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-discard-exit-3" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-discard-exit-3.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-execution-ordering" 0.0 "framework/../bin/fs-execution-ordering -auto -fbo"
run_test "spec/glsl-1.30/execution/fs-float-uint-conversion" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-float-uint-conversion.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-increment-int" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-increment-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-increment-uint" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-increment-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-isinf-vec2" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-isinf-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-isinf-vec3" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-isinf-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-isinf-vec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-isinf-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-isnan-vec2" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-isnan-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-isnan-vec3" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-isnan-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-isnan-vec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-isnan-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-mix-bvec4-infnan" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-mix-bvec4-infnan.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-multiply-const-ivec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-multiply-const-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-multiply-const-uvec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-multiply-const-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-multiply-ivec4-const" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-multiply-ivec4-const.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-multiply-uvec4-const" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-multiply-uvec4-const.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texelFetch-2D" 0.0 "framework/../bin/fs-texelFetch-2D -auto"
run_test "spec/glsl-1.30/execution/fs-texelFetchOffset-2D" 0.0 "framework/../bin/fs-texelFetchOffset-2D -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-01" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-01.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-02" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-02.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-03" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-03.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-04" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-04.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-05" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-05.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-06" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-06.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-07" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-07.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-08" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-08.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-09" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-09.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-10" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-10.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-11" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-11.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-texture-sampler2dshadow-12" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-texture-sampler2dshadow-12.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-textureGrad-miplevels" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-textureGrad-miplevels.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-textureLod-miplevels" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-textureLod-miplevels.shader_test -auto"
run_test "spec/glsl-1.30/execution/fs-textureSize-compare" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/fs-textureSize-compare.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/fs-int-interpolation" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/interpolation/fs-int-interpolation.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/fs-uint-interpolation" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/interpolation/fs-uint-interpolation.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_BackSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-gl_FrontSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-flat-other-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-mixed" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/interpolation/interpolation-mixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_BackSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-gl_FrontSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-other-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-other-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-none-other-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-none-other-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_BackSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-gl_FrontSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-noperspective-other-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_BackSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-gl_FrontSecondaryColor-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-flat-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-distance" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-distance.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-fixed" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-fixed.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-none" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-none.shader_test -auto"
run_test "spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-vertex" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/interpolation/interpolation-smooth-other-smooth-vertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/isinf-and-isnan fs_basic" 0.0 "framework/../bin/isinf-and-isnan fs_basic -auto"
run_test "spec/glsl-1.30/execution/isinf-and-isnan fs_fbo" 0.0 "framework/../bin/isinf-and-isnan fs_fbo -auto"
run_test "spec/glsl-1.30/execution/isinf-and-isnan vs_basic" 0.0 "framework/../bin/isinf-and-isnan vs_basic -auto"
run_test "spec/glsl-1.30/execution/isinf-and-isnan vs_fbo" 0.0 "framework/../bin/isinf-and-isnan vs_fbo -auto"
run_test "spec/glsl-1.30/execution/isinf-and-isnan vs_xfb" 0.0 "framework/../bin/isinf-and-isnan vs_xfb -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxClipDistances" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxClipDistances.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxClipPlanes" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxClipPlanes.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxCombinedTextureImageUnits" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxCombinedTextureImageUnits.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxDrawBuffers" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxDrawBuffers.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxFragmentUniformComponents" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxFragmentUniformComponents.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxTextureCoords" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxTextureCoords.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxTextureImageUnits" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxTextureImageUnits.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxTextureUnits" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxTextureUnits.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxVaryingComponents" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxVaryingComponents.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxVaryingFloats" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxVaryingFloats.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxVertexAttribs" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxVertexAttribs.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxVertexTextureImageUnits" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxVertexTextureImageUnits.shader_test -auto"
run_test "spec/glsl-1.30/execution/maximums/gl_MaxVertexUniformComponents" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/maximums/gl_MaxVertexUniformComponents.shader_test -auto"
run_test "spec/glsl-1.30/execution/qualifiers/vs-out-conversion-ivec4-to-vec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/qualifiers/vs-out-conversion-ivec4-to-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/fs-fallthrough" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/fs-fallthrough.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/fs-perpixel" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/fs-perpixel.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/fs-uint" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/fs-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/fs-uniform" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/fs-uniform.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/fs-uniform-nested" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/fs-uniform-nested.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/vs-pervertex" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/vs-pervertex.shader_test -auto"
run_test "spec/glsl-1.30/execution/switch/vs-uniform" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/switch/vs-uniform.shader_test -auto"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-isampler1D" 0.0 "framework/../bin/texelFetch fs isampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-isampler1DArray" 0.0 "framework/../bin/texelFetch fs isampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-isampler2D" 0.0 "framework/../bin/texelFetch fs isampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-isampler2DArray" 0.0 "framework/../bin/texelFetch fs isampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-isampler2DArray-swizzle" 0.0 "framework/../bin/texelFetch fs isampler2DArray b0r1 -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-isampler3D" 0.0 "framework/../bin/texelFetch fs isampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-sampler1D" 0.0 "framework/../bin/texelFetch fs sampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-sampler1DArray" 0.0 "framework/../bin/texelFetch fs sampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-sampler2D" 0.0 "framework/../bin/texelFetch fs sampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-sampler2DArray" 0.0 "framework/../bin/texelFetch fs sampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-sampler2DArray-swizzle" 0.0 "framework/../bin/texelFetch fs sampler2DArray b0r1 -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-sampler3D" 0.0 "framework/../bin/texelFetch fs sampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-usampler1D" 0.0 "framework/../bin/texelFetch fs usampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-usampler1DArray" 0.0 "framework/../bin/texelFetch fs usampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-usampler2D" 0.0 "framework/../bin/texelFetch fs usampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-usampler2DArray" 0.0 "framework/../bin/texelFetch fs usampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-usampler2DArray-swizzle" 0.0 "framework/../bin/texelFetch fs usampler2DArray b0r1 -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/fs-texelFetch-usampler3D" 0.0 "framework/../bin/texelFetch fs usampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-isampler1D" 0.0 "framework/../bin/texelFetch vs isampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-isampler1DArray" 0.0 "framework/../bin/texelFetch vs isampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-isampler2D" 0.0 "framework/../bin/texelFetch vs isampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-isampler2DArray" 0.0 "framework/../bin/texelFetch vs isampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-isampler2DArray-swizzle" 0.0 "framework/../bin/texelFetch vs isampler2DArray b0r1 -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-isampler3D" 0.0 "framework/../bin/texelFetch vs isampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-sampler1D" 0.0 "framework/../bin/texelFetch vs sampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-sampler1DArray" 0.0 "framework/../bin/texelFetch vs sampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-sampler2D" 0.0 "framework/../bin/texelFetch vs sampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-sampler2DArray" 0.0 "framework/../bin/texelFetch vs sampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-sampler2DArray-swizzle" 0.0 "framework/../bin/texelFetch vs sampler2DArray b0r1 -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-sampler3D" 0.0 "framework/../bin/texelFetch vs sampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-usampler1D" 0.0 "framework/../bin/texelFetch vs usampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-usampler1DArray" 0.0 "framework/../bin/texelFetch vs usampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-usampler2D" 0.0 "framework/../bin/texelFetch vs usampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-usampler2DArray" 0.0 "framework/../bin/texelFetch vs usampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-usampler2DArray-swizzle" 0.0 "framework/../bin/texelFetch vs usampler2DArray b0r1 -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetch/vs-texelFetch-usampler3D" 0.0 "framework/../bin/texelFetch vs usampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-isampler1D" 0.0 "framework/../bin/texelFetch offset fs isampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-isampler1DArray" 0.0 "framework/../bin/texelFetch offset fs isampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-isampler2D" 0.0 "framework/../bin/texelFetch offset fs isampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-isampler2DArray" 0.0 "framework/../bin/texelFetch offset fs isampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-isampler3D" 0.0 "framework/../bin/texelFetch offset fs isampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-sampler1D" 0.0 "framework/../bin/texelFetch offset fs sampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-sampler1DArray" 0.0 "framework/../bin/texelFetch offset fs sampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-sampler2D" 0.0 "framework/../bin/texelFetch offset fs sampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-sampler2DArray" 0.0 "framework/../bin/texelFetch offset fs sampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-sampler3D" 0.0 "framework/../bin/texelFetch offset fs sampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-usampler1D" 0.0 "framework/../bin/texelFetch offset fs usampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-usampler1DArray" 0.0 "framework/../bin/texelFetch offset fs usampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-usampler2D" 0.0 "framework/../bin/texelFetch offset fs usampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-usampler2DArray" 0.0 "framework/../bin/texelFetch offset fs usampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/fs-usampler3D" 0.0 "framework/../bin/texelFetch offset fs usampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-isampler1D" 0.0 "framework/../bin/texelFetch offset vs isampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-isampler1DArray" 0.0 "framework/../bin/texelFetch offset vs isampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-isampler2D" 0.0 "framework/../bin/texelFetch offset vs isampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-isampler2DArray" 0.0 "framework/../bin/texelFetch offset vs isampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-isampler3D" 0.0 "framework/../bin/texelFetch offset vs isampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-sampler1D" 0.0 "framework/../bin/texelFetch offset vs sampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-sampler1DArray" 0.0 "framework/../bin/texelFetch offset vs sampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-sampler2D" 0.0 "framework/../bin/texelFetch offset vs sampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-sampler2DArray" 0.0 "framework/../bin/texelFetch offset vs sampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-sampler3D" 0.0 "framework/../bin/texelFetch offset vs sampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-usampler1D" 0.0 "framework/../bin/texelFetch offset vs usampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-usampler1DArray" 0.0 "framework/../bin/texelFetch offset vs usampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-usampler2D" 0.0 "framework/../bin/texelFetch offset vs usampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-usampler2DArray" 0.0 "framework/../bin/texelFetch offset vs usampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/texelFetchOffset/vs-usampler3D" 0.0 "framework/../bin/texelFetch offset vs usampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-isampler1D" 0.0 "framework/../bin/textureSize fs isampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-isampler1DArray" 0.0 "framework/../bin/textureSize fs isampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-isampler2D" 0.0 "framework/../bin/textureSize fs isampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-isampler2DArray" 0.0 "framework/../bin/textureSize fs isampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-isampler3D" 0.0 "framework/../bin/textureSize fs isampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-isamplerCube" 0.0 "framework/../bin/textureSize fs isamplerCube -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler1D" 0.0 "framework/../bin/textureSize fs sampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler1DArray" 0.0 "framework/../bin/textureSize fs sampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler1DArrayShadow" 0.0 "framework/../bin/textureSize fs sampler1DArrayShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler1DShadow" 0.0 "framework/../bin/textureSize fs sampler1DShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler2D" 0.0 "framework/../bin/textureSize fs sampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler2DArray" 0.0 "framework/../bin/textureSize fs sampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler2DArrayShadow" 0.0 "framework/../bin/textureSize fs sampler2DArrayShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler2DShadow" 0.0 "framework/../bin/textureSize fs sampler2DShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-sampler3D" 0.0 "framework/../bin/textureSize fs sampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-samplerCube" 0.0 "framework/../bin/textureSize fs samplerCube -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-samplerCubeShadow" 0.0 "framework/../bin/textureSize fs samplerCubeShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-usampler1D" 0.0 "framework/../bin/textureSize fs usampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-usampler1DArray" 0.0 "framework/../bin/textureSize fs usampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-usampler2D" 0.0 "framework/../bin/textureSize fs usampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-usampler2DArray" 0.0 "framework/../bin/textureSize fs usampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-usampler3D" 0.0 "framework/../bin/textureSize fs usampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/fs-textureSize-usamplerCube" 0.0 "framework/../bin/textureSize fs usamplerCube -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-isampler1D" 0.0 "framework/../bin/textureSize vs isampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-isampler1DArray" 0.0 "framework/../bin/textureSize vs isampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-isampler2D" 0.0 "framework/../bin/textureSize vs isampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-isampler2DArray" 0.0 "framework/../bin/textureSize vs isampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-isampler3D" 0.0 "framework/../bin/textureSize vs isampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-isamplerCube" 0.0 "framework/../bin/textureSize vs isamplerCube -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler1D" 0.0 "framework/../bin/textureSize vs sampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler1DArray" 0.0 "framework/../bin/textureSize vs sampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler1DArrayShadow" 0.0 "framework/../bin/textureSize vs sampler1DArrayShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler1DShadow" 0.0 "framework/../bin/textureSize vs sampler1DShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler2D" 0.0 "framework/../bin/textureSize vs sampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler2DArray" 0.0 "framework/../bin/textureSize vs sampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler2DArrayShadow" 0.0 "framework/../bin/textureSize vs sampler2DArrayShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler2DShadow" 0.0 "framework/../bin/textureSize vs sampler2DShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-sampler3D" 0.0 "framework/../bin/textureSize vs sampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-samplerCube" 0.0 "framework/../bin/textureSize vs samplerCube -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-samplerCubeShadow" 0.0 "framework/../bin/textureSize vs samplerCubeShadow -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-usampler1D" 0.0 "framework/../bin/textureSize vs usampler1D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-usampler1DArray" 0.0 "framework/../bin/textureSize vs usampler1DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-usampler2D" 0.0 "framework/../bin/textureSize vs usampler2D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-usampler2DArray" 0.0 "framework/../bin/textureSize vs usampler2DArray -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-usampler3D" 0.0 "framework/../bin/textureSize vs usampler3D -auto -fbo"
run_test "spec/glsl-1.30/execution/textureSize/vs-textureSize-usamplerCube" 0.0 "framework/../bin/textureSize vs usamplerCube -auto -fbo"
run_test "spec/glsl-1.30/execution/uniform-initializer/fs-uint" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/fs-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/fs-uint-array" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/fs-uint-array.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/fs-uint-from-const" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/fs-uint-from-const.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/fs-uint-set-by-API" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/fs-uint-set-by-API.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/fs-uint-set-by-other-stage" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/fs-uint-set-by-other-stage.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/vs-uint" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/vs-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/vs-uint-array" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/vs-uint-array.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/vs-uint-from-const" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/vs-uint-from-const.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/vs-uint-set-by-API" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/vs-uint-set-by-API.shader_test -auto"
run_test "spec/glsl-1.30/execution/uniform-initializer/vs-uint-set-by-other-stage" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.30/execution/uniform-initializer/vs-uint-set-by-other-stage.shader_test -auto"
run_test "spec/glsl-1.30/execution/vertexid-beginend" 0.0 "framework/../bin/vertexid-beginend -auto -fbo"
run_test "spec/glsl-1.30/execution/vertexid-drawarrays" 0.0 "framework/../bin/vertexid-drawarrays -auto -fbo"
run_test "spec/glsl-1.30/execution/vertexid-drawelements" 0.0 "framework/../bin/vertexid-drawelements -auto -fbo"
run_test "spec/glsl-1.30/execution/vs-attrib-ivec4-implied" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-attrib-ivec4-implied.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-attrib-ivec4-precision" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-attrib-ivec4-precision.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-attrib-uvec4-implied" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-attrib-uvec4-implied.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-attrib-uvec4-precision" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-attrib-uvec4-precision.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-decrement-int" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-decrement-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-decrement-uint" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-decrement-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-float-uint-conversion" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-float-uint-conversion.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-increment-int" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-increment-int.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-increment-uint" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-increment-uint.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-isinf-vec2" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-isinf-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-isinf-vec3" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-isinf-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-isinf-vec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-isinf-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-isnan-vec2" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-isnan-vec2.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-isnan-vec3" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-isnan-vec3.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-isnan-vec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-isnan-vec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-mix-bvec4-infnan" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-mix-bvec4-infnan.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-multiply-const-ivec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-multiply-const-ivec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-multiply-const-uvec4" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-multiply-const-uvec4.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-multiply-ivec4-const" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-multiply-ivec4-const.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-multiply-uvec4-const" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-multiply-uvec4-const.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-textureLod-miplevels" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-textureLod-miplevels.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-textureLod-miplevels-2" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-textureLod-miplevels-2.shader_test -auto"
run_test "spec/glsl-1.30/execution/vs-textureSize-compare" 0.0 "framework/../bin/shader_runner tests/spec/glsl-1.30/execution/vs-textureSize-compare.shader_test -auto"
run_test "spec/glsl-1.30/linker/clipping/mixing-clip-distance-and-clip-vertex-disallowed" 0.0 "framework/../bin/mixing-clip-distance-and-clip-vertex-disallowed -auto"
run_test "spec/glsl-1.30/preprocessor/concat/concat-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/concat/concat-01.frag pass 1.30"
run_test "spec/glsl-1.30/preprocessor/concat/concat-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/concat/concat-02.frag pass 1.30"
run_test "spec/glsl-1.30/preprocessor/concat/concat-03.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/concat/concat-03.frag pass 1.30"
run_test "spec/glsl-1.30/preprocessor/concat/concat-04.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/concat/concat-04.frag fail 1.30"
run_test "spec/glsl-1.30/preprocessor/feature-macros/gl_fragment_precision_high.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/feature-macros/gl_fragment_precision_high.frag pass 1.30"
run_test "spec/glsl-1.30/preprocessor/feature-macros/gl_fragment_precision_high.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/feature-macros/gl_fragment_precision_high.vert pass 1.30"
run_test "spec/glsl-1.30/preprocessor/reserved/double-underscore-01.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/reserved/double-underscore-01.frag fail 1.30"
run_test "spec/glsl-1.30/preprocessor/reserved/double-underscore-02.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/reserved/double-underscore-02.frag fail 1.30"
run_test "spec/glsl-1.30/preprocessor/reserved/double-underscore-03.frag" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-1.30/preprocessor/reserved/double-underscore-03.frag fail 1.30"
run_test "spec/glsl-1.30/texel-offset-limits" 0.0 "framework/../bin/glsl-1.30-texel-offset-limits -auto -fbo"
run_test "spec/glsl-es-3.00/compiler/array-length-is-constant.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/array-length-is-constant.vert pass 3.00"
run_test "spec/glsl-es-3.00/compiler/array-length-is-not-float.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/array-length-is-not-float.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/array-length-is-not-unsigned-int.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/array-length-is-not-unsigned-int.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/array-length-is-signed-int.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/array-length-is-signed-int.vert pass 3.00"
run_test "spec/glsl-es-3.00/compiler/array-sized-by-initializer.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/array-sized-by-initializer.vert pass 3.00"
run_test "spec/glsl-es-3.00/compiler/line-continuation.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/line-continuation.vert pass 3.00"
run_test "spec/glsl-es-3.00/compiler/no-statement-before-first-case.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/no-statement-before-first-case.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/no-unsized-arrays-01.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/no-unsized-arrays-01.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/no-unsized-arrays-02.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/no-unsized-arrays-02.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/undefined-macro.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/undefined-macro.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/uniform_block/block-array.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/block-array.vert fail 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-access-without-interface-name.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-access-without-interface-name.vert fail 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-array-access-with-noncontant-index.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-array-access-with-noncontant-index.vert fail 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-array-access-without-index.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-array-access-without-index.vert fail 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-array-without-size.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-array-without-size.vert fail 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-array.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-array.vert pass 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-basic.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-basic.vert pass 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-field-clashes-with-function.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-field-clashes-with-function.vert pass 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-field-clashes-with-struct.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-field-clashes-with-struct.vert pass 3.00 es"
run_test "spec/glsl-es-3.00/compiler/uniform_block/interface-name-field-clashes-with-variable.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/uniform_block/interface-name-field-clashes-with-variable.vert pass 3.00 es"
run_test "spec/glsl-es-3.00/compiler/utf8-comment.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/utf8-comment.vert pass 3.00"
run_test "spec/glsl-es-3.00/compiler/utf8-function.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/utf8-function.vert fail 3.00"
run_test "spec/glsl-es-3.00/compiler/utf8-identifier.vert" 0.0 "framework/../bin/glslparsertest tests/spec/glsl-es-3.00/compiler/utf8-identifier.vert fail 3.00"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 404 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

