#!/bin/bash


need_pass=431
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/EXT_transform_feedback/api-errors separate_no_varyings" 0.0 "bin/ext_transform_feedback-api-errors separate_no_varyings -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors separate_ok_1" 0.0 "bin/ext_transform_feedback-api-errors separate_ok_1 -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors separate_ok_2" 0.0 "bin/ext_transform_feedback-api-errors separate_ok_2 -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors separate_unbound_0_1" 0.0 "bin/ext_transform_feedback-api-errors separate_unbound_0_1 -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors separate_unbound_0_2" 0.0 "bin/ext_transform_feedback-api-errors separate_unbound_0_2 -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors separate_unbound_1_2" 0.0 "bin/ext_transform_feedback-api-errors separate_unbound_1_2 -auto -fbo"
run_test "spec/EXT_transform_feedback/api-errors useprog_active" 0.0 "bin/ext_transform_feedback-api-errors useprog_active -auto -fbo"
run_test "spec/EXT_transform_feedback/buffer-usage" 0.0 "bin/ext_transform_feedback-buffer-usage -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[1]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[1]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[2]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[3]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[3]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[4]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[4]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[5]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[5]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[6]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[6]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[7]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[7]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipDistance[8]-no-subscript" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipDistance[8]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_ClipVertex" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_ClipVertex -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_Color" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_Color -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_FogFragCoord" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_FogFragCoord -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_PointSize" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_PointSize -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_Position" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_Position -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_SecondaryColor" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_SecondaryColor -auto -fbo"
run_test "spec/EXT_transform_feedback/builtin-varyings gl_TexCoord" 0.0 "bin/ext_transform_feedback-builtin-varyings gl_TexCoord -auto -fbo"
run_test "spec/EXT_transform_feedback/change-size base-grow" 0.0 "bin/ext_transform_feedback-change-size base-grow -auto -fbo"
run_test "spec/EXT_transform_feedback/change-size base-shrink" 0.0 "bin/ext_transform_feedback-change-size base-shrink -auto -fbo"
run_test "spec/EXT_transform_feedback/change-size offset-grow" 0.0 "bin/ext_transform_feedback-change-size offset-grow -auto -fbo"
run_test "spec/EXT_transform_feedback/change-size offset-shrink" 0.0 "bin/ext_transform_feedback-change-size offset-shrink -auto -fbo"
run_test "spec/EXT_transform_feedback/change-size range-grow" 0.0 "bin/ext_transform_feedback-change-size range-grow -auto -fbo"
run_test "spec/EXT_transform_feedback/change-size range-shrink" 0.0 "bin/ext_transform_feedback-change-size range-shrink -auto -fbo"
run_test "spec/EXT_transform_feedback/discard-api" 0.0 "bin/ext_transform_feedback-discard-api -auto -fbo"
run_test "spec/EXT_transform_feedback/discard-bitmap" 0.0 "bin/ext_transform_feedback-discard-bitmap -auto -fbo"
run_test "spec/EXT_transform_feedback/discard-clear" 0.0 "bin/ext_transform_feedback-discard-clear -auto -fbo"
run_test "spec/EXT_transform_feedback/discard-copypixels" 0.0 "bin/ext_transform_feedback-discard-copypixels -auto -fbo"
run_test "spec/EXT_transform_feedback/discard-drawarrays" 0.0 "bin/ext_transform_feedback-discard-drawarrays -auto -fbo"
run_test "spec/EXT_transform_feedback/discard-drawpixels" 0.0 "bin/ext_transform_feedback-discard-drawpixels -auto -fbo"
run_test "spec/EXT_transform_feedback/generatemipmap buffer" 0.0 "bin/ext_transform_feedback-generatemipmap buffer -auto -fbo"
run_test "spec/EXT_transform_feedback/generatemipmap discard" 0.0 "bin/ext_transform_feedback-generatemipmap discard -auto -fbo"
run_test "spec/EXT_transform_feedback/generatemipmap prims_written" 0.0 "bin/ext_transform_feedback-generatemipmap prims_written -auto -fbo"
run_test "spec/EXT_transform_feedback/get-buffer-state buffer_size" 0.0 "bin/ext_transform_feedback-get-buffer-state buffer_size -auto -fbo"
run_test "spec/EXT_transform_feedback/get-buffer-state buffer_start" 0.0 "bin/ext_transform_feedback-get-buffer-state buffer_start -auto -fbo"
run_test "spec/EXT_transform_feedback/get-buffer-state indexed_binding" 0.0 "bin/ext_transform_feedback-get-buffer-state indexed_binding -auto -fbo"
run_test "spec/EXT_transform_feedback/get-buffer-state main_binding" 0.0 "bin/ext_transform_feedback-get-buffer-state main_binding -auto -fbo"
run_test "spec/EXT_transform_feedback/immediate-reuse" 0.0 "bin/ext_transform_feedback-immediate-reuse -auto -fbo"
run_test "spec/EXT_transform_feedback/interleaved-attribs" 0.0 "bin/ext_transform_feedback-interleaved -auto -fbo"
run_test "spec/EXT_transform_feedback/intervening-read output" 0.0 "bin/ext_transform_feedback-intervening-read output -auto -fbo"
run_test "spec/EXT_transform_feedback/intervening-read prims_written" 0.0 "bin/ext_transform_feedback-intervening-read prims_written -auto -fbo"
run_test "spec/EXT_transform_feedback/negative-prims" 0.0 "bin/ext_transform_feedback-negative-prims -auto -fbo"
run_test "spec/EXT_transform_feedback/order arrays lines" 0.0 "bin/ext_transform_feedback-order arrays lines -auto -fbo"
run_test "spec/EXT_transform_feedback/order arrays points" 0.0 "bin/ext_transform_feedback-order arrays points -auto -fbo"
run_test "spec/EXT_transform_feedback/order arrays triangles" 0.0 "bin/ext_transform_feedback-order arrays triangles -auto -fbo"
run_test "spec/EXT_transform_feedback/order elements lines" 0.0 "bin/ext_transform_feedback-order elements lines -auto -fbo"
run_test "spec/EXT_transform_feedback/order elements points" 0.0 "bin/ext_transform_feedback-order elements points -auto -fbo"
run_test "spec/EXT_transform_feedback/order elements triangles" 0.0 "bin/ext_transform_feedback-order elements triangles -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type float" 0.0 "bin/ext_transform_feedback-output-type float -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type float[2]" 0.0 "bin/ext_transform_feedback-output-type float[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type float[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type float[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type int" 0.0 "bin/ext_transform_feedback-output-type int -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type int[2]" 0.0 "bin/ext_transform_feedback-output-type int[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type int[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type int[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec2" 0.0 "bin/ext_transform_feedback-output-type ivec2 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec2[2]" 0.0 "bin/ext_transform_feedback-output-type ivec2[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec2[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type ivec2[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec3" 0.0 "bin/ext_transform_feedback-output-type ivec3 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec3[2]" 0.0 "bin/ext_transform_feedback-output-type ivec3[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec3[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type ivec3[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec4" 0.0 "bin/ext_transform_feedback-output-type ivec4 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec4[2]" 0.0 "bin/ext_transform_feedback-output-type ivec4[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type ivec4[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type ivec4[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2" 0.0 "bin/ext_transform_feedback-output-type mat2 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2[2]" 0.0 "bin/ext_transform_feedback-output-type mat2[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat2[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2x3" 0.0 "bin/ext_transform_feedback-output-type mat2x3 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2x3[2]" 0.0 "bin/ext_transform_feedback-output-type mat2x3[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2x3[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat2x3[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2x4" 0.0 "bin/ext_transform_feedback-output-type mat2x4 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2x4[2]" 0.0 "bin/ext_transform_feedback-output-type mat2x4[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat2x4[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat2x4[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3" 0.0 "bin/ext_transform_feedback-output-type mat3 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3[2]" 0.0 "bin/ext_transform_feedback-output-type mat3[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat3[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3x2" 0.0 "bin/ext_transform_feedback-output-type mat3x2 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3x2[2]" 0.0 "bin/ext_transform_feedback-output-type mat3x2[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3x2[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat3x2[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3x4" 0.0 "bin/ext_transform_feedback-output-type mat3x4 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3x4[2]" 0.0 "bin/ext_transform_feedback-output-type mat3x4[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat3x4[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat3x4[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4" 0.0 "bin/ext_transform_feedback-output-type mat4 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4[2]" 0.0 "bin/ext_transform_feedback-output-type mat4[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat4[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4x2" 0.0 "bin/ext_transform_feedback-output-type mat4x2 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4x2[2]" 0.0 "bin/ext_transform_feedback-output-type mat4x2[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4x2[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat4x2[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4x3" 0.0 "bin/ext_transform_feedback-output-type mat4x3 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4x3[2]" 0.0 "bin/ext_transform_feedback-output-type mat4x3[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type mat4x3[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type mat4x3[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uint" 0.0 "bin/ext_transform_feedback-output-type uint -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uint[2]" 0.0 "bin/ext_transform_feedback-output-type uint[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uint[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type uint[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec2" 0.0 "bin/ext_transform_feedback-output-type uvec2 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec2[2]" 0.0 "bin/ext_transform_feedback-output-type uvec2[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec2[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type uvec2[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec3" 0.0 "bin/ext_transform_feedback-output-type uvec3 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec3[2]" 0.0 "bin/ext_transform_feedback-output-type uvec3[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec3[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type uvec3[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec4" 0.0 "bin/ext_transform_feedback-output-type uvec4 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec4[2]" 0.0 "bin/ext_transform_feedback-output-type uvec4[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type uvec4[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type uvec4[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec2" 0.0 "bin/ext_transform_feedback-output-type vec2 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec2[2]" 0.0 "bin/ext_transform_feedback-output-type vec2[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec2[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type vec2[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec3" 0.0 "bin/ext_transform_feedback-output-type vec3 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec3[2]" 0.0 "bin/ext_transform_feedback-output-type vec3[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec3[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type vec3[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec4" 0.0 "bin/ext_transform_feedback-output-type vec4 -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec4[2]" 0.0 "bin/ext_transform_feedback-output-type vec4[2] -auto -fbo"
run_test "spec/EXT_transform_feedback/output-type vec4[2]-no-subscript" 0.0 "bin/ext_transform_feedback-output-type vec4[2]-no-subscript -auto -fbo"
run_test "spec/EXT_transform_feedback/overflow-edge-cases" 0.0 "bin/ext_transform_feedback-overflow-edge-cases -auto -fbo"
run_test "spec/EXT_transform_feedback/position-readback-bufferbase" 0.0 "bin/ext_transform_feedback-position -auto -fbo"
run_test "spec/EXT_transform_feedback/position-readback-bufferbase-discard" 0.0 "bin/ext_transform_feedback-position discard -auto -fbo"
run_test "spec/EXT_transform_feedback/position-readback-bufferoffset" 0.0 "bin/ext_transform_feedback-position offset -auto -fbo"
run_test "spec/EXT_transform_feedback/position-readback-bufferoffset-discard" 0.0 "bin/ext_transform_feedback-position offset discard -auto -fbo"
run_test "spec/EXT_transform_feedback/position-readback-bufferrange" 0.0 "bin/ext_transform_feedback-position range -auto -fbo"
run_test "spec/EXT_transform_feedback/position-readback-bufferrange-discard" 0.0 "bin/ext_transform_feedback-position range discard -auto -fbo"
run_test "spec/EXT_transform_feedback/position-render-bufferbase" 0.0 "bin/ext_transform_feedback-position render -auto -fbo"
run_test "spec/EXT_transform_feedback/position-render-bufferbase-discard" 0.0 "bin/ext_transform_feedback-position render discard -auto -fbo"
run_test "spec/EXT_transform_feedback/position-render-bufferoffset" 0.0 "bin/ext_transform_feedback-position render offset -auto -fbo"
run_test "spec/EXT_transform_feedback/position-render-bufferoffset-discard" 0.0 "bin/ext_transform_feedback-position render offset discard -auto -fbo"
run_test "spec/EXT_transform_feedback/position-render-bufferrange" 0.0 "bin/ext_transform_feedback-position render range -auto -fbo"
run_test "spec/EXT_transform_feedback/position-render-bufferrange-discard" 0.0 "bin/ext_transform_feedback-position render range discard -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_generated-bufferbase" 0.0 "bin/ext_transform_feedback-position primgen -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_generated-bufferbase-discard" 0.0 "bin/ext_transform_feedback-position primgen discard -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_generated-bufferoffset" 0.0 "bin/ext_transform_feedback-position primgen offset -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_generated-bufferoffset-discard" 0.0 "bin/ext_transform_feedback-position primgen offset discard -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_generated-bufferrange" 0.0 "bin/ext_transform_feedback-position primgen range -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_generated-bufferrange-discard" 0.0 "bin/ext_transform_feedback-position primgen range discard -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_written-bufferbase" 0.0 "bin/ext_transform_feedback-position primwritten -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_written-bufferbase-discard" 0.0 "bin/ext_transform_feedback-position primwritten discard -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_written-bufferoffset" 0.0 "bin/ext_transform_feedback-position primwritten offset -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_written-bufferoffset-discard" 0.0 "bin/ext_transform_feedback-position primwritten offset discard -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_written-bufferrange" 0.0 "bin/ext_transform_feedback-position primwritten range -auto -fbo"
run_test "spec/EXT_transform_feedback/query-primitives_written-bufferrange-discard" 0.0 "bin/ext_transform_feedback-position primwritten range discard -auto -fbo"
run_test "spec/EXT_transform_feedback/separate-attribs" 0.0 "bin/ext_transform_feedback-separate -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_loop flat_first" 0.0 "bin/ext_transform_feedback-tessellation line_loop flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_loop flat_last" 0.0 "bin/ext_transform_feedback-tessellation line_loop flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_loop monochrome" 0.0 "bin/ext_transform_feedback-tessellation line_loop monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_loop smooth" 0.0 "bin/ext_transform_feedback-tessellation line_loop smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_strip flat_first" 0.0 "bin/ext_transform_feedback-tessellation line_strip flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_strip flat_last" 0.0 "bin/ext_transform_feedback-tessellation line_strip flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_strip monochrome" 0.0 "bin/ext_transform_feedback-tessellation line_strip monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation line_strip smooth" 0.0 "bin/ext_transform_feedback-tessellation line_strip smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation lines flat_first" 0.0 "bin/ext_transform_feedback-tessellation lines flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation lines flat_last" 0.0 "bin/ext_transform_feedback-tessellation lines flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation lines monochrome" 0.0 "bin/ext_transform_feedback-tessellation lines monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation lines smooth" 0.0 "bin/ext_transform_feedback-tessellation lines smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation points flat_first" 0.0 "bin/ext_transform_feedback-tessellation points flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation points flat_last" 0.0 "bin/ext_transform_feedback-tessellation points flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation points monochrome" 0.0 "bin/ext_transform_feedback-tessellation points monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation points smooth" 0.0 "bin/ext_transform_feedback-tessellation points smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation polygon flat_first" 0.0 "bin/ext_transform_feedback-tessellation polygon flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation polygon monochrome" 0.0 "bin/ext_transform_feedback-tessellation polygon monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation polygon smooth" 0.0 "bin/ext_transform_feedback-tessellation polygon smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation polygon wireframe" 0.0 "bin/ext_transform_feedback-tessellation polygon wireframe -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quad_strip flat_first" 0.0 "bin/ext_transform_feedback-tessellation quad_strip flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quad_strip monochrome" 0.0 "bin/ext_transform_feedback-tessellation quad_strip monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quad_strip smooth" 0.0 "bin/ext_transform_feedback-tessellation quad_strip smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quad_strip wireframe" 0.0 "bin/ext_transform_feedback-tessellation quad_strip wireframe -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quads flat_first" 0.0 "bin/ext_transform_feedback-tessellation quads flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quads monochrome" 0.0 "bin/ext_transform_feedback-tessellation quads monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quads smooth" 0.0 "bin/ext_transform_feedback-tessellation quads smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation quads wireframe" 0.0 "bin/ext_transform_feedback-tessellation quads wireframe -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_fan flat_last" 0.0 "bin/ext_transform_feedback-tessellation triangle_fan flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_fan monochrome" 0.0 "bin/ext_transform_feedback-tessellation triangle_fan monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_fan smooth" 0.0 "bin/ext_transform_feedback-tessellation triangle_fan smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_fan wireframe" 0.0 "bin/ext_transform_feedback-tessellation triangle_fan wireframe -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_strip flat_first" 0.0 "bin/ext_transform_feedback-tessellation triangle_strip flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_strip flat_last" 0.0 "bin/ext_transform_feedback-tessellation triangle_strip flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_strip monochrome" 0.0 "bin/ext_transform_feedback-tessellation triangle_strip monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_strip smooth" 0.0 "bin/ext_transform_feedback-tessellation triangle_strip smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangle_strip wireframe" 0.0 "bin/ext_transform_feedback-tessellation triangle_strip wireframe -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangles flat_first" 0.0 "bin/ext_transform_feedback-tessellation triangles flat_first -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangles flat_last" 0.0 "bin/ext_transform_feedback-tessellation triangles flat_last -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangles monochrome" 0.0 "bin/ext_transform_feedback-tessellation triangles monochrome -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangles smooth" 0.0 "bin/ext_transform_feedback-tessellation triangles smooth -auto -fbo"
run_test "spec/EXT_transform_feedback/tessellation triangles wireframe" 0.0 "bin/ext_transform_feedback-tessellation triangles wireframe -auto -fbo"
run_test "spec/EXT_vertex_array_bgra/bgra-sec-color-pointer" 0.0 "bin/bgra-sec-color-pointer -auto"
run_test "spec/EXT_vertex_array_bgra/bgra-vert-attrib-pointer" 0.0 "bin/bgra-vert-attrib-pointer -auto"
run_test "spec/NV_conditional_render/begin-while-active" 0.0 "bin/nv_conditional_render-begin-while-active -auto -fbo"
run_test "spec/NV_conditional_render/bitmap" 0.0 "bin/nv_conditional_render-bitmap -auto"
run_test "spec/NV_conditional_render/clear" 0.0 "bin/nv_conditional_render-clear -auto"
run_test "spec/NV_conditional_render/copypixels" 0.0 "bin/nv_conditional_render-copypixels -auto"
run_test "spec/NV_conditional_render/copyteximage" 0.0 "bin/nv_conditional_render-copyteximage -auto"
run_test "spec/NV_conditional_render/copytexsubimage" 0.0 "bin/nv_conditional_render-copytexsubimage -auto"
run_test "spec/NV_conditional_render/dlist" 0.0 "bin/nv_conditional_render-dlist -auto"
run_test "spec/NV_conditional_render/drawpixels" 0.0 "bin/nv_conditional_render-drawpixels -auto"
run_test "spec/NV_conditional_render/generatemipmap" 0.0 "bin/nv_conditional_render-generatemipmap -auto"
run_test "spec/NV_conditional_render/vertex_array" 0.0 "bin/nv_conditional_render-vertex_array -auto"
run_test "spec/NV_primitive_restart/primitive-restart-DISABLE_VBO" 0.0 "bin/primitive-restart DISABLE_VBO -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_COMBINED_VERTEX_AND_INDEX" 0.0 "bin/primitive-restart VBO_COMBINED_VERTEX_AND_INDEX -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_INDEX_ONLY" 0.0 "bin/primitive-restart VBO_INDEX_ONLY -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_SEPARATE_VERTEX_AND_INDEX" 0.0 "bin/primitive-restart VBO_SEPARATE_VERTEX_AND_INDEX -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_VERTEX_ONLY" 0.0 "bin/primitive-restart VBO_VERTEX_ONLY -auto"
run_test "spec/OES_read_format/oes-read-format" 0.0 "bin/oes-read-format -auto"
run_test "spec/SGIS_generate_mipmap/gen-nonzero-unit" 0.0 "bin/gen-nonzero-unit -auto"
run_test "spec/SGIS_generate_mipmap/gen-teximage" 0.0 "bin/gen-teximage -auto"
run_test "spec/SGIS_generate_mipmap/gen-texsubimage" 0.0 "bin/gen-texsubimage -auto"
run_test "spec/glsl-1.00/compiler/arithmetic-operators/division-by-zero-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/arithmetic-operators/division-by-zero-02.frag pass 1.00"
run_test "spec/glsl-1.00/compiler/arithmetic-operators/modulus-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/arithmetic-operators/modulus-00.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.vert fail 1.00"
run_test "spec/glsl-1.00/compiler/assignment-operators/modulus-assign-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/assignment-operators/modulus-assign-00.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/default-precision-bool-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/default-precision-bool-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/default-precision-float-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/default-precision-float-01.frag pass 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/default-precision-vec-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/default-precision-vec-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-bool-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-bool-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-bool-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-bool-02.frag fail 1.30"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-fs-highp-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-fs-highp-02.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-function-param-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-function-param-01.frag pass 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-02.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-02.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-vs-highp-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-vs-highp-01.vert pass 1.00"
run_test "spec/glsl-1.00/compiler/qualifiers/fn-inout-array-allowed-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/qualifiers/fn-inout-array-allowed-cstyle.vert pass 1.00 --check-link"
run_test "spec/glsl-1.00/compiler/qualifiers/fn-out-array-allowed-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/qualifiers/fn-out-array-allowed-cstyle.vert pass 1.00 --check-link"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-01.vert fail 1.00"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-02.vert fail 1.00"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-02.frag fail 1.00"
run_test "spec/glsl-1.10/api/getactiveattrib 110" 0.0 "bin/getactiveattrib 110 -auto -fbo"
run_test "spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-01.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-02.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/arithmetic-operators/modulus-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/arithmetic-operators/modulus-00.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/assignment-operators/modulus-assign-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/assignment-operators/modulus-assign-00.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-01.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-02.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-global.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-global.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-global.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-global.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-03.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-03.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-04.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-04.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-03.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-03.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-04.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-04.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-05.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-05.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-06.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-06.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData-dead.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData-dead.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-dead-and-gl_FragData.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-dead-and-gl_FragData.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/invalid-version.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/invalid-version.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/centroid-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/centroid-01.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/in-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/in-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/in-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/in-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/inout-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/inout-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/invariant-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/invariant-01.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/out-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/out-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/out-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/out-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/inout-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/inout-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/inout.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/inout.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/nonuniform-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/nonuniform-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/nonuniform.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/nonuniform.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/out-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/out-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/out.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/out.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/return-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/return-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/return.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/return.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-coord.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-coord.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-frag-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-frag-coord.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-frag-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-frag-coord.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-front-facing.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-front-facing.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord0.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord0.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord1.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord1.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord2.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord3.vert fail 1.10"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 431 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

