#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f $0))
RUNDATE=$(date +%Y-%m-%d.%H)
DUT_DATA_DIR=$SCRIPT_DIR/../logs/dut-data
RUNFILE=$DUT_DATA_DIR/inventory-$RUNDATE.txt

mkdir -p $DUT_DATA_DIR
SEP=
for pool in bvt cq tot-cq pfq
do
    echo -n "$SEP"
    STATUS=$DUT_DATA_DIR/full.$RUNDATE.$pool.txt
    $SCRIPT_DIR/full_status $pool >$STATUS
    $SCRIPT_DIR/report_status $STATUS
    SEP="

"
done >$RUNFILE

INTEREST=(
	chromeos-lab-alerts@google.com
)

mailx -s "DUT pool inventories $RUNDATE" "${INTEREST[@]}" <$RUNFILE
