#!/bin/bash


need_pass=333
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib
export DISPLAY=:0
export XAUTHORITY=/home/chronos/.Xauthority


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+ Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
    echo "+ Return code 0 -> Test passed. ($name)"
  else
    let "failures++"
    echo "+ Return code not 0 -> Test failed. ($name)"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/EXT_texture_sRGB/fbo-alphatest-formats" 0.0 "bin/fbo-alphatest-formats -auto GL_EXT_texture_sRGB"
run_test "spec/EXT_texture_sRGB/fbo-srgb" 0.0 "bin/fbo-srgb -auto"
run_test "spec/EXT_texture_sRGB/invalid formats" 0.0 "bin/arb_texture_compression-invalid-formats srgb"
run_test "spec/EXT_texture_sRGB/texwrap formats" 0.0 "bin/texwrap -fbo -auto GL_EXT_texture_sRGB"
run_test "spec/EXT_vertex_array_bgra/bgra-sec-color-pointer" 0.0 "bin/bgra-sec-color-pointer -auto"
run_test "spec/EXT_vertex_array_bgra/bgra-vert-attrib-pointer" 0.0 "bin/bgra-vert-attrib-pointer -auto"
run_test "spec/NV_primitive_restart/primitive-restart-DISABLE_VBO" 0.0 "bin/primitive-restart DISABLE_VBO -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_COMBINED_VERTEX_AND_INDEX" 0.0 "bin/primitive-restart VBO_COMBINED_VERTEX_AND_INDEX -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_INDEX_ONLY" 0.0 "bin/primitive-restart VBO_INDEX_ONLY -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_SEPARATE_VERTEX_AND_INDEX" 0.0 "bin/primitive-restart VBO_SEPARATE_VERTEX_AND_INDEX -auto"
run_test "spec/NV_primitive_restart/primitive-restart-VBO_VERTEX_ONLY" 0.0 "bin/primitive-restart VBO_VERTEX_ONLY -auto"
run_test "spec/OES_read_format/oes-read-format" 0.0 "bin/oes-read-format -auto"
run_test "spec/SGIS_generate_mipmap/gen-nonzero-unit" 0.0 "bin/gen-nonzero-unit -auto"
run_test "spec/SGIS_generate_mipmap/gen-teximage" 0.0 "bin/gen-teximage -auto"
run_test "spec/SGIS_generate_mipmap/gen-texsubimage" 0.0 "bin/gen-texsubimage -auto"
run_test "spec/glsl-1.00/compiler/arithmetic-operators/division-by-zero-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/arithmetic-operators/division-by-zero-02.frag pass 1.00"
run_test "spec/glsl-1.00/compiler/arithmetic-operators/modulus-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/arithmetic-operators/modulus-00.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/assignment-operators/assign-array-prohibited.vert fail 1.00"
run_test "spec/glsl-1.00/compiler/assignment-operators/modulus-assign-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/assignment-operators/modulus-assign-00.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/default-precision-bool-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/default-precision-bool-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/default-precision-float-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/default-precision-float-01.frag pass 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/default-precision-vec-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/default-precision-vec-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-bool-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-bool-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-fs-highp-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-fs-highp-02.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-function-param-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-function-param-01.frag pass 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-literal-const-02.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-struct-02.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/precision-qualifiers/precision-vs-highp-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/precision-qualifiers/precision-vs-highp-01.vert pass 1.00"
run_test "spec/glsl-1.00/compiler/qualifiers/fn-inout-array-allowed-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/qualifiers/fn-inout-array-allowed-cstyle.vert pass 1.00 --check-link"
run_test "spec/glsl-1.00/compiler/qualifiers/fn-out-array-allowed-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/qualifiers/fn-out-array-allowed-cstyle.vert pass 1.00 --check-link"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-01.vert fail 1.00"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-attribute-02.vert fail 1.00"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-01.frag fail 1.00"
run_test "spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.00/compiler/storage-qualfiers/static-write-varying-02.frag fail 1.00"
run_test "spec/glsl-1.10/api/getactiveattrib 110" 0.0 "bin/getactiveattrib 110 -auto -fbo"
run_test "spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-01.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/arithmetic-operators/division-by-zero-02.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/arithmetic-operators/modulus-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/arithmetic-operators/modulus-00.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/assignment-operators/assign-array-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/assignment-operators/modulus-assign-00.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/assignment-operators/modulus-assign-00.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-01.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/constant-expressions/sampler-array-index-02.frag pass 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-global.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-global.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-global.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-global.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/declarations/bad-array-type-struct-member.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-03.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-03.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-equality-04.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-equality-04.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-03.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-03.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-04.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-04.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-05.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-05.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/invalid-logic-not-06.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/expressions/invalid-logic-not-06.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postdecrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/postincrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/predecrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-float-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-int-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-ivec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec2-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec3-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-assignment.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.frag" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.vert" 0.0 "bin/glslparsertest generated_tests/spec/glsl-1.10/compiler/expressions/preincrement-vec4-non-lvalue-for-out-parameter.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData-dead.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData-dead.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-and-gl_FragData.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-dead-and-gl_FragData.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/fragment-outputs/write-gl_FragColor-dead-and-gl_FragData.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/invalid-version.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/invalid-version.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/centroid-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/centroid-01.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-inout-array-prohibited-cstyle.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/fn-out-array-prohibited-cstyle.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/in-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/in-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/in-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/in-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/inout-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/inout-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/invariant-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/invariant-01.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/out-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/out-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/out-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/out-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bool-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec2-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec3-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-bvec4-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/qualifiers/varying-struct-prohibited.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/reserved/double-underscore-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/reserved/double-underscore-01.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/reserved/double-underscore-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/reserved/double-underscore-02.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/reserved/double-underscore-03.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/reserved/double-underscore-03.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/inout-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/inout-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/inout.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/inout.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/nonuniform-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/nonuniform-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/nonuniform.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/nonuniform.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/out-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/out-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/out.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/out.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/return-struct.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/return-struct.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/samplers/return.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/samplers/return.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-close-bracket.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/special-characters/digraph-open-bracket.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-01.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-01.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-02.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-attribute-02.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-color.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-coord.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-coord.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-frag-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-fog-frag-coord.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-frag-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-frag-coord.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-front-facing.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-front-facing.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord0.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord0.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord1.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord1.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord2.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord2.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord3.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord3.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord4.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord4.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord5.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord5.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord6.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord6.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord7.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-multitexcoord7.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-normal.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-normal.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-secondary-color.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-tex-coord.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-tex-coord.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-01.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-01.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-02.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-varying-02.frag fail 1.10"
run_test "spec/glsl-1.10/compiler/storage-qualfiers/static-write-vertex.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/storage-qualfiers/static-write-vertex.vert fail 1.10"
run_test "spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name-nested.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name-nested.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/struct/structure-and-field-have-same-name.vert pass 1.10"
run_test "spec/glsl-1.10/compiler/texcoord/implicit-access-max.frag" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/texcoord/implicit-access-max.frag fail 1.10 --check-link"
run_test "spec/glsl-1.10/compiler/texcoord/implicit-access-max.vert" 0.0 "bin/glslparsertest tests/spec/glsl-1.10/compiler/texcoord/implicit-access-max.vert fail 1.10 --check-link"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-abs-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-abs-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-acos-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-acos-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-all-bvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec2-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec3-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4-using-if" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-any-bvec4-using-if.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-asin-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-asin-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-atan-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-atan-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-ceil-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec2-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec3-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-clamp-vec4-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-cross-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-cross-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec2-bvec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec2-bvec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec3-bvec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec3-bvec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec4-bvec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-bvec4-bvec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-equal-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-equal-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-exp2-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-float-float-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-float-float-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec2-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec2-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec3-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec3-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec4-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-faceforward-vec4-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-float" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-float.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-floor-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-floor-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThan-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec3-ivec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec4-ivec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-ivec4-ivec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec2-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec3-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec3-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec4-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-greaterThanEqual-vec4-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec3.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec4" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-inversesqrt-vec4.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec2-ivec2" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec2-ivec2.shader_test -auto"
run_test "spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec3-ivec3" 0.0 "bin/shader_runner generated_tests/spec/glsl-1.10/execution/built-in-functions/fs-lessThan-ivec3-ivec3.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 333 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

