#!/bin/bash


need_pass=170
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
  else
    let "failures++"
  fi
}


pushd $PIGLIT_PATH
run_test "glean/vp1-Z-write test" 0.0 "framework/../bin/glean -o -v -v -v -t +vertProg1 --quick"
run_test "glx/GLX_EXT_import_context/free context" 0.0 "framework/../bin/glx-free-context"
run_test "glx/GLX_EXT_import_context/get context ID" 0.0 "framework/../bin/glx-get-context-id"
run_test "glx/GLX_EXT_import_context/get current display" 0.0 "framework/../bin/glx-get-current-display-ext"
run_test "glx/GLX_EXT_import_context/import context, multi process" 0.0 "framework/../bin/glx-import-context-multi-process"
run_test "glx/GLX_EXT_import_context/import context, single process" 0.0 "framework/../bin/glx-import-context-single-process"
run_test "glx/GLX_EXT_import_context/imported context has same context ID" 0.0 "framework/../bin/glx-import-context-has-same-context-id"
run_test "glx/GLX_EXT_import_context/make current, single process" 0.0 "framework/../bin/glx-make-current-single-process"
run_test "glx/GLX_EXT_import_context/query context info" 0.0 "framework/../bin/glx-query-context-info-ext"
run_test "glx/GLX_OML_sync_control/swapbuffersmsc-return swap_interval 1" 0.0 "framework/../bin/glx-oml-sync-control-swapbuffersmsc-return 1 -auto -fbo"
run_test "glx/extension string sanity" 0.0 "framework/../bin/glx-string-sanity"
run_test "glx/glx-close-display" 0.0 "framework/../bin/glx-close-display -auto"
run_test "glx/glx-copy-sub-buffer" 0.0 "framework/../bin/glx-copy-sub-buffer -auto"
run_test "glx/glx-destroycontext-1" 0.0 "framework/../bin/glx-destroycontext-1 -auto"
run_test "glx/glx-destroycontext-2" 0.0 "framework/../bin/glx-destroycontext-2 -auto"
run_test "glx/glx-dont-care-mask" 0.0 "framework/../bin/glx-dont-care-mask -auto"
run_test "glx/glx-fbconfig-compliance" 0.0 "framework/../bin/glx-fbconfig-compliance -auto"
run_test "glx/glx-fbconfig-sanity" 0.0 "framework/../bin/glx-fbconfig-sanity -auto"
run_test "glx/glx-fbo-binding" 0.0 "framework/../bin/glx-fbo-binding -auto"
run_test "glx/glx-multi-context-ib-1" 0.0 "framework/../bin/glx-multi-context-ib-1 -auto"
run_test "glx/glx-multithread" 0.0 "framework/../bin/glx-multithread -auto"
run_test "glx/glx-multithread-makecurrent-1" 0.0 "framework/../bin/glx-multithread-makecurrent-1 -auto"
run_test "glx/glx-multithread-makecurrent-2" 0.0 "framework/../bin/glx-multithread-makecurrent-2 -auto"
run_test "glx/glx-multithread-makecurrent-3" 0.0 "framework/../bin/glx-multithread-makecurrent-3 -auto"
run_test "glx/glx-multithread-makecurrent-4" 0.0 "framework/../bin/glx-multithread-makecurrent-4 -auto"
run_test "glx/glx-pixmap-crosscheck" 0.0 "framework/../bin/glx-pixmap-crosscheck -auto"
run_test "glx/glx-pixmap-life" 0.0 "framework/../bin/glx-pixmap-life -auto"
run_test "glx/glx-pixmap13-life" 0.0 "framework/../bin/glx-pixmap13-life -auto"
run_test "glx/glx-query-drawable-GLXBadDrawable" 0.0 "framework/../bin/glx-query-drawable -auto --bad-drawable"
run_test "glx/glx-shader-sharing" 0.0 "framework/../bin/glx-shader-sharing -auto"
run_test "glx/glx-swap-event_async" 0.0 "framework/../bin/glx-swap-event -auto --async"
run_test "glx/glx-swap-event_event" 0.0 "framework/../bin/glx-swap-event -auto --event"
run_test "glx/glx-swap-event_interval" 0.0 "framework/../bin/glx-swap-event -auto --interval"
run_test "glx/glx-swap-singlebuffer" 0.0 "framework/../bin/glx-swap-singlebuffer -auto"
run_test "glx/glx-visuals-depth" 0.0 "framework/../bin/glx-visuals-depth -auto"
run_test "glx/glx-visuals-depth -pixmap" 0.0 "framework/../bin/glx-visuals-depth -pixmap -auto -fbo"
run_test "glx/glx-visuals-stencil" 0.0 "framework/../bin/glx-visuals-stencil -auto"
run_test "glx/glx-visuals-stencil -pixmap" 0.0 "framework/../bin/glx-visuals-stencil -pixmap -auto -fbo"
run_test "glx/glx-window-life" 0.0 "framework/../bin/glx-window-life -auto"
run_test "hiz/hiz-depth-read-fbo-d24-s0" 0.0 "framework/../bin/hiz-depth-read-fbo-d24-s0 -auto"
run_test "hiz/hiz-depth-read-fbo-d24s8" 0.0 "framework/../bin/hiz-depth-read-fbo-d24s8 -auto"
run_test "hiz/hiz-depth-read-window-stencil0" 0.0 "framework/../bin/hiz-depth-read-window-stencil0 -auto"
run_test "hiz/hiz-depth-read-window-stencil1" 0.0 "framework/../bin/hiz-depth-read-window-stencil1 -auto"
run_test "hiz/hiz-depth-stencil-test-fbo-d0-s8" 0.0 "framework/../bin/hiz-depth-stencil-test-fbo-d0-s8 -auto"
run_test "hiz/hiz-depth-stencil-test-fbo-d24-s0" 0.0 "framework/../bin/hiz-depth-stencil-test-fbo-d24-s0 -auto"
run_test "hiz/hiz-depth-stencil-test-fbo-d24s8" 0.0 "framework/../bin/hiz-depth-stencil-test-fbo-d24s8 -auto"
run_test "hiz/hiz-depth-test-fbo-d24-s0" 0.0 "framework/../bin/hiz-depth-test-fbo-d24-s0 -auto"
run_test "hiz/hiz-depth-test-fbo-d24s8" 0.0 "framework/../bin/hiz-depth-test-fbo-d24s8 -auto"
run_test "hiz/hiz-depth-test-window-stencil0" 0.0 "framework/../bin/hiz-depth-test-window-stencil0 -auto"
run_test "hiz/hiz-depth-test-window-stencil1" 0.0 "framework/../bin/hiz-depth-test-window-stencil1 -auto"
run_test "hiz/hiz-stencil-read-fbo-d0-s8" 0.0 "framework/../bin/hiz-stencil-read-fbo-d0-s8 -auto"
run_test "hiz/hiz-stencil-read-fbo-d24s8" 0.0 "framework/../bin/hiz-stencil-read-fbo-d24s8 -auto"
run_test "hiz/hiz-stencil-read-window-depth0" 0.0 "framework/../bin/hiz-stencil-read-window-depth0 -auto"
run_test "hiz/hiz-stencil-read-window-depth1" 0.0 "framework/../bin/hiz-stencil-read-window-depth1 -auto"
run_test "hiz/hiz-stencil-test-fbo-d0-s8" 0.0 "framework/../bin/hiz-stencil-test-fbo-d0-s8 -auto"
run_test "hiz/hiz-stencil-test-fbo-d24s8" 0.0 "framework/../bin/hiz-stencil-test-fbo-d24s8 -auto"
run_test "hiz/hiz-stencil-test-window-depth0" 0.0 "framework/../bin/hiz-stencil-test-window-depth0 -auto"
run_test "hiz/hiz-stencil-test-window-depth1" 0.0 "framework/../bin/hiz-stencil-test-window-depth1 -auto"
run_test "security/initialized-fbo" 0.0 "framework/../bin/initialized-fbo -auto"
run_test "security/initialized-texmemory" 0.0 "framework/../bin/initialized-texmemory -auto"
run_test "security/initialized-vbo" 0.0 "framework/../bin/initialized-vbo -auto"
run_test "shaders/GLSL link array-of-struct-of-array" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-struct-array.frag pass -auto -fbo"
run_test "shaders/GLSL link matched global initializer expression" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-05a.vert shaders/glsl-link-initializer-05b.vert fail -auto -fbo"
run_test "shaders/GLSL link matched global initializer, 2 shaders" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-01c.vert shaders/glsl-link-initializer-01d.vert pass -auto -fbo"
run_test "shaders/GLSL link mismatched centroid" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-centroid-01a.vert shaders/glsl-link-centroid-01b.vert fail -auto -fbo"
run_test "shaders/GLSL link mismatched global const initializer" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-02a.vert shaders/glsl-link-initializer-02b.vert fail -auto -fbo"
run_test "shaders/GLSL link mismatched global initializer expression" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-06a.vert shaders/glsl-link-initializer-06b.vert fail -auto -fbo"
run_test "shaders/GLSL link mismatched global initializer, 2 shaders" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-01b.vert shaders/glsl-link-initializer-01d.vert fail -auto -fbo"
run_test "shaders/GLSL link mismatched global initializer, 3 shaders" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-01a.vert shaders/glsl-link-initializer-01b.vert shaders/glsl-link-initializer-01c.vert fail -auto -fbo"
run_test "shaders/GLSL link mismatched invariant" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-invariant-01a.vert shaders/glsl-link-invariant-01b.vert fail -auto -fbo"
run_test "shaders/GLSL link single global initializer, 2 shaders" 0.0 "framework/../bin/glsl-link-test shaders/glsl-link-initializer-01a.vert shaders/glsl-link-initializer-01b.vert pass -auto -fbo"
run_test "shaders/attribute0" 0.0 "framework/../bin/attribute0 -auto"
run_test "shaders/fragcoord_w" 0.0 "framework/../bin/shader_runner tests/shaders/fragcoord_w.shader_test -auto"
run_test "shaders/getuniform-01" 0.0 "framework/../bin/getuniform-01 -auto"
run_test "shaders/getuniform-02" 0.0 "framework/../bin/getuniform-02 -auto"
run_test "shaders/glsl-algebraic-add-add-1" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-add-1.shader_test -auto"
run_test "shaders/glsl-algebraic-add-add-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-add-2.shader_test -auto"
run_test "shaders/glsl-algebraic-add-add-3" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-add-3.shader_test -auto"
run_test "shaders/glsl-algebraic-add-add-4" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-add-4.shader_test -auto"
run_test "shaders/glsl-algebraic-add-sub-1" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-sub-1.shader_test -auto"
run_test "shaders/glsl-algebraic-add-sub-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-sub-2.shader_test -auto"
run_test "shaders/glsl-algebraic-add-zero" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-zero.shader_test -auto"
run_test "shaders/glsl-algebraic-add-zero-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-add-zero-2.shader_test -auto"
run_test "shaders/glsl-algebraic-div-one" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-div-one.shader_test -auto"
run_test "shaders/glsl-algebraic-div-one-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-div-one-2.shader_test -auto"
run_test "shaders/glsl-algebraic-logicand-false" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicand-false.shader_test -auto"
run_test "shaders/glsl-algebraic-logicand-false-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicand-false-2.shader_test -auto"
run_test "shaders/glsl-algebraic-logicand-true" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicand-true.shader_test -auto"
run_test "shaders/glsl-algebraic-logicand-true-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicand-true-2.shader_test -auto"
run_test "shaders/glsl-algebraic-logicor-false" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicor-false.shader_test -auto"
run_test "shaders/glsl-algebraic-logicor-false-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicor-false-2.shader_test -auto"
run_test "shaders/glsl-algebraic-logicor-true" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicor-true.shader_test -auto"
run_test "shaders/glsl-algebraic-logicor-true-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicor-true-2.shader_test -auto"
run_test "shaders/glsl-algebraic-logicxor-false" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicxor-false.shader_test -auto"
run_test "shaders/glsl-algebraic-logicxor-true" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-logicxor-true.shader_test -auto"
run_test "shaders/glsl-algebraic-mul-mul-1" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-mul-mul-1.shader_test -auto"
run_test "shaders/glsl-algebraic-mul-one" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-mul-one.shader_test -auto"
run_test "shaders/glsl-algebraic-mul-one-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-mul-one-2.shader_test -auto"
run_test "shaders/glsl-algebraic-mul-zero" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-mul-zero.shader_test -auto"
run_test "shaders/glsl-algebraic-neg-neg" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-neg-neg.shader_test -auto"
run_test "shaders/glsl-algebraic-not-equals" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-not-equals.shader_test -auto"
run_test "shaders/glsl-algebraic-not-notequals" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-not-notequals.shader_test -auto"
run_test "shaders/glsl-algebraic-pow-two" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-pow-two.shader_test -auto"
run_test "shaders/glsl-algebraic-rcp-rcp" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-rcp-rcp.shader_test -auto"
run_test "shaders/glsl-algebraic-rcp-rsq" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-rcp-rsq.shader_test -auto"
run_test "shaders/glsl-algebraic-rcp-sqrt" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-rcp-sqrt.shader_test -auto"
run_test "shaders/glsl-algebraic-rcp-sqrt-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-rcp-sqrt-2.shader_test -auto"
run_test "shaders/glsl-algebraic-sub-sub-1" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-sub-sub-1.shader_test -auto"
run_test "shaders/glsl-algebraic-sub-zero" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-sub-zero.shader_test -auto"
run_test "shaders/glsl-algebraic-sub-zero-2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-sub-zero-2.shader_test -auto"
run_test "shaders/glsl-algebraic-sub-zero-3" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-sub-zero-3.shader_test -auto"
run_test "shaders/glsl-algebraic-sub-zero-4" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-algebraic-sub-zero-4.shader_test -auto"
run_test "shaders/glsl-arb-fragment-coord-conventions" 0.0 "framework/../bin/glsl-arb-fragment-coord-conventions -auto"
run_test "shaders/glsl-arb-fragment-coord-conventions-define" 0.0 "framework/../bin/glsl-arb-fragment-coord-conventions-define -auto"
run_test "shaders/glsl-array-bounds-01" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-bounds-01.shader_test -auto"
run_test "shaders/glsl-array-bounds-03" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-bounds-03.shader_test -auto"
run_test "shaders/glsl-array-bounds-04" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-bounds-04.shader_test -auto"
run_test "shaders/glsl-array-bounds-05" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-bounds-05.shader_test -auto"
run_test "shaders/glsl-array-bounds-07" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-bounds-07.shader_test -auto"
run_test "shaders/glsl-array-bounds-08" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-bounds-08.shader_test -auto"
run_test "shaders/glsl-array-compare" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-compare.shader_test -auto"
run_test "shaders/glsl-array-compare-02" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-compare-02.shader_test -auto"
run_test "shaders/glsl-array-length" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-length.shader_test -auto"
run_test "shaders/glsl-array-uniform" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-uniform.shader_test -auto"
run_test "shaders/glsl-array-uniform-length" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-uniform-length.shader_test -auto"
run_test "shaders/glsl-array-varying-01" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-array-varying-01.shader_test -auto"
run_test "shaders/glsl-bindattriblocation" 0.0 "framework/../bin/glsl-bindattriblocation -auto"
run_test "shaders/glsl-bug-22603" 0.0 "framework/../bin/glsl-bug-22603 -auto"
run_test "shaders/glsl-const-builtin-abs" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-abs.shader_test -auto"
run_test "shaders/glsl-const-builtin-acos" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-acos.shader_test -auto"
run_test "shaders/glsl-const-builtin-all" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-all.shader_test -auto"
run_test "shaders/glsl-const-builtin-any" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-any.shader_test -auto"
run_test "shaders/glsl-const-builtin-asin" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-asin.shader_test -auto"
run_test "shaders/glsl-const-builtin-atan" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-atan.shader_test -auto"
run_test "shaders/glsl-const-builtin-ceil" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-ceil.shader_test -auto"
run_test "shaders/glsl-const-builtin-clamp" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-clamp.shader_test -auto"
run_test "shaders/glsl-const-builtin-cos" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-cos.shader_test -auto"
run_test "shaders/glsl-const-builtin-cross" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-cross.shader_test -auto"
run_test "shaders/glsl-const-builtin-degrees" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-degrees.shader_test -auto"
run_test "shaders/glsl-const-builtin-derivatives" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-derivatives.shader_test -auto"
run_test "shaders/glsl-const-builtin-distance" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-distance.shader_test -auto"
run_test "shaders/glsl-const-builtin-dot" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-dot.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-02" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-02.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-03" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-03.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-04" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-04.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-05" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-05.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-06" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-06.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-07" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-07.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-08" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-08.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-09" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-09.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-10" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-10.shader_test -auto"
run_test "shaders/glsl-const-builtin-equal-bool" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-equal-bool.shader_test -auto"
run_test "shaders/glsl-const-builtin-exp" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-exp.shader_test -auto"
run_test "shaders/glsl-const-builtin-exp2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-exp2.shader_test -auto"
run_test "shaders/glsl-const-builtin-faceforward" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-faceforward.shader_test -auto"
run_test "shaders/glsl-const-builtin-floor" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-floor.shader_test -auto"
run_test "shaders/glsl-const-builtin-fract" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-fract.shader_test -auto"
run_test "shaders/glsl-const-builtin-greaterThan" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-greaterThan.shader_test -auto"
run_test "shaders/glsl-const-builtin-greaterThanEqual" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-greaterThanEqual.shader_test -auto"
run_test "shaders/glsl-const-builtin-inversesqrt" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-inversesqrt.shader_test -auto"
run_test "shaders/glsl-const-builtin-length" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-length.shader_test -auto"
run_test "shaders/glsl-const-builtin-lessThan" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-lessThan.shader_test -auto"
run_test "shaders/glsl-const-builtin-lessThanEqual" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-lessThanEqual.shader_test -auto"
run_test "shaders/glsl-const-builtin-log" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-log.shader_test -auto"
run_test "shaders/glsl-const-builtin-log2" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-log2.shader_test -auto"
run_test "shaders/glsl-const-builtin-matrixCompMult" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-matrixCompMult.shader_test -auto"
run_test "shaders/glsl-const-builtin-max" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-max.shader_test -auto"
run_test "shaders/glsl-const-builtin-min" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-min.shader_test -auto"
run_test "shaders/glsl-const-builtin-mix" 0.0 "framework/../bin/shader_runner tests/shaders/glsl-const-builtin-mix.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 170 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

