#!/bin/bash


need_pass=212
failures=0
PIGLIT_PATH=/usr/local/autotest/deps/piglit/piglit/
export PIGLIT_SOURCE_DIR=/usr/local/autotest/deps/piglit/piglit/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PIGLIT_PATH/lib


function run_test()
{
  local name="$1"
  local time="$2"
  local command="$3"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "Running test "$name" of expected runtime $time sec: $command"
  sync
  $command
  if [ $? == 0 ] ; then
    let "need_pass--"
  else
    let "failures++"
  fi
}


pushd $PIGLIT_PATH
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-add-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-eq-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-ne-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-neg-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-selection-bool-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-sub-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-op-uplus-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-outerProduct-vec2-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/fs-transpose-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-matrixCompMult-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-add-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-div-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-eq-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-vec2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x3-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-vec2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat2x4-vec2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-vec3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x2-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-vec3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat3x4-vec3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-vec4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x2-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-mat4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-vec4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-mat4x3-vec4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-mult-vec4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x3-mat2x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat2x4-mat2x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x2-mat3x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat3x4-mat3x4-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x2-mat4x2-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3-using-if" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-ne-mat4x3-mat4x3-using-if.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-neg-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat2x4-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat3x2-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat3x2-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat3x4-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat3x4-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat4x2-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat4x2-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat4x3-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-selection-bool-mat4x3-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat2x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat3x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat3x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat3x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat3x4.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat4x2" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat4x2.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat4x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-float-mat4x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x3-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x3-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x3-mat2x3" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x3-mat2x3.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x4-float" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x4-float.shader_test -auto"
run_test "spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x4-mat2x4" 0.0 "framework/../bin/shader_runner tests/../generated_tests/spec/glsl-1.20/execution/built-in-functions/vs-op-sub-mat2x4-mat2x4.shader_test -auto"
popd

if [ $need_pass == 0 ] ; then
  echo "+---------------------------------------------+"
  echo "| Overall pass, as all 212 tests have passed. |"
  echo "+---------------------------------------------+"
else
  echo "+-----------------------------------------------------------+"
  echo "| Overall failure, as $need_pass tests did not pass and $failures failed. |"
  echo "+-----------------------------------------------------------+"
fi
exit $need_pass

