# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cfs-bandwidth-test: cfs-bandwidth-test.c
	$(CC) -g cfs-bandwidth-test.c -o cfs-bandwidth-test -lpthread
