#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Set the test list for x86 generic (non-ChromeOS device).
mv -f test_list.x86 test_list

