# Copyright 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from autotest_lib.client.cros.webstore_test import ItemType, InstallType

AUTHOR = "Nathan Stoddard (nstoddard@chromium.org)"
NAME = "webstore_InstallTheme"
SUITE = "webstore"
TIME = "SHORT"
TEST_TYPE = "client"

DOC = """
Installs a theme from the CWS. Passes if the theme can be
installed successfully.
"""

job.run_test('webstore_InstallItem',
        item_id='amapkohokabgjplbdgdmjenfgkjjpljp',
        item_type=ItemType.theme, install_type=InstallType.free)
