#!/usr/bin/env python

import common
import os
import sys

class CrashModem(common.Modem):
    def ConnectDone(self, ok, why):
        sys.exit(0)

def setup():
    os.system('/usr/lib/flimflam/test/connect-service cellular 2>/dev/null &')
    return 0

common.setup(setup)
mm = common.ModemManager(common.bus, common.OCMM)
tm0 = CrashModem(mm, '/TestModem/3')
common.cleanup(lambda: sys.exit(1))
common.run()
