#!/usr/bin/env python

import common
import sys

class FailModem(common.Modem):
    def Enable(self, *args, **kwargs):
        raise common.RandomError

common.setup()
mm = common.ModemManager(common.bus, common.OCMM)
tm0 = FailModem(mm, '/TestModem/1')
common.cleanup(lambda: sys.exit(0))
common.run()
