#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if grep -q '^ok$' "$1" 2>/dev/null; then
	kill -TERM $PPID;
fi

echo 'ok' > "$1"
sleep 1
exit 0
