#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if grep -q '^ok$' "$1" 2>/dev/null; then
	kill -TERM $PPID;
fi

if ! grep -q '^first-fail$' "$1" 2>/dev/null; then
	echo 'first-fail' > "$1"
	exit 1
fi

echo 'ok' >> "$1"
exit 0
