# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

low-mem-test: low-mem-test.c
	$(CC) -g low-mem-test.c -o low-mem-test -lpthread
