#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

usage() {
  echo "Usage: $0 <version-tag>"
}

if [[ $# -lt 1 ]]; then
  usage
  exit 0
fi

PACKAGENAME=webgl-tests-${1}

# source locations and revisions, taken from the original DEPS file
WEBGL="https://cvs.khronos.org/svn/repos/registry/trunk/public/webgl/sdk/tests@11002"
WEBGLTO="WebGL"

function update_mirror() {
  LOCALMIRROR=$1
  [ -z "${LOCALMIRROR}" ] && return 0

  echo -n "Update local mirror? [yn] "
  read n
  if [[ "$n" == "y" ]]; then
    cp "${PACKAGENAME}.tar.gz" ${LOCALMIRROR}
  fi
}

function download_stuff() {
  FILESDIR=`dirname $0`

  echo "Getting WebGL stuff"
  for sub in WEBGL; do
    eval svn export \$\{${sub}\} \$\{${sub}TO\}
  done

  tar -cvjf ${PACKAGENAME}.tar.bz2 WebGL
}

download_stuff "$@"
update_mirror

