#!/usr/bin/expect
# usage: expect_scp <remote-ip-addr>:<remote-path> <local-path>

# Sometimes, the network connection time may be more than the default
# timeout duration of expect, i.e., 10 seconds. Hence, set a longer timeout.
set timeout 20

set local_path [lindex $argv 1]
set remote_path [lindex $argv 0]
spawn scp -r "$local_path" "$remote_path"

# The prompts from the remote machine are not deterministic.
# For example, it may prompt (yes/no) for 0, 1, or even 2 times;
# it may or may not prompt the user for a password, etc.
# We used a loop to handle various combinations of such possibilities.
set count 0
while {$count <= 3} {
  incr count
  expect {
    -nocase "(yes/no)?" {send "yes\r"}
    -nocase "password:" {send "test0000\r"; exit}
    # In case the remote machine has closed the connection.
    eof {exit}
  }
}
