#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# setup: mkdir -p "%T/c/usr" && keyctl show @s | awk 'END { print $1 }' > "%T/c/keyring_id"
# args: -b /bin,/bin -b /lib,/lib -b /usr/lib,/usr/lib -b /usr/bin,/usr/bin -b /usr/local,/usr/local -C "%T/c" -w
# args64: -b /lib64,/lib64

read id < keyring_id

[ "$(keyctl show @s | awk 'END { print $1 }')" -ne "$id" ]
