#!/bin/sh
# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# args: -u 1000 -g 1000 -c 2
# note that 2 = CAP_DAC_OVERRIDE

. "$(dirname "$0")"/common.sh

needreuid 1000
needregid 1000

[ ! -w "$0" ] && die "Can't write to '$0'"
exit 0
